package me.bruno.packbuilder.enums.texture;

import me.bruno.packbuilder.enums.Files;

public enum Block implements Files {

    // textures/block

    TEXTURES_BLOCK_ACACIA_DOOR_BOTTOM("textures\\block", "acacia_door_bottom", "door_acacia_lower", "1.8"),
    TEXTURES_BLOCK_ACACIA_DOOR_TOP("textures\\block", "acacia_door_top", "door_acacia_upper", "1.8"),
    TEXTURES_BLOCK_ACACIA_LEAVES("textures\\block", "acacia_leaves", "leaves_acacia", "1.7"),
    TEXTURES_BLOCK_ACACIA_LOG("textures\\block", "acacia_log", "log_acacia", "1.7"),
    TEXTURES_BLOCK_ACACIA_LOG_TOP("textures\\block", "acacia_log_top", "log_acacia_top", "1.7"),
    TEXTURES_BLOCK_ACACIA_PLANKS("textures\\block", "acacia_planks", "planks_acacia", "1.7"),
    TEXTURES_BLOCK_ACACIA_SAPLING("textures\\block", "acacia_sapling", "sapling_acacia", "1.7"),
    TEXTURES_BLOCK_ACACIA_TRAPDOOR("textures\\block", "acacia_trapdoor", "1.13"),
    TEXTURES_BLOCK_ACTIVATOR_RAIL("textures\\block", "activator_rail", "rail_activator", "1.6"),
    TEXTURES_BLOCK_ACTIVATOR_RAIL_ON("textures\\block", "activator_rail_on", "rail_activator_powered", "1.6"),
    TEXTURES_BLOCK_ALLIUM("textures\\block", "allium", "flower_allium", "1.7"),
    TEXTURES_BLOCK_AMETHYST_BLOCK("textures\\block", "amethyst_block", "1.17"),
    TEXTURES_BLOCK_AMETHYST_CLUSTER("textures\\block", "amethyst_cluster", "1.17"),
    TEXTURES_BLOCK_ANCIENT_DEBRIS_SIDE("textures\\block", "ancient_debris_side", "1.16"),
    TEXTURES_BLOCK_ANCIENT_DEBRIS_TOP("textures\\block", "ancient_debris_top", "1.16"),
    TEXTURES_BLOCK_ANDESITE("textures\\block", "andesite", "stone_andesite", "1.8"),
    TEXTURES_BLOCK_ANVIL("textures\\block", "anvil", "anvil_base", "1.6"),
    TEXTURES_BLOCK_ANVIL_TOP("textures\\block", "anvil_top", "anvil_top_damaged_0", "1.6"),
    TEXTURES_BLOCK_ATTACHED_MELON_STEM("textures\\block", "attach  ed_melon_stem", "melon_stem_connected", "1.6"),
    TEXTURES_BLOCK_ATTACHED_PUMPKIN_STEM("textures\\block", "attached_pumpkin_stem", "pumpkin_stem_connected", "1.6"),
    TEXTURES_BLOCK_AZALEA_LEAVES("textures\\block", "azalea_leaves", "1.17"),
    TEXTURES_BLOCK_AZALEA_PLANT("textures\\block", "azalea_plant", "1.17"),
    TEXTURES_BLOCK_AZALEA_SIDE("textures\\block", "azalea_side", "1.17"),
    TEXTURES_BLOCK_AZALEA_TOP("textures\\block", "azalea_top", "1.17"),
    TEXTURES_BLOCK_AZURE_BLUET("textures\\block", "azure_bluet", "flower_houstonia",  "1.7"),
    TEXTURES_BLOCK_BAMBOO_LARGE_LEAVES("textures\\block", "bamboo_large_leaves",  "1.14"),
    TEXTURES_BLOCK_BAMBOO_SINGLELEAF("textures\\block", "bamboo_singleleaf",  "1.14"),
    TEXTURES_BLOCK_BAMBOO_SMALL_LEAVES("textures\\block", "bamboo_small_leaves",  "1.14"),
    TEXTURES_BLOCK_BAMBOO_STAGE0("textures\\block", "bamboo_stage0",  "1.14"),
    TEXTURES_BLOCK_BAMBOO_STALK("textures\\block", "bamboo_stalk",  "1.14"),
    TEXTURES_BLOCK_BARREL_BOTTOM("textures\\block", "barrel_bottom",  "1.14"),
    TEXTURES_BLOCK_BARREL_SIDE("textures\\block", "barrel_side",  "1.14"),
    TEXTURES_BLOCK_BARREL_TOP("textures\\block", "barrel_top",  "1.14"),
    TEXTURES_BLOCK_BARREL_TOP_OPEN("textures\\block", "barrel_top_open",  "1.14"),
    TEXTURES_BLOCK_BASALT_SIDE("textures\\block", "basalt_side", "1.16"),
    TEXTURES_BLOCK_BASALT_TOP("textures\\block", "basalt_top", "1.16"),
    TEXTURES_BLOCK_BEACON("textures\\block", "beacon", "1.6"),
    TEXTURES_BLOCK_BEDROCK("textures\\block", "bedrock", "1.6"),
    TEXTURES_BLOCK_BEE_NEST_BOTTOM("textures\\block", "bee_nest_bottom", "1.15"),
    TEXTURES_BLOCK_BEE_NEST_FRONT("textures\\block", "bee_nest_front", "1.15"),
    TEXTURES_BLOCK_BEE_NEST_FRONT_HONEY("textures\\block", "bee_nest_front_honey", "1.15"),
    TEXTURES_BLOCK_BEE_NEST_SIDE("textures\\block", "bee_nest_side", "1.15"),
    TEXTURES_BLOCK_BEE_NEST_TOP("textures\\block", "bee_nest_top", "1.15"),
    TEXTURES_BLOCK_BEEHIVE_END("textures\\block", "beehive_end", "1.15"),
    TEXTURES_BLOCK_BEEHIVE_FRONT("textures\\block", "beehive_front", "1.15"),
    TEXTURES_BLOCK_BEEHIVE_FRONT_HONEY("textures\\block", "beehive_front_honey", "1.15"),
    TEXTURES_BLOCK_BEEHIVE_SIDE("textures\\block", "beehive_side", "1.15"),
    TEXTURES_BLOCK_BEETROOTS_STAGE0("textures\\block", "beetroots_stage0", "beetroots_stage_0", "1.9"),
    TEXTURES_BLOCK_BEETROOTS_STAGE1("textures\\block", "beetroots_stage1", "beetroots_stage_1", "1.9"),
    TEXTURES_BLOCK_BEETROOTS_STAGE2("textures\\block", "beetroots_stage2", "beetroots_stage_2", "1.9"),
    TEXTURES_BLOCK_BEETROOTS_STAGE3("textures\\block", "beetroots_stage3", "beetroots_stage_3", "1.9"),
    TEXTURES_BLOCK_BELL_BOTTOM("textures\\block", "bell_bottom", "1.14"),
    TEXTURES_BLOCK_BELL_SIDE("textures\\block", "bell_side", "1.14"),
    TEXTURES_BLOCK_BELL_TOP("textures\\block", "bell_top", "1.14"),
    TEXTURES_BLOCK_BIG_DRIPLEAF_SIDE("textures\\block", "big_dripleaf_side", "1.17"),
    TEXTURES_BLOCK_BIG_DRIPLEAF_TIP("textures\\block", "big_dripleaf_tip", "1.17"),
    TEXTURES_BLOCK_BIG_DRIPLEAF_TOP("textures\\block", "big_dripleaf_top", "1.17"),
    TEXTURES_BLOCK_BIRCH_DOOR_BOTTOM("textures\\block", "birch_door_bottom", "door_birch_lower", "1.8"),
    TEXTURES_BLOCK_BIRCH_DOOR_TOP("textures\\block", "birch_door_top", "door_birch_upper", "1.8"),
    TEXTURES_BLOCK_BIRCH_LEAVES("textures\\block", "birch_leaves", "leaves_birch", "1.6"),
    TEXTURES_BLOCK_BIRCH_LOG("textures\\block", "birch_log", "log_birch", "1.6"),
    TEXTURES_BLOCK_BIRCH_LOG_TOP("textures\\block", "birch_log_top", "log_birch_top", "1.6"),
    TEXTURES_BLOCK_BIRCH_PLANKS("textures\\block", "birch_planks", "planks_birch", "1.6"),
    TEXTURES_BLOCK_BIRCH_SAPLING("textures\\block", "birch_sapling", "sapling_birch", "1.6"),
    TEXTURES_BLOCK_BIRCH_TRAPDOOR("textures\\block", "birch_trapdoor", "1.13"),
    TEXTURES_BLOCK_BLACK_CANDLE("textures\\block", "black_candle", "1.17"),
    TEXTURES_BLOCK_BLACK_CANDLE_LIT("textures\\block", "black_candle_lit", "1.17"),
    TEXTURES_BLOCK_BLACK_CONCRETE("textures\\block", "black_concrete", "concrete_black", "1.12"),
    TEXTURES_BLOCK_BLACK_CONCRETE_POWDER("textures\\block", "black_concrete_powder", "concrete_powder_black", "1.12"),
    TEXTURES_BLOCK_BLACK_GLAZED_TERRACOTTA("textures\\block", "black_glazed_terracotta", "glazed_terracotta_black", "1.12"),
    TEXTURES_BLOCK_BLACK_SHULKER_BOX("textures\\block", "black_shulker_box", "shulker_top_black", "1.11"),
    TEXTURES_BLOCK_BLACK_STAINED_GLASS("textures\\block", "black_stained_glass", "glass_black", "1.7"),
    TEXTURES_BLOCK_BLACK_STAINED_GLASS_PANE_TOP("textures\\block", "black_stained_glass_pane_top", "glass_pane_top_black", "1.7"),
    TEXTURES_BLOCK_BLACK_TERRACOTTA("textures\\block", "black_terracotta", "hardened_clay_stained_black", "1.6"),
    TEXTURES_BLOCK_BLACK_WOOL("textures\\block", "black_wool", "wool_colored_black", "1.6"),
    TEXTURES_BLOCK_BLACKSTONE("textures\\block", "blackstone", "1.16"),
    TEXTURES_BLOCK_BLACKSTONE_TOP("textures\\block", "blackstone_top", "1.16"),
    TEXTURES_BLOCK_BLAST_FURNACE_FRONT("textures\\block", "blast_furnace_front", "1.14"),
    TEXTURES_BLOCK_BLAST_FURNACE_FRONT_LIT("textures\\block", "blast_furnace_front_lit", "1.14"),
    TEXTURES_BLOCK_BLAST_FURNACE_SIDE("textures\\block", "blast_furnace_side", "1.14"),
    TEXTURES_BLOCK_BLAST_FURNACE_TOP("textures\\block", "blast_furnace_top", "1.14"),
    TEXTURES_BLOCK_BLUE_CANDLE("textures\\block", "blue_candle", "1.17"),
    TEXTURES_BLOCK_BLUE_CANDLE_LIT("textures\\block", "blue_candle_lit", "1.17"),
    TEXTURES_BLOCK_BLUE_CONCRETE("textures\\block", "blue_concrete", "concrete_blue", "1.12"),
    TEXTURES_BLOCK_BLUE_CONCRETE_POWDER("textures\\block", "blue_concrete_powder", "concrete_powder_blue", "1.12"),
    TEXTURES_BLOCK_BLUE_GLAZED_TERRACOTTA("textures\\block", "blue_glazed_terracotta", "glazed_terracotta_blue", "1.12"),
    TEXTURES_BLOCK_BLUE_ICE("textures\\block", "blue_ice", "1.13"),
    TEXTURES_BLOCK_BLUE_SHULKER_BOX("textures\\block", "blue_shulker_box", "shulker_top_blue", "1.11"),
    TEXTURES_BLOCK_BLUE_STAINED_GLASS("textures\\block", "blue_stained_glass", "glass_blue", "1.7"),
    TEXTURES_BLOCK_BLUE_STAINED_GLASS_PANE_TOP("textures\\block", "blue_stained_glass_pane_top", "glass_pane_top_blue", "1.7"),
    TEXTURES_BLOCK_BLUE_TERRACOTTA("textures\\block", "blue_terracotta", "hardened_clay_stained_blue", "1.6"),
    TEXTURES_BLOCK_BLUE_WOOL("textures\\block", "blue_wool", "wool_colored_blue", "1.6"),
    TEXTURES_BLOCK_BONE_BLOCK_SIDE("textures\\block", "bone_block_side", "1.13"),
    TEXTURES_BLOCK_BONE_BLOCK_TOP("textures\\block", "bone_block_top", "1.13"),
    TEXTURES_BLOCK_BOOKSHELF("textures\\block", "bookshelf", "1.6"),
    TEXTURES_BLOCK_BRAIN_CORAL("textures\\block", "brain_coral", "1.13"),
    TEXTURES_BLOCK_BRAIN_CORAL_BLOCK("textures\\block", "brain_coral_block", "1.13"),
    TEXTURES_BLOCK_BRAIN_CORAL_FAN("textures\\block", "brain_coral_fan", "1.13"),
    TEXTURES_BLOCK_BREWING_STAND("textures\\block", "brewing_stand", "1.6"),
    TEXTURES_BLOCK_BREWING_STAND_BASE("textures\\block", "brewing_stand_base", "1.6"),
    TEXTURES_BLOCK_BRICKS("textures\\block", "bricks", "brick", "1.6"),
    TEXTURES_BLOCK_BROWN_CANDLE("textures\\block", "brown_candle", "1.17"),
    TEXTURES_BLOCK_BROWN_CANDLE_LIT("textures\\block", "brown_candle_lit", "1.17"),
    TEXTURES_BLOCK_BROWN_CONCRETE("textures\\block", "brown_concrete", "concrete_brown", "1.12"),
    TEXTURES_BLOCK_BROWN_CONCRETE_POWDER("textures\\block", "brown_concrete_powder", "concrete_powder_brown", "1.12"),
    TEXTURES_BLOCK_BROWN_GLAZED_TERRACOTTA("textures\\block", "brown_glazed_terracotta", "glazed_terracotta_brown", "1.12"),
    TEXTURES_BLOCK_BROWN_MUSHROOM("textures\\block", "brown_mushroom", "mushroom_brown", "1.6"),
    TEXTURES_BLOCK_BROWN_MUSHROOM_BLOCK("textures\\block", "brown_mushroom_block", "mushroom_block_skin_brown", "1.6"),
    TEXTURES_BLOCK_BROWN_SHULKER_BOX("textures\\block", "brown_shulker_box", "shulker_top_brown", "1.11"),
    TEXTURES_BLOCK_BROWN_STAINED_GLASS("textures\\block", "brown_stained_glass", "glass_brown", "1.7"),
    TEXTURES_BLOCK_BROWN_STAINED_GLASS_PANE_TOP("textures\\block", "brown_stained_glass_pane_top", "glass_pane_top_brown", "1.7"),
    TEXTURES_BLOCK_BROWN_TERRACOTTA("textures\\block", "brown_terracotta", "hardened_clay_stained_brown", "1.6"),
    TEXTURES_BLOCK_BROWN_WOOL("textures\\block", "brown_wool", "wool_colored_brown", "1.6"),
    TEXTURES_BLOCK_BUBBLE_CORAL("textures\\block", "bubble_coral", "1.13"),
    TEXTURES_BLOCK_BUBBLE_CORAL_BLOCK("textures\\block", "bubble_coral_block", "1.13"),
    TEXTURES_BLOCK_BUBBLE_CORAL_FAN("textures\\block", "bubble_coral_fan", "1.13"),
    TEXTURES_BLOCK_BUDDING_AMETHYST("textures\\block", "budding_amethyst", "1.17"),
    TEXTURES_BLOCK_CACTUS_BOTTOM("textures\\block", "cactus_bottom", "1.6"),
    TEXTURES_BLOCK_CACTUS_SIDE("textures\\block", "cactus_side", "1.6"),
    TEXTURES_BLOCK_CACTUS_TOP("textures\\block", "cactus_top", "1.6"),
    TEXTURES_BLOCK_CAKE_BOTTOM("textures\\block", "cake_bottom", "1.6"),
    TEXTURES_BLOCK_CAKE_INNER("textures\\block", "cake_inner", "1.6"),
    TEXTURES_BLOCK_CAKE_SIDE("textures\\block", "cake_side", "1.6"),
    TEXTURES_BLOCK_CAKE_TOP("textures\\block", "cake_top", "1.6"),
    TEXTURES_BLOCK_CALCITE("textures\\block", "calcite", "1.17"),
    TEXTURES_BLOCK_CAMPFIRE_FIRE("textures\\block", "campfire_fire", "1.14"),
    TEXTURES_BLOCK_CAMPFIRE_LOG("textures\\block", "campfire_log", "1.14"),
    TEXTURES_BLOCK_CAMPFIRE_LOG_LIT("textures\\block", "campfire_log_lit", "1.14"),
    TEXTURES_BLOCK_CANDLE("textures\\block", "candle", "1.17"),
    TEXTURES_BLOCK_CANDLE_LIT("textures\\block", "candle_lit", "1.17"),
    TEXTURES_BLOCK_CARROTS_STAGE0("textures\\block", "carrots_stage0", "carrots_stage_0", "1.6"),
    TEXTURES_BLOCK_CARROTS_STAGE1("textures\\block", "carrots_stage1", "carrots_stage_1", "1.6"),
    TEXTURES_BLOCK_CARROTS_STAGE2("textures\\block", "carrots_stage2", "carrots_stage_2", "1.6"),
    TEXTURES_BLOCK_CARROTS_STAGE3("textures\\block", "carrots_stage3", "carrots_stage_3", "1.6"),
    TEXTURES_BLOCK_CARTOGRAPHY_TABLE_SIDE1("textures\\block", "cartography_table_side1", "1.14"),
    TEXTURES_BLOCK_CARTOGRAPHY_TABLE_SIDE2("textures\\block", "cartography_table_side2", "1.14"),
    TEXTURES_BLOCK_CARTOGRAPHY_TABLE_SIDE3("textures\\block", "cartography_table_side3", "1.14"),
    TEXTURES_BLOCK_CARTOGRAPHY_TABLE_TOP("textures\\block", "cartography_table_top", "1.14"),
    TEXTURES_BLOCK_CARVED_PUMPKIN("textures\\block", "carved_pumpkin", "pumpkin_face_off", "1.6"),
    TEXTURES_BLOCK_CAULDRON_BOTTOM("textures\\block", "cauldron_bottom", "1.6"),
    TEXTURES_BLOCK_CAULDRON_INNER("textures\\block", "cauldron_inner", "1.6"),
    TEXTURES_BLOCK_CAULDRON_SIDE("textures\\block", "cauldron_side", "1.6"),
    TEXTURES_BLOCK_CAULDRON_TOP("textures\\block", "cauldron_top", "1.6"),
    TEXTURES_BLOCK_CAVE_VINES("textures\\block", "cave_vines", "1.17"),
    TEXTURES_BLOCK_CAVE_VINES_LIT("textures\\block", "cave_vines_lit", "1.17"),
    TEXTURES_BLOCK_CAVE_VINES_PLANT("textures\\block", "cave_vines_plant", "1.17"),
    TEXTURES_BLOCK_CAVE_VINES_PLANT_LIT("textures\\block", "cave_vines_plant_lit", "1.17"),
    TEXTURES_BLOCK_CHAIN("textures\\block", "chain", "1.16"),
    TEXTURES_BLOCK_CHAIN_COMMAND_BLOCK_BACK("textures\\block", "chain_command_block_back", "1.9"),
    TEXTURES_BLOCK_CHAIN_COMMAND_BLOCK_CONDITIONAL("textures\\block", "chain_command_block_contitional", "1.9"),
    TEXTURES_BLOCK_CHAIN_COMMAND_BLOCK_FRONT("textures\\block", "chain_command_block_front", "1.9"),
    TEXTURES_BLOCK_CHAIN_COMMAND_BLOCK_SIDE("textures\\block", "chain_command_block_side", "1.9"),
    TEXTURES_BLOCK_CHIPPED_ANVIL_TOP("textures\\block", "chipped_anvil_top", "anvil_top_damaged_1", "1.6"),
    TEXTURES_BLOCK_CHISELED_DEEPSLATE("textures\\block", "chiseled_deepslate", "1.17"),
    TEXTURES_BLOCK_CHISELED_NETHER_BRICKS("textures\\block", "chiseled_nether_bricks", "1.16"),
    TEXTURES_BLOCK_CHISELED_POLISHED_BLACKSTONE("textures\\block", "chiseled_polished_blackstone", "1.16"),
    TEXTURES_BLOCK_CHISELED_QUARTZ_BLOCK("textures\\block", "chiseled_quartz_block", "quartz_block_chiseled", "1.6"),
    TEXTURES_BLOCK_CHISELED_QUARTZ_BLOCK_TOP("textures\\block", "chiseled_quartz_block_top", "quartz_block_chiseled_top", "1.6"),
    TEXTURES_BLOCK_CHISELED_RED_SANDSTONE("textures\\block", "chiseled_red_sandstone", "red_sandstone_carved", "1.8"),
    TEXTURES_BLOCK_CHISELED_SANDSTONE("textures\\block", "chiseled_sandstone", "sandstone_carved", "1.6"),
    TEXTURES_BLOCK_CHISELED_STONE_BRICKS("textures\\block", "chiseled_stone_bricks", "stonebrick_carved", "1.6"),
    TEXTURES_BLOCK_CHORUS_FLOWER("textures\\block", "chorus_flower", "1.9"),
    TEXTURES_BLOCK_CHORUS_FLOWER_DEAD("textures\\block", "chorus_flower_dead", "1.9"),
    TEXTURES_BLOCK_CHORUS_PLANT("textures\\block", "chorus_plant", "1.9"),
    TEXTURES_BLOCK_CLAY("textures\\block", "clay", "1.6"),
    TEXTURES_BLOCK_COAL_BLOCK("textures\\block", "coal_block", "1.6"),
    TEXTURES_BLOCK_COAL_ORE("textures\\block", "coal_ore", "1.6"),
    TEXTURES_BLOCK_COARSE_DIRT("textures\\block", "coarse_dirt", "1.8"),
    TEXTURES_BLOCK_COBBLED_DEEPSLATE("textures\\block", "cobbled_deepslate", "1.13"),
    TEXTURES_BLOCK_COBBLESTONE("textures\\block", "cobblestone", "1.6"),
    TEXTURES_BLOCK_COBWEB("textures\\block", "cobweb", "web", "1.6"),
    TEXTURES_BLOCK_COCOA_STAGE0("textures\\block", "cocoa_stage0", "cocoa_stage_0", "1.6"),
    TEXTURES_BLOCK_COCOA_STAGE1("textures\\block", "cocoa_stage1", "cocoa_stage_1", "1.6"),
    TEXTURES_BLOCK_COCOA_STAGE2("textures\\block", "cocoa_stage2", "cocoa_stage_2", "1.6"),
    TEXTURES_BLOCK_COMMAND_BLOCK_BACK("textures\\block","command_block_back", "command_block", "1.6"),
    TEXTURES_BLOCK_COMMAND_BLOCK_CONDITIONAL("textures\\block", "command_block_conditional", "1.9"),
    TEXTURES_BLOCK_COMMAND_BLOCK_FRONT("textures\\block", "command_block_front", "1.9"),
    TEXTURES_BLOCK_COMMAND_BLOCK_SIDE("textures\\block", "command_block_side", "1.9"),
    TEXTURES_BLOCK_COMPARATOR("textures\\block", "comparator", "comparator_off", "1.6"),
    TEXTURES_BLOCK_COMPARATOR_ON("textures\\block", "comparator_on", "1.6"),
    TEXTURES_BLOCK_COMPOSTER_BOTTOM("textures\\block", "composter_bottom", "1.14"),
    TEXTURES_BLOCK_COMPOSTER_COMPOST("textures\\block", "composter_compost", "1.14"),
    TEXTURES_BLOCK_COMPOSTER_READY("textures\\block", "composter_ready", "1.14"),
    TEXTURES_BLOCK_COMPOSTER_SIDE("textures\\block", "composter_side", "1.14"),
    TEXTURES_BLOCK_COMPOSTER_TOP("textures\\block", "composter_top", "1.14"),
    TEXTURES_BLOCK_CONDUIT("textures\\block", "conduit", "1.13"),
    TEXTURES_BLOCK_COPPER_BLOCK("textures\\block", "copper_block", "1.17"),
    TEXTURES_BLOCK_COPPER_ORE("textures\\block", "copper_ore", "1.17"),
    TEXTURES_BLOCK_CORNFLOWER("textures\\block", "cornflower", "1.14"),
    TEXTURES_BLOCK_CRACKED_DEEPSLATE_BRICKS("textures\\block", "cracked_deepslate_bricks", "1.17"),
    TEXTURES_BLOCK_CRACKED_NETHER_BRICKS("textures\\block", "cracked_nether_bricks", "1.16"),
    TEXTURES_BLOCK_CRACKED_POLISHED_BLACKSTONE_BRICKS("textures\\block", "cracked_polished_blackstone_bricks", "1.16"),
    TEXTURES_BLOCK_CRACKED_STONE_BRICKS("textures\\block", "cracked_stone_bricks", "stonebrick_cracked", "1.6"),
    TEXTURES_BLOCK_CRAFTING_TABLE_FRONT("textures\\block", "crafting_table_front", "1.6"),
    TEXTURES_BLOCK_CRAFTING_TABLE_SIDE("textures\\block", "crafting_table_side", "1.6"),
    TEXTURES_BLOCK_CRAFTING_TABLE_TOP("textures\\block", "crafting_table_top", "1.6"),
    TEXTURES_BLOCK_CRIMSON_DOOR_BOTTOM("textures\\block", "crimson_door_bottom", "1.16"),
    TEXTURES_BLOCK_CRIMSON_DOOR_TOP("textures\\block", "crimson_door_top", "1.16"),
    TEXTURES_BLOCK_CRIMSON_FUNGUS("textures\\block", "crimson_fungus", "1.16"),
    TEXTURES_BLOCK_CRIMSON_NYLIUM("textures\\block", "crimson_nylium", "1.16"),
    TEXTURES_BLOCK_CRIMSON_NYLIUM_SIDE("textures\\block", "crimson_nylium_side", "1.16"),
    TEXTURES_BLOCK_CRIMSON_PLANKS("textures\\block", "crimson_planks", "1.16"),
    TEXTURES_BLOCK_CRIMSON_ROOTS("textures\\block", "crimson_roots", "1.16"),
    TEXTURES_BLOCK_CRIMSON_ROOTS_POT("textures\\block", "crimson_roots_pot", "1.16"),
    TEXTURES_BLOCK_CRIMSON_STEM("textures\\block", "crimson_stem", "1.16"),
    TEXTURES_BLOCK_CRIMSON_STEM_TOP("textures\\block", "crimson_stem_top", "1.16"),
    TEXTURES_BLOCK_CRIMSON_TRAPDOOR("textures\\block", "crimson_trapdoor", "1.16"),
    TEXTURES_BLOCK_CRYING_OBSIDIAN("textures\\block", "crying_obsidian", "1.16"),
    TEXTURES_BLOCK_CUT_COPPER("textures\\block", "cut_copper", "1.17"),
    TEXTURES_BLOCK_CUT_RED_SANDSTONE("textures\\block", "cut_red_sandstone", "red_sandstone_smooth", "1.8"),
    TEXTURES_BLOCK_CUT_SANDSTONE("textures\\block", "cut_sandstone", "sandstone_smooth", "1.8"),
    TEXTURES_BLOCK_CYAN_CANDLE("textures\\block", "cyan_candle", "1.17"),
    TEXTURES_BLOCK_CYAN_CANDLE_LIT("textures\\block", "cyan_candle_lit", "1.17"),
    TEXTURES_BLOCK_CYAN_CONCRETE("textures\\block", "cyan_concrete", "concrete_cyan", "1.12"),
    TEXTURES_BLOCK_CYAN_CONCRETE_POWDER("textures\\block", "cyan_concrete_powder", "concrete_powder_cyan", "1.12"),
    TEXTURES_BLOCK_CYAN_GLAZED_TERRACOTTA("textures\\block", "cyan_glazed_terracotta", "glazed_terracotta_cyan", "1.12"),
    TEXTURES_BLOCK_CYAN_SHULKER_BOX("textures\\block", "cyan_shulker_box", "shulker_top_cyan", "1.11"),
    TEXTURES_BLOCK_CYAN_STAINED_GLASS("textures\\block", "cyan_stained_glass", "glass_cyan", "1.7"),
    TEXTURES_BLOCK_CYAN_STAINED_GLASS_PANE_TOP("textures\\block", "cyan_stained_glass_pane_top", "glass_pane_top_cyan", "1.7"),
    TEXTURES_BLOCK_CYAN_TERRACOTTA("textures\\block", "cyan_terracotta", "hardened_clay_stained_cyan", "1.6"),
    TEXTURES_BLOCK_CYAN_WOOL("textures\\block", "cyan_wool", "wool_colored_cyan", "1.6"),
    TEXTURES_BLOCK_DANDELION("textures\\block", "dandelion", "flower_dandelion", "1.6"),
    TEXTURES_BLOCK_DARK_OAK_DOOR_BOTTOM("textures\\block", "dark_oak_door_bottom", "door_dark_oak_lower", "1.8"),
    TEXTURES_BLOCK_DARK_OAK_DOOR_TOP("textures\\block", "dark_oak_door_top", "door_dark_oak_upper", "1.8"),
    TEXTURES_BLOCK_DARK_OAK_LEAVES("textures\\block", "dark_oak_leaves", "leaves_big_oak", "1.7"),
    TEXTURES_BLOCK_DARK_OAK_LOG("textures\\block", "dark_oak_log", "log_big_oak", "1.7"),
    TEXTURES_BLOCK_DARK_OAK_LOG_TOP("textures\\block", "dark_oak_log_top", "log_big_oak_top", "1.7"),
    TEXTURES_BLOCK_DARK_OAK_PLANKS("textures\\block", "dark_oak_planks", "planks_big_oak", "1.7"),
    TEXTURES_BLOCK_DARK_OAK_SAPLING("textures\\block", "dark_oak_sapling", "sapling_roofed_oak", "1.7"),
    TEXTURES_BLOCK_DARK_OAK_TRAPDOOR("textures\\block", "dark_oak_trapdoor", "1.13"),
    TEXTURES_BLOCK_DARK_PRISMARINE("textures\\block", "dark_prismarine", "prismarine_dark", "1.8"),
    TEXTURES_BLOCK_DAYLIGHT_DETECTOR_INVERTED_TOP("textures\\block", "daylight_detector_inverted_top", "1.8"),
    TEXTURES_BLOCK_DAYLIGHT_DETECTOR_SIDE("textures\\block", "daylight_detector_side", "1.6"),
    TEXTURES_BLOCK_DAYLIGHT_DETECTOR_TOP("textures\\block", "daylight_detector_side", "1.6"),
    TEXTURES_BLOCK_DEAD_BRAIN_CORAL("textures\\block", "dead_brain_coral", "1.13"),
    TEXTURES_BLOCK_DEAD_BRAIN_CORAL_BLOCK("textures\\block", "dead_brain_coral_block", "1.13"),
    TEXTURES_BLOCK_DEAD_BRAIN_CORAL_FAN("textures\\block", "dead_brain_coral_fan", "1.13"),
    TEXTURES_BLOCK_DEAD_BUBBLE_CORAL("textures\\block", "dead_bubble_coral", "1.13"),
    TEXTURES_BLOCK_DEAD_BUBBLE_CORAL_BLOCK("textures\\block", "dead_bubble_coral_block", "1.13"),
    TEXTURES_BLOCK_DEAD_BUBBLE_CORAL_FAN("textures\\block", "dead_bubble_coral_fan", "1.13"),
    TEXTURES_BLOCK_DEAD_BUSH("textures\\block", "dead_bush", "deadbush", "1.6"),
    TEXTURES_BLOCK_DEAD_FIRE_CORAL("textures\\block", "dead_fire_coral", "1.13"),
    TEXTURES_BLOCK_DEAD_FIRE_CORAL_BLOCK("textures\\block", "dead_fire_coral_block", "1.13"),
    TEXTURES_BLOCK_DEAD_FIRE_CORAL_FAN("textures\\block", "dead_fire_coral_fan", "1.13"),
    TEXTURES_BLOCK_DEAD_HORN_CORAL("textures\\block", "dead_horn_coral", "1.13"),
    TEXTURES_BLOCK_DEAD_HORN_CORAL_BLOCK("textures\\block", "dead_horn_coral_block", "1.13"),
    TEXTURES_BLOCK_DEAD_HORN_CORAL_FAN("textures\\block", "dead_horn_coral_fan", "1.13"),
    TEXTURES_BLOCK_DEAD_TUBE_CORAL("textures\\block", "dead_tube_coral", "1.13"),
    TEXTURES_BLOCK_DEAD_TUBE_CORAL_BLOCK("textures\\block", "dead_tube_coral_block", "1.13"),
    TEXTURES_BLOCK_DEAD_TUBE_CORAL_FAN("textures\\block", "dead_tube_coral_fan", "1.13"),
    TEXTURES_BLOCK_DEEPSLATE("textures\\block", "deepslate", "1.17"),
    TEXTURES_BLOCK_DEEPSLATE_BRICKS("textures\\block", "deepslate_bricks", "1.17"),
    TEXTURES_BLOCK_DEEPSLATE_COAL_ORE("textures\\block", "deepslate_coal_ore", "1.17"),
    TEXTURES_BLOCK_DEEPSLATE_COPPER_ORE("textures\\block", "deepslate_copper_ore", "1.17"),
    TEXTURES_BLOCK_DEEPSLATE_DIAMOND_ORE("textures\\block", "deepslate_diamond_ore", "1.17"),
    TEXTURES_BLOCK_DEEPSLATE_EMERALD_ORE("textures\\block", "deepslate_emerald_ore", "1.17"),
    TEXTURES_BLOCK_DEEPSLATE_IRON_ORE("textures\\block", "deepslate_iron_ore", "1.17"),
    TEXTURES_BLOCK_DEEPSLATE_GOLD_ORE("textures\\block", "deepslate_gold_ore", "1.17"),
    TEXTURES_BLOCK_DEEPSLATE_LAPIS_ORE("textures\\block", "deepslate_lapis_ore", "1.17"),
    TEXTURES_BLOCK_DEEPSLATE_REDSTONE_ORE("textures\\block", "deepslate_redstone_ore", "1.17"),
    TEXTURES_BLOCK_DEEPSLATE_TILES("textures\\block", "deepslate_tiles", "1.17"),
    TEXTURES_BLOCK_DEEPSLATE_TOP("textures\\block", "deepslate_top", "1.17"),
    TEXTURES_BLOCK_DESTROY_STAGE_0("textures\\block", "destroy_stage_0", "1.6"),
    TEXTURES_BLOCK_DESTROY_STAGE_1("textures\\block", "destroy_stage_1", "1.6"),
    TEXTURES_BLOCK_DESTROY_STAGE_2("textures\\block", "destroy_stage_2", "1.6"),
    TEXTURES_BLOCK_DESTROY_STAGE_3("textures\\block", "destroy_stage_3", "1.6"),
    TEXTURES_BLOCK_DESTROY_STAGE_4("textures\\block", "destroy_stage_4", "1.6"),
    TEXTURES_BLOCK_DESTROY_STAGE_5("textures\\block", "destroy_stage_5", "1.6"),
    TEXTURES_BLOCK_DESTROY_STAGE_6("textures\\block", "destroy_stage_6", "1.6"),
    TEXTURES_BLOCK_DESTROY_STAGE_7("textures\\block", "destroy_stage_7", "1.6"),
    TEXTURES_BLOCK_DESTROY_STAGE_8("textures\\block", "destroy_stage_8", "1.6"),
    TEXTURES_BLOCK_DESTROY_STAGE_9("textures\\block", "destroy_stage_9", "1.6"),
    TEXTURES_BLOCK_DETECTOR_RAIL("textures\\block", "detector_rail", "rail_detector", "1.6"),
    TEXTURES_BLOCK_DETECTOR_RAIL_ON("textures\\block", "detector_rail_on", "rail_detector_powered", "1.6"),
    TEXTURES_BLOCK_DIAMOND_BLOCK("textures\\block", "diamond_block", "1.6"),
    TEXTURES_BLOCK_DIAMOND_ORE("textures\\block", "diamond_ore", "1.6"),
    TEXTURES_BLOCK_DIORITE("textures\\block", "diorite", "stone_diorite", "1.8"),
    TEXTURES_BLOCK_DIRT("textures\\block", "dirt", "1.6"),
    TEXTURES_BLOCK_DIRT_PATH_SIDE("textures\\block", "dirt_path_side", "grass_path_side", "1.9"),
    TEXTURES_BLOCK_DIRT_PATH_TOP("textures\\block", "dirt_path_top", "grass_path_top", "1.9"),
    TEXTURES_BLOCK_DISPENSER_FRONT("textures\\block", "dispenser_front", "dispenser_front_horizontal", "1.6"),
    TEXTURES_BLOCK_DISPENSER_FRONT_VERTICAL("textures\\block", "dispenser_front_vertical", "1.6"),
    TEXTURES_BLOCK_DRAGON_EGG("textures\\block", "dragon_egg", "1.6"),
    TEXTURES_BLOCK_DRIED_KELP_BOTTOM("textures\\block", "dried_kelp_bottom", "1.14"),
    TEXTURES_BLOCK_DRIED_KELP_SIDE("textures\\block", "dried_kelp_side", "1.14"),
    TEXTURES_BLOCK_DRIED_KELP_TOP("textures\\block", "dried_kelp_bottom", "1.14"),
    TEXTURES_BLOCK_DRIPSTONE_BLOCK("textures\\block", "dripstone_block", "1.17"),
    TEXTURES_BLOCK_DROPPER_FRONT("textures\\block", "dropper_front", "dropped_front_horizontal", "1.6"),
    TEXTURES_BLOCK_DROPPER_FRONT_VERTICAL("textures\\block", "dropper_front_vertical", "1.6"),
    TEXTURES_BLOCK_EMERALD_BLOCK("textures\\block", "emerald_block", "1.6"),
    TEXTURES_BLOCK_EMERALD_ORE("textures\\block", "emerald_ore", "1.6"),
    TEXTURES_BLOCK_ENCHANTING_TABLE_BOTTOM("textures\\block", "enchanting_table_bottom", "1.6"),
    TEXTURES_BLOCK_ENCHANTING_TABLE_SIDE("textures\\block", "enchanting_table_side", "1.6"),
    TEXTURES_BLOCK_ENCHANTING_TABLE_TOP("textures\\block", "enchanting_table_top", "1.6"),
    TEXTURES_BLOCK_END_PORTAL_FRAME_EYE("textures\\block", "end_portal_frame_eye", "endframe_eye", "1.6"),
    TEXTURES_BLOCK_END_PORTAL_FRAME_SIDE("textures\\block", "end_portal_frame_side", "endframe_side", "1.6"),
    TEXTURES_BLOCK_END_PORTAL_FRAME_TOP("textures\\block", "end_portal_frame_top", "endframe_top", "1.6"),
    TEXTURES_BLOCK_END_ROD("textures\\block", "end_rod", "1.9"),
    TEXTURES_BLOCK_END_STONE("textures\\block", "end_stone", "1.6"),
    TEXTURES_BLOCK_END_STONE_BRICKS("textures\\block", "end_stone_bricks", "end_bricks", "1.9"),
    TEXTURES_BLOCK_EXPOSED_COPPER("textures\\block", "exposed_copper", "1.17"),
    TEXTURES_BLOCK_EXPOSED_CUT_COPPER("textures\\block", "exposed_cut_copper", "1.17"),
    TEXTURES_BLOCK_FARMLAND("textures\\block", "farmland", "farmland_dry", "1.6"),
    TEXTURES_BLOCK_FARMLAND_MOIST("textures\\block", "farmland_moist", "farmland_wet", "1.6"),
    TEXTURES_BLOCK_FERN("textures\\block", "fern", "1.6"),
    TEXTURES_BLOCK_FIRE_0("textures\\block", "fire_0", "fire_layer_0", "1.6"),
    TEXTURES_BLOCK_FIRE_1("textures\\block", "fire_1", "fire_layer_1", "1.6"),
    TEXTURES_BLOCK_FIRE_CORAL("textures\\block", "fire_coral", "1.13"),
    TEXTURES_BLOCK_FIRE_CORAL_BLOCK("textures\\block", "fire_coral_block", "1.13"),
    TEXTURES_BLOCK_FIRE_CORAL_FAN("textures\\block", "fire_coral_fan", "1.13"),
    TEXTURES_BLOCK_FLETCHING_TABLE_FRONT("textures\\block", "fletching_table_front", "1.14"),
    TEXTURES_BLOCK_FLETCHING_TABLE_SIDE("textures\\block", "fletching_table_side", "1.14"),
    TEXTURES_BLOCK_FLETCHING_TABLE_TOP("textures\\block", "fletching_table_top", "1.14"),
    TEXTURES_BLOCK_FLOWER_POT("textures\\block", "flower_pot", "1.6"),
    TEXTURES_BLOCK_FLOWERING_AZALEA_LEAVES("textures\\block", "flowering_azalea_leaves", "1.17"),
    TEXTURES_BLOCK_FLOWERING_AZALEA_SIDE("textures\\block", "flowering_azalea_side", "1.17"),
    TEXTURES_BLOCK_FLOWERING_AZALEA_TOP("textures\\block", "flowering_azalea_top", "1.17"),
    TEXTURES_BLOCK_FROGSPAWN("textures\\block", "frogspawn", "1.19"),
    TEXTURES_BLOCK_FROSTED_ICE_0("textures\\block", "frosted_ice_0", "1.9"),
    TEXTURES_BLOCK_FROSTED_ICE_1("textures\\block", "frosted_ice_1", "1.9"),
    TEXTURES_BLOCK_FROSTED_ICE_2("textures\\block", "frosted_ice_2", "1.9"),
    TEXTURES_BLOCK_FROSTED_ICE_3("textures\\block", "frosted_ice_3", "1.9"),
    TEXTURES_BLOCK_FURNACE_FRONT("textures\\block", "furnace_front", "furnace_front_off", "1.6"),
    TEXTURES_BLOCK_FURNACE_FRONT_ON("textures\\block", "furnace_front_on", "1.6"),
    TEXTURES_BLOCK_FURNACE_SIDE("textures\\block", "furnace_side", "1.6"),
    TEXTURES_BLOCK_FURNACE_TOP("textures\\block", "furnace_top", "1.6"),
    TEXTURES_BLOCK_GILDED_BLACKSTONE("textures\\block", "gilded_blackstone", "1.16"),
    TEXTURES_BLOCK_GLASS("textures\\block", "glass", "1.6"),
    TEXTURES_BLOCK_GLASS_PANE_TOP("textures\\block", "glass_pane_top", "1.6"),
    TEXTURES_BLOCK_GLOW_ITEM_FRAME("textures\\block", "glow_item_frame", "1.17"),
    TEXTURES_BLOCK_GLOW_LICHEN("textures\\block", "glow_lichen", "1.17"),
    TEXTURES_BLOCK_GLOWSTONE("textures\\block", "glowstone", "1.6"),
    TEXTURES_BLOCK_GOLD_BLOCK("textures\\block", "gold_block", "1.6"),
    TEXTURES_BLOCK_GOLD_ORE("textures\\block", "gold_ore", "1.6"),
    TEXTURES_BLOCK_GRANITE("textures\\block", "granite", "stone_granite", "1.8"),
    TEXTURES_BLOCK_GRASS("textures\\block", "grass", "tallgrass", "1.6"),
    TEXTURES_BLOCK_GRASS_BLOCK_SIDE("textures\\block", "grass_block_side", "grass_side", "1.6"),
    TEXTURES_BLOCK_GRASS_BLOCK_SIDE_OVERLAY("textures\\block", "grass_block_side_overlay", "grass_side_overlay", "1.6"),
    TEXTURES_BLOCK_GRASS_BLOCK_SNOW("textures\\block", "grass_block_snow", "grass_side_snowed", "1.6"),
    TEXTURES_BLOCK_GRASS_BLOCK_TOP("textures\\block", "grass_block_top", "grass_top", "1.6"),
    TEXTURES_BLOCK_GRAVEL("textures\\block", "gravel", "1.6"),
    TEXTURES_BLOCK_GRAY_CANDLE("textures\\block", "gray_candle", "1.17"),
    TEXTURES_BLOCK_GRAY_CANDLE_LIT("textures\\block", "gray_candle_lit", "1.17"),
    TEXTURES_BLOCK_GRAY_CONCRETE("textures\\block", "gray_concrete", "concrete_gray", "1.12"),
    TEXTURES_BLOCK_GRAY_CONCRETE_POWDER("textures\\block", "gray_concrete_powder", "concrete_powder_gray", "1.12"),
    TEXTURES_BLOCK_GRAY_GLAZED_TERRACOTTA("textures\\block", "gray_glazed_terracotta", "glazed_terracotta_gray", "1.12"),
    TEXTURES_BLOCK_GRAY_SHULKER_BOX("textures\\block", "gray_shulker_box", "shulker_top_gray", "1.11"),
    TEXTURES_BLOCK_GRAY_STAINED_GLASS("textures\\block", "gray_stained_glass", "glass_gray", "1.7"),
    TEXTURES_BLOCK_GRAY_STAINED_GLASS_PANE_TOP("textures\\block", "gray_stained_glass_pane_top", "glass_pane_top_gray", "1.7"),
    TEXTURES_BLOCK_GRAY_TERRACOTTA("textures\\block", "gray_terracotta", "hardened_clay_stained_gray", "1.6"),
    TEXTURES_BLOCK_GRAY_WOOL("textures\\block", "gray_wool", "wool_colored_gray", "1.6"),
    TEXTURES_BLOCK_GREEN_CANDLE("textures\\block", "green_candle", "1.17"),
    TEXTURES_BLOCK_GREEN_CANDLE_LIT("textures\\block", "green_candle_lit", "1.17"),
    TEXTURES_BLOCK_GREEN_CONCRETE("textures\\block", "green_concrete", "concrete_green", "1.12"),
    TEXTURES_BLOCK_GREEN_CONCRETE_POWDER("textures\\block", "green_concrete_powder", "concrete_powder_green", "1.12"),
    TEXTURES_BLOCK_GREEN_GLAZED_TERRACOTTA("textures\\block", "green_glazed_terracotta", "glazed_terracotta_green", "1.12"),
    TEXTURES_BLOCK_GREEN_SHULKER_BOX("textures\\block", "green_shulker_box", "shulker_top_green", "1.11"),
    TEXTURES_BLOCK_GREEN_STAINED_GLASS("textures\\block", "green_stained_glass", "glass_green", "1.7"),
    TEXTURES_BLOCK_GREEN_STAINED_GLASS_PANE_TOP("textures\\block", "green_stained_glass_pane_top", "glass_pane_top_green", "1.7"),
    TEXTURES_BLOCK_GREEN_TERRACOTTA("textures\\block", "green_terracotta", "hardened_clay_stained_green", "1.6"),
    TEXTURES_BLOCK_GREEN_WOOL("textures\\block", "green_wool", "wool_colored_green", "1.6"),
    TEXTURES_BLOCK_GRINDSTONE_PIVOT("textures\\block", "grindstone_pivot", "1.14"),
    TEXTURES_BLOCK_GRINDSTONE_ROUND("textures\\block", "grindstone_round", "1.14"),
    TEXTURES_BLOCK_GRINDSTONE_SIDE("textures\\block", "grindstone_side", "1.14"),
    TEXTURES_BLOCK_HANGING_ROOTS("textures\\block", "hanging_roots", "1.17"),
    TEXTURES_BLOCK_HAY_BLOCK_TOP("textures\\block", "hay_block_top", "1.6"),
    TEXTURES_BLOCK_HAY_BLOCK_SIDE("textures\\block", "hay_block_side", "1.6"),
    TEXTURES_BLOCK_HONEY_BLOCK_BOTTOM("textures\\block", "honey_block_bottom", "1.15"),
    TEXTURES_BLOCK_HONEY_BLOCK_SIDE("textures\\block", "honey_block_side", "1.15"),
    TEXTURES_BLOCK_HONEY_BLOCK_TOP("textures\\block", "honey_block_top", "1.15"),
    TEXTURES_BLOCK_HONEYCOMB("textures\\block", "honeycomb", "1.15"),
    TEXTURES_BLOCK_HOPPER_INSIDE("textures\\block", "hopper_inside", "1.6"),
    TEXTURES_BLOCK_HOPPER_OUTSIDE("textures\\block", "hopper_outide", "1.6"),
    TEXTURES_BLOCK_HOPPER_TOP("textures\\block", "hopper_top", "1.6"),
    TEXTURES_BLOCK_HORN_CORAL("textures\\block", "horn_coral", "1.13"),
    TEXTURES_BLOCK_HORN_CORAL_BLOCK("textures\\block", "horn_coral_block", "1.13"),
    TEXTURES_BLOCK_HORN_CORAL_FAN("textures\\block", "horn_coral_fan", "1.13"),
    TEXTURES_BLOCK_ICE("textures\\block", "ice", "1.6"),
    TEXTURES_BLOCK_IRON_BARS("textures\\block", "iron_bars", "1.6"),
    TEXTURES_BLOCK_IRON_BLOCK("textures\\block", "iron_block", "1.6"),
    TEXTURES_BLOCK_IRON_DOOR_BOTTOM("textures\\block", "iron_door_bottom", "door_iron_lower", "1.6"),
    TEXTURES_BLOCK_IRON_DOOR_TOP("textures\\block", "iron_door_top", "door_iron_upper", "1.6"),
    TEXTURES_BLOCK_IRON_ORE("textures\\block", "iron_ore", "1.6"),
    TEXTURES_BLOCK_IRON_TRAPDOOR("textures\\block", "iron_trapdoor", "1.8"),
    TEXTURES_BLOCK_ITEM_FRAME("texures\\block", "item_frame", "itemframe_background", "1.6"),
    TEXTURES_BLOCK_JACK_O_LANTERN("textures\\block", "jack_o_lantern", "pumpkin_face_on", "1.6"),
    TEXTURES_BLOCK_JIGSAW_BOTTOM("textures\\block", "jigsaw_bottom", "1.14"),
    TEXTURES_BLOCK_JIGSAWM_LOCK("textures\\block", "jigsaw_lock", "1.14"),
    TEXTURES_BLOCK_JIGSAW_SIDE("textures\\block", "jigsaw_side", "1.14"),
    TEXTURES_BLOCK_JIGSAW_TOP("textures\\block", "jigsaw_top", "1.14"),
    TEXTURES_BLOCK_JUKEBOX_SIDE("textures\\block", "jukebox_side", "1.6"),
    TEXTURES_BLOCK_JUKEBOX_TOP("textures\\block", "jukebox_top", "1.6"),
    TEXTURES_BLOCK_JUNGLE_DOOR_BOTTOM("textures\\block", "jungle_door_bottom", "door_jungle_lower", "1.8"),
    TEXTURES_BLOCK_JUNGLE_DOOR_TOP("textures\\block", "jungle_door_top", "door_jungle_upper", "1.8"),
    TEXTURES_BLOCK_JUNGLE_LEAVES("textures\\block", "jungle_leaves", "leaves_jungle", "1.6"),
    TEXTURES_BLOCK_JUNGLE_LOG("textures\\block", "jungle_log", "log_jungle", "1.6"),
    TEXTURES_BLOCK_JUNGLE_LOG_TOP("textures\\block", "jungle_log_top", "log_jungle_top", "1.6"),
    TEXTURES_BLOCK_JUNGLE_PLANKS("textures\\block", "jungle_planks", "planks_jungle", "1.6"),
    TEXTURES_BLOCK_JUNGLE_SAPLING("textures\\block", "jungle_sapling", "sapling_jungle", "1.6"),
    TEXTURES_BLOCK_JUNGLE_TRAPDOOR("textures\\block", "jungle_trapdoor", "1.13"),
    TEXTURES_BLOCK_KELP("textures\\block", "kelp", "1.14"),
    TEXTURES_BLOCK_KELP_PLANT("textures\\block", "kelp_plant", "1.14"),
    TEXTURES_BLOCK_LADDER("textures\\block", "ladder", "1.6"),
    TEXTURES_BLOCK_LANTERN("textures\\block", "lantern", "1.14"),
    TEXTURES_BLOCK_LAPIS_BLOCK("textures\\block", "lapis_block", "1.6"),
    TEXTURES_BLOCK_LAPIS_ORE("textures\\block", "lapis_ore", "1.6"),
    TEXTURES_BLOCK_LARGE_AMETHYST_BUD("textures\\block", "large_amethyst_bud", "1.17"),
    TEXTURES_BLOCK_LARGE_FERN_BOTTOM("textures\\block", "large_fern_bottom", "double_plant_fern_bottom", "1.7"),
    TEXTURES_BLOCK_LARGE_FERN_TOP("textures\\block", "large_fern_top", "double_plant_fern_top", "1.7"),
    TEXTURES_BLOCK_LAVA_FLOW("textures\\block", "lava_flow", "1.6"),
    TEXTURES_BLOCK_LAVA_STILL("textures\\block", "lava_still", "1.6"),
    TEXTURES_BLOCK_LECTERN_BASE("textures\\block", "lectern_base", "1.14"),
    TEXTURES_BLOCK_LECTERN_FRONT("textures\\block", "lectern_front", "1.14"),
    TEXTURES_BLOCK_LECTERN_SIDES("textures\\block", "lectern_sides", "1.14"),
    TEXTURES_BLOCK_LECTERN_TOP("textures\\block", "lectern_top", "1.14"),
    TEXTURES_BLOCK_LEVER("textures\\block", "lever", "1.6"),
    TEXTURES_BLOCK_LIGHT_BLUE_CANDLE("textures\\block", "light_blue_candle", "1.17"),
    TEXTURES_BLOCK_LIGHT_BLUE_CANDLE_LIT("textures\\block", "light_blue_candle_lit", "1.17"),
    TEXTURES_BLOCK_LIGHT_BLUE_CONCRETE("textures\\block", "light_blue_concrete", "concrete_light_blue", "1.12"),
    TEXTURES_BLOCK_LIGHT_BLUE_CONCRETE_POWDER("textures\\block", "light_blue_concrete_powder", "concrete_powder_light_blue", "1.12"),
    TEXTURES_BLOCK_LIGHT_BLUE_GLAZED_TERRACOTTA("textures\\block", "light_blue_glazed_terracotta", "glazed_terracotta_light_blue", "1.12"),
    TEXTURES_BLOCK_LIGHT_BLUE_SHULKER_BOX("textures\\block", "light_blue_shulker_box", "shulker_top_light_blue", "1.11"),
    TEXTURES_BLOCK_LIGHT_BLUE_STAINED_GLASS("textures\\block", "light_blue_stained_glass", "glass_light_blue", "1.7"),
    TEXTURES_BLOCK_LIGHT_BLUE_STAINED_GLASS_PANE_TOP("textures\\block", "light_blue_stained_glass_pane_top", "glass_pane_top_light_blue", "1.7"),
    TEXTURES_BLOCK_LIGHT_BLUE_TERRACOTTA("textures\\block", "light_blue_terracotta", "hardened_clay_stained_light_blue", "1.6"),
    TEXTURES_BLOCK_LIGHT_BLUE_WOOL("textures\\block", "light_blue_wool", "wool_colored_light_blue", "1.6"),
    TEXTURES_BLOCK_LIGHT_GRAY_CANDLE("textures\\block", "light_gray_candle", "1.17"),
    TEXTURES_BLOCK_LIGHT_GRAY_CANDLE_LIT("textures\\block", "light_gray_candle_lit", "1.17"),
    TEXTURES_BLOCK_LIGHT_GRAY_CONCRETE("textures\\block", "light_gray_concrete", "concrete_silver", "1.12"),
    TEXTURES_BLOCK_LIGHT_GRAY_CONCRETE_POWDER("textures\\block", "light_gray_concrete_powder", "concrete_powder_silver", "1.12"),
    TEXTURES_BLOCK_LIGHT_GRAY_GLAZED_TERRACOTTA("textures\\block", "light_gray_glazed_terracotta", "glazed_terracotta_silver", "1.12"),
    TEXTURES_BLOCK_LIGHT_GRAY_SHULKER_BOX("textures\\block", "light_gray_shulker_box", "shulker_top_silver", "1.11"),
    TEXTURES_BLOCK_LIGHT_GRAY_STAINED_GLASS("textures\\block", "light_gray_stained_glass", "glass_silver", "1.7"),
    TEXTURES_BLOCK_LIGHT_GRAY_STAINED_GLASS_PANE_TOP("textures\\block", "light_gray_stained_glass_pane_top", "glass_pane_top_silver", "1.7"),
    TEXTURES_BLOCK_LIGHT_GRAY_TERRACOTTA("textures\\block", "light_gray_terracotta", "hardened_clay_stained_silver", "1.6"),
    TEXTURES_BLOCK_LIGHT_GRAY_WOOL("textures\\block", "light_gray_wool", "wool_colored_silver", "1.6"),
    TEXTURES_BLOCK_LIGHTNING_ROD("textures\\block", "lightning_rod", "1.17"),
    TEXTURES_BLOCK_LIGHTNING_ROD_ON("textures\\block", "lightning_rod_on", "1.17"),
    TEXTURES_BLOCK_LILAC_BOTTOM("textures\\block", "lilac_bottom", "double_plant_syringa_bottom", "1.7"),
    TEXTURES_BLOCK_LILAC_TOP("textures\\block", "lilac_top", "double_plant_syringa_top", "1.7"),
    TEXTURES_BLOCK_LILY_OF_THE_VALLEY("textures\\block", "lily_of_the_valley", "1.14"),
    TEXTURES_BLOCK_LILY_PAD("textures\\block", "lily_pad", "waterlily", "1.6"),
    TEXTURES_BLOCK_LIME_CANDLE("textures\\block", "lime_candle", "1.17"),
    TEXTURES_BLOCK_LIME_CANDLE_LIT("textures\\block", "lime_candle_lit", "1.17"),
    TEXTURES_BLOCK_LIME_CONCRETE("textures\\block", "lime_concrete", "concrete_lime", "1.12"),
    TEXTURES_BLOCK_LIME_CONCRETE_POWDER("textures\\block", "lime_concrete_powder", "concrete_powder_lime", "1.12"),
    TEXTURES_BLOCK_LIME_GLAZED_TERRACOTTA("textures\\block", "lime_glazed_terracotta", "glazed_terracotta_lime", "1.12"),
    TEXTURES_BLOCK_LIME_SHULKER_BOX("textures\\block", "lime_shulker_box", "shulker_top_lime", "1.11"),
    TEXTURES_BLOCK_LIME_STAINED_GLASS("textures\\block", "lime_stained_glass", "glass_lime", "1.7"),
    TEXTURES_BLOCK_LIME_STAINED_GLASS_PANE_TOP("textures\\block", "lime_stained_glass_pane_top", "glass_pane_top_lime", "1.7"),
    TEXTURES_BLOCK_LIME_TERRACOTTA("textures\\block", "lime_terracotta", "hardened_clay_stained_lime", "1.6"),
    TEXTURES_BLOCK_LIME_WOOL("textures\\block", "lime_wool", "wool_colored_lime", "1.6"),
    TEXTURES_BLOCK_LODESTONE_SIDE("textures\\block", "lodestone_side", "1.16"),
    TEXTURES_BLOCK_LODESTONE_TOP("textures\\block", "lodestone_top", "1.16"),
    TEXTURES_BLOCK_LOOM_FRONT("textures\\block", "loom_front", "1.14"),
    TEXTURES_BLOCK_LOOM_SIDE("textures\\block", "loom_side", "1.14"),
    TEXTURES_BLOCK_LOOM_TOP("textures\\block", "loom_top", "1.14"),
    TEXTURES_BLOCK_MAGENTA_CANDLE("textures\\block", "magenta_candle", "1.17"),
    TEXTURES_BLOCK_MAGENTA_CANDLE_LIT("textures\\block", "magenta_candle_lit", "1.17"),
    TEXTURES_BLOCK_MAGENTA_CONCRETE("textures\\block", "magenta_concrete", "concrete_magenta", "1.12"),
    TEXTURES_BLOCK_MAGENTA_CONCRETE_POWDER("textures\\block", "magenta_concrete_powder", "concrete_powder_magenta", "1.12"),
    TEXTURES_BLOCK_MAGENTA_GLAZED_TERRACOTTA("textures\\block", "magenta_glazed_terracotta", "glazed_terracotta_magenta", "1.12"),
    TEXTURES_BLOCK_MAGENTA_SHULKER_BOX("textures\\block", "magenta_shulker_box", "shulker_top_magenta", "1.11"),
    TEXTURES_BLOCK_MAGENTA_STAINED_GLASS("textures\\block", "magenta_stained_glass", "glass_magenta", "1.7"),
    TEXTURES_BLOCK_MAGENTA_STAINED_GLASS_PANE_TOP("textures\\block", "magenta_stained_glass_pane_top", "glass_pane_top_magenta", "1.7"),
    TEXTURES_BLOCK_MAGENTA_TERRACOTTA("textures\\block", "magenta_terracotta", "hardened_clay_stained_magenta", "1.6"),
    TEXTURES_BLOCK_MAGENTA_WOOL("textures\\block", "magenta_wool", "wool_colored_magenta", "1.6"),
    TEXTURES_BLOCK_MAGMA("textures\\block", "magma", "1.10"),
    TEXTURES_BLOCK_MANGROVE_DOOR_BOTTOM("textures\\block", "mangrove_door_bottom", "1.19"),
    TEXTURES_BLOCK_MANGROVE_DOOR_TOP("textures\\block", "mangrove_door_top", "1.19"),
    TEXTURES_BLOCK_MANGROVE_LEAVES("textures\\block", "mangrove_leaves", "1.19"),
    TEXTURES_BLOCK_MANGROVE_LOG("textures\\block", "mangrove_log", "1.19"),
    TEXTURES_BLOCK_MANGROVE_LOG_TOP("textures\\block", "mangrove_log_top", "1.19"),
    TEXTURES_BLOCK_MANGROVE_PLANKS("textures\\block", "mangrove_planks", "1.19"),
    TEXTURES_BLOCK_MANGROVE_PROPAGULE("textures\\block", "mangrove_propagule", "1.19"),
    TEXTURES_BLOCK_MANGROVE_PROPAGULE_HANGING("textures\\block", "mangrove_propagule_hanging", "1.19"),
    TEXTURES_BLOCK_MANGROVE_ROOTS_SIDE("textures\\block", "mangrove_roots_side", "1.19"),
    TEXTURES_BLOCK_MANGROVE_ROOTS_TOP("textures\\block", "mangrove_roots_top", "1.19"),
    TEXTURES_BLOCK_MANGROVE_TRAPDOOR("textures\\block", "mangrove_trapdoor", "1.19"),
    TEXTURES_BLOCK_MEDIUM_AMETHYST_BUD("textures\\block", "medium_amethyst_bud", "1.17"),
    TEXTURES_BLOCK_MELON_SIDE("textures\\block", "melon_side", "1.6"),
    TEXTURES_BLOCK_MELON_STEM("textures\\block", "melon_stem", "melon_stem_disconnected", "1.6"),
    TEXTURES_BLOCK_MELON_TOP("textures\\block", "melon_top", "1.6"),
    TEXTURES_BLOCK_MOSS_BLOCK("textures\\block", "moss_block", "1.17"),
    TEXTURES_BLOCK_MOSSY_COBBLESTONE("textures\\block", "mossy_cobblestone", "cobblestone_mossy", "1.6"),
    TEXTURES_BLOCK_MOSSY_STONE_BRICKS("textures\\block", "mossy_stone_bricks", "stonebrick_mossy", "1.6"),
    TEXTURES_BLOCK_MUD("textures\\block", "mud", "1.19"),
    TEXTURES_BLOCK_MUD_BRICKS("textures\\block", "mud_bricks", "1.19"),
    TEXTURES_BLOCK_MUDDY_MANGROVE_ROOTS_SIDE("textures\\block", "muddy_mangrove_roots_side", "1.19"),
    TEXTURES_BLOCK_MUDDY_MANGROVE_ROOTS_TOP("textures\\block", "muddy_mangrove_roots_top", "1.19"),
    TEXTURES_BLOCK_MUSHROOM_BLOCK_INSIDE("textures\\block", "mushroom_block_inside", "1.6"),
    TEXTURES_BLOCK_MUSHROOM_STEM("textures\\block", "mushroom_stem", "mushroom_block_skin_stem", "1.6"),
    TEXTURES_BLOCK_MYCELIUM_SIDE("textures\\block", "mycelium_side", "1.6"),
    TEXTURES_BLOCK_MYCELIUM_TOP("textures\\block", "mycelium_top", "1.6"),
    TEXTURES_BLOCK_NETHER_BRICKS("textures\\block", "nether_bricks", "nether_brick", "1.6"),
    TEXTURES_BLOCK_NETHER_GOLD_ORE("textures\\block", "nether_gold_ore", "1.16"),
    TEXTURES_BLOCK_NETHER_PORTAL("textures\\block", "nether_portal", "portal", "1.6"),
    TEXTURES_BLOCK_NETHER_QUARTZ_ORE("textures\\block", "nether_quartz_ore", "quartz_ore", "1.6"),
    TEXTURES_BLOCK_NETHER_SPROUTS("textures\\block", "nether_sprouts", "1.16"),
    TEXTURES_BLOCK_NETHER_WART_BLOCK("textures\\block", "nether_wart_block", "1.10"),
    TEXTURES_BLOCK_NETHER_WART_STAGE0("textures\\block", "nether_wart_stage0", "nether_wart_stage_0", "1.6"),
    TEXTURES_BLOCK_NETHER_WART_STAGE1("textures\\block", "nether_wart_stage1", "nether_wart_stage_1", "1.6"),
    TEXTURES_BLOCK_NETHER_WART_STAGE2("textures\\block", "nether_wart_stage2", "nether_wart_stage_2", "1.6"),
    TEXTURES_BLOCK_NETHERITE_BLOCK("textures\\block", "netherite_block", "1.16"),
    TEXTURES_BLOCK_NETHERRACK("textures\\block", "netherrack", "1.6"),
    TEXTURES_BLOCK_NOTE_BLOCK("textures\\block", "note_block", "noteblock", "1.6"),
    TEXTURES_BLOCK_OAK_DOOR_BOTTOM("textures\\block", "oak_door_bottom", "door_wood_lower", "1.6"),
    TEXTURES_BLOCK_OAK_DOOR_TOP("textures\\block", "oak_door_top", "door_wood_upper", "1.6"),
    TEXTURES_BLOCK_OAK_LEAVES("textures\\block", "oak_leaves", "leaves_oak", "1.6"),
    TEXTURES_BLOCK_OAK_LOG("textures\\block", "oak_log", "log_oak", "1.6"),
    TEXTURES_BLOCK_OAK_LOG_TOP("textures\\block", "oak_log_top", "log_oak_top", "1.6"),
    TEXTURES_BLOCK_OAK_PLANKS("textures\\block", "oak_planks", "planks_oak", "1.6"),
    TEXTURES_BLOCK_OAK_SAPLING("textures\\block", "oak_sapling", "sapling_oak", "1.6"),
    TEXTURES_BLOCK_OAK_TRAPDOOR("textures\\block", "oak_trapdoor", "trapdoor", "1.6"),
    TEXTURES_BLOCK_OBSERVER_BACK("textures\\block", "observer_back", "1.11"),
    TEXTURES_BLOCK_OBSERVER_BACK_ON("textures\\block", "observer_back_on", "observer_back_lit", "1.11"),
    TEXTURES_BLOCK_OBSERVER_FRONT("textures\\block", "observer_front", "1.11"),
    TEXTURES_BLOCK_OBSERVER_SIDE("textures\\block", "observer_side", "1.11"),
    TEXTURES_BLOCK_OBSERVER_TOP("textures\\block", "observer_top", "1.11"),
    TEXTURES_BLOCK_OBSIDIAN("textures\\block", "obsidian", "1.6"),
    TEXTURES_BLOCK_OCHRE_FROGLIGHT_SIDE("textures\\block", "ochre_froglight_side", "1.19"),
    TEXTURES_BLOCK_OCHRE_FROGLIGHT_TOP("textures\\block", "ochre_froglight_top", "1.19"),
    TEXTURES_BLOCK_ORANGE_CANDLE("textures\\block", "orange_candle", "1.17"),
    TEXTURES_BLOCK_ORANGE_CANDLE_LIT("textures\\block", "orange_candle_lit", "1.17"),
    TEXTURES_BLOCK_ORANGE_CONCRETE("textures\\block", "orange_concrete", "concrete_orange", "1.12"),
    TEXTURES_BLOCK_ORANGE_CONCRETE_POWDER("textures\\block", "orange_concrete_powder", "concrete_powder_orange", "1.12"),
    TEXTURES_BLOCK_ORANGE_GLAZED_TERRACOTTA("textures\\block", "orange_glazed_terracotta", "glazed_terracotta_orange", "1.12"),
    TEXTURES_BLOCK_ORANGE_SHULKER_BOX("textures\\block", "orange_shulker_box", "shulker_top_orange", "1.11"),
    TEXTURES_BLOCK_ORANGE_STAINED_GLASS("textures\\block", "orange_stained_glass", "glass_orange", "1.7"),
    TEXTURES_BLOCK_ORANGE_STAINED_GLASS_PANE_TOP("textures\\block", "orange_stained_glass_pane_top", "glass_pane_top_orange", "1.7"),
    TEXTURES_BLOCK_ORANGE_TERRACOTTA("textures\\block", "orage_terracotta", "hardened_clay_stained_orange", "1.6"),
    TEXTURES_BLOCK_ORANGE_TULIP("textures\\block", "orange_tulip", "flower_tulip_orange", "1.7"),
    TEXTURES_BLOCK_ORANGE_WOOL("textures\\block", "orange_wool", "wool_colored_orange", "1.6"),
    TEXTURES_BLOCK_OXEYE_DAISY("textures\\block", "oxeye_daisy", "flower_oxeye_daisy", "1.7"),
    TEXTURES_BLOCK_OXIDIZED_COPPER("textures\\block", "oxidized_copper", "1.17"),
    TEXTURES_BLOCK_OXIDIZED_CUT_COPPER("textures\\block", "oxidized_cut_copper", "1.17"),
    TEXTURES_BLOCK_PACKED_ICE("textures\\block", "packed_ice", "ice_packed", "1.7"),
    TEXTURES_BLOCK_PACKED_MUD("textures\\block", "packed_mud", "1.19"),
    TEXTURES_BLOCK_PEARLESCENT_FROGLIGHT_SIDE("textures\\block", "pearlescent_froglight_side", "1.19"),
    TEXTURES_BLOCK_PEARLESCENT_FROGLIGHT_TOP("textures\\block", "pearlescent_froglight_top", "1.19"),
    TEXTURES_BLOCK_PEONY_BOTTOM("textures\\block", "peony_bottom", "double_plant_paeonia_bottom", "1.7"),
    TEXTURES_BLOCK_PEONY_TOP("textures\\block", "peony_top", "double_plant_paeonia_top"),
    TEXTURES_BLOCK_PINK_CANDLE("textures\\block", "pink_candle", "1.17"),
    TEXTURES_BLOCK_PINK_CANDLE_LIT("textures\\block", "pink_candle_lit", "1.17"),
    TEXTURES_BLOCK_PINK_CONCRETE("textures\\block", "pink_concrete", "concrete_pink", "1.12"),
    TEXTURES_BLOCK_PINK_CONCRETE_POWDER("textures\\block", "pink_concrete_powder", "concrete_powder_pink", "1.12"),
    TEXTURES_BLOCK_PINK_GLAZED_TERRACOTTA("textures\\block", "pink_glazed_terracotta", "glazed_terracotta_pink", "1.12"),
    TEXTURES_BLOCK_PINK_SHULKER_BOX("textures\\block", "pink_shulker_box", "shulker_top_pink", "1.11"),
    TEXTURES_BLOCK_PINK_STAINED_GLASS("textures\\block", "pink_stained_glass", "glass_pink", "1.7"),
    TEXTURES_BLOCK_PINK_STAINED_GLASS_PANE_TOP("textures\\block", "pink_stained_glass_pane_top", "glass_pane_top_pink", "1.7"),
    TEXTURES_BLOCK_PINK_TERRACOTTA("textures\\block", "pink_terracotta", "hardened_clay_stained_pink", "1.6"),
    TEXTURES_BLOCK_PINK_TULIP("textures\\block", "pink_tulip", "flower_tulip_pink", "1.7"),
    TEXTURES_BLOCK_PINK_WOOL("textures\\block", "pink_wool", "wool_colored_pink", "1.6"),
    TEXTURES_BLOCK_PISTON_BOTTOM("textures\\block", "piston_bottom", "1.6"),
    TEXTURES_BLOCK_PISTON_INNER("textures\\block", "piston_inner", "1.6"),
    TEXTURES_BLOCK_PISTON_SIDE("textures\\block", "piston_side", "1.6"),
    TEXTURES_BLOCK_PISTON_TOP("textures\\block", "piston_top", "piston_top_normal", "1.6"),
    TEXTURES_BLOCK_PISTON_TOP_STICKY("textures\\block", "piston_top_sticky", "1.6"),
    TEXTURES_BLOCK_PODZOL_SIDE("textures\\block", "podzol_side", "dirt_podzol_side", "1.7"),
    TEXTURES_BLOCK_PODZOL_TOP("textures\\block", "podzol_top", "dirt_podzol_top", "1.7"),
    TEXTURES_BLOCK_POINTED_DRIPSTONE_DOWN_BASE("textures\\block", "pointed_dripstone_down_base", "1.17"),
    TEXTURES_BLOCK_POINTED_DRIPSTONE_DOWN_FRUSTUM("textures\\block", "pointed_dripstone_down_frustum", "1.17"),
    TEXTURES_BLOCK_POINTED_DRIPSTONE_DOWN_MIDDLE("textures\\block", "pointed_dripstone_down_middle", "1.17"),
    TEXTURES_BLOCK_POINTED_DRIPSTONE_DOWN_TIP("textures\\block", "pointed_dripstone_down_tip", "1.17"),
    TEXTURES_BLOCK_POINTED_DRIPSTONE_DOWN_TIP_MERGE("textures\\block", "pointed_dripstone_down_tip_merge", "1.17"),
    TEXTURES_BLOCK_POINTED_DRIPSTONE_UP_BASE("textures\\block", "pointed_dripstone_up_base", "1.17"),
    TEXTURES_BLOCK_POINTED_DRIPSTONE_UP_FRUSTUM("textures\\block", "pointed_dripstone_up_frustum", "1.17"),
    TEXTURES_BLOCK_POINTED_DRIPSTONE_UP_MIDDLE("textures\\block", "pointed_dripstone_up_middle", "1.17"),
    TEXTURES_BLOCK_POINTED_DRIPSTONE_UP_TIP("textures\\block", "pointed_dripstone_up_tip", "1.17"),
    TEXTURES_BLOCK_POINTED_DRIPSTONE_UP_TIP_MERGE("textures\\block", "pointed_dripstone_up_tip_merge", "1.17"),
    TEXTURES_BLOCK_POLISHED_ANDESITE("textures\\block", "polished_andesite", "stone_andesite_smooth", "1.8"),
    TEXTURES_BLOCK_POLISHED_BASALT_SIDE("textures\\block", "polished_basalt_side", "1.16"),
    TEXTURES_BLOCK_POLISHED_BASALT_TOP("textures\\block", "polished_basalt_top", "1.16"),
    TEXTURES_BLOCK_POLISHED_BLACKSTONE("textures\\block", "polished_blackstone", "1.16"),
    TEXTURES_BLOCK_POLISHED_BLACKSTONE_BRICKS("textures\\block", "polished_blackstone_bricks", "1.16"),
    TEXTURES_BLOCK_POLISHED_DEEPSLATE("textures\\block", "polished_deepslate", "1.17"),
    TEXTURES_BLOCK_POLISHED_DIORITE("textures\\block", "polished_diorite", "stone_diorite_smooth", "1.8"),
    TEXTURES_BLOCK_POLISHED_GRANITE("textures\\block", "polished_granite", "stone_granite_polished", "1.8"),
    TEXTURES_BLOCK_POPPY("textures\\block", "poppy", "flower_rose", "1.6"),
    TEXTURES_BLOCK_POTATOES_STAGE0("textures\\block", "potatoes_stage0", "potatoes_stage_0", "1.6"),
    TEXTURES_BLOCK_POTATOES_STAGE1("textures\\block", "potatoes_stage1", "potatoes_stage_1", "1.6"),
    TEXTURES_BLOCK_POTATOES_STAGE2("textures\\block", "potatoes_stage2", "potatoes_stage_2", "1.6"),
    TEXTURES_BLOCK_POTATOES_STAGE3("textures\\block", "potatoes_stage3", "potatoes_stage_3", "1.6"),
    TEXTURES_BLOCK_POTTED_AZALEA_BUSH_PLANT("textures\\block", "potted_azalea_bush_plant", "1.17"),
    TEXTURES_BLOCK_POTTED_AZALEA_BUSH_SIDE("textures\\block", "potted_azalea_bush_side", "1.17"),
    TEXTURES_BLOCK_POTTED_AZALEA_BUSH_TOP("textures\\block", "potted_azalea_bush_top", "1.17"),
    TEXTURES_BLOCK_POTTED_FLOWERING_AZALEA_BUSH_PLANT("textures\\block", "potted_flowering_azalea_bush_plant", "1.17"),
    TEXTURES_BLOCK_POTTED_FLOWERING_AZALEA_BUSH_SIDE("textures\\block", "potted_flowering_azalea_bush_side", "1.17"),
    TEXTURES_BLOCK_POTTED_FLOWERING_AZALEA_BUSH_TOP("textures\\block", "potted_flowering_azalea_bush_top", "1.17"),
    TEXTURES_BLOCK_POWDER_SNOW("textures\\block", "powder_snow", "1.17"),
    TEXTURES_BLOCK_POWERED_RAIL("textures\\block", "powered_rail", "rail_golden", "1.6"),
    TEXTURES_BLOCK_POWERED_RAIL_ON("textures\\block", "powered_rail_on", "rail_golden_powered", "1.6"),
    TEXTURES_BLOCK_PRISMARINE("textures\\block", "prismarine", "prismarine_rough", "1.8"),
    TEXTURES_BLOCK_PRISMARINE_BRICKS("textures\\block", "prismarine_bricks", "1.8"),
    TEXTURES_BLOCK_PUMPKIN_SIDE("textures\\block", "pumpkin_side", "1.6"),
    TEXTURES_BLOCK_PUMPKIN_STEM("textures\\block", "pumpkin_stem", "pumpkin_stem_disconnected", "1.6"),
    TEXTURES_BLOCK_PUMPKIN_TOP("textures\\block", "pumpkin_top", "1.6"),
    TEXTURES_BLOCK_PURPLE_CANDLE("textures\\block", "purple_candle", "1.17"),
    TEXTURES_BLOCK_PURPLE_CANDLE_LIT("textures\\block", "purple_candle_lit", "1.17"),
    TEXTURES_BLOCK_PURPLE_CONCRETE("textures\\block", "purple_concrete", "concrete_purple", "1.12"),
    TEXTURES_BLOCK_PURPLE_CONCRETE_POWDER("textures\\block", "purple_concrete_powder", "concrete_powder_purple", "1.12"),
    TEXTURES_BLOCK_PURPLE_GLAZED_TERRACOTTA("textures\\block", "purple_glazed_terracotta", "glazed_terracotta_purple", "1.12"),
    TEXTURES_BLOCK_PURPLE_SHULKER_BOX("textures\\block", "purple_shulker_box", "1.13"),
    TEXTURES_BLOCK_PURPLE_STAINED_GLASS("textures\\block", "purple_stained_glass", "glass_purple", "1.7"),
    TEXTURES_BLOCK_PURPLE_STAINED_GLASS_PANE_TOP("textures\\block", "purple_stained_glass_pane_top", "glass_pane_top_purple", "1.7"),
    TEXTURES_BLOCK_PURPLE_TERRACOTTA("textures\\block", "purple_terracotta", "hardened_clay_stained_purple", "1.6"),
    TEXTURES_BLOCK_PURPLE_WOOL("textures\\block", "purple_wool", "wool_colored_purple", "1.6"),
    TEXTURES_BLOCK_PURPUR_BLOCK("textures\\block", "purpur_block", "1.9"),
    TEXTURES_BLOCK_PURPUR_PILLAR("textures\\block", "purpur_pillar", "1.9"),
    TEXTURES_BLOCK_PURPUR_PILLAR_TOP("textures\\block", "purpur_pillar_top", "1.9"),
    TEXTURES_BLOCK_QUARTZ_BLOCK_BOTTOM("textures\\block", "quartz_block_bottom", "1.6"),
    TEXTURES_BLOCK_QUARTZ_BLOCK_SIDE("textures\\block", "quartz_block_side", "1.6"),
    TEXTURES_BLOCK_QUARTZ_BLOCK_TOP("textures\\block", "quartz_block_top", "1.6"),
    TEXTURES_BLOCK_QUARTZ_BRICKS("textures\\block", "quartz_bricks", "1.16"),
    TEXTURES_BLOCK_QUARTZ_PILLAR("textures\\block", "quartz_pillar", "quartz_block_lines", "1.6"),
    TEXTURES_BLOCK_QUARTZ_PILLAR_TOP("textures\\block", "quartz_pillar_top", "quartz_block_lines_top", "1.6"),
    TEXTURES_BLOCK_RAIL("textures\\block", "rail", "rail_normal", "1.6"),
    TEXTURES_BLOCK_RAIL_CORNER("textures\\block", "rail_corner", "rail_normal_turned", "1.6"),
    TEXTURES_BLOCK_RAW_COPPER_BLOCK("textures\\block", "raw_copper_block", "1.17"),
    TEXTURES_BLOCK_RAW_GOLD_BLOCK("textures\\block", "raw_gold_block", "1.17"),
    TEXTURES_BLOCK_RAW_IRON_BLOCK("textures\\block", "raw_iron_block", "1.17"),
    TEXTURES_BLOCK_RED_CANDLE("textures\\block", "red_candle", "1.17"),
    TEXTURES_BLOCK_RED_CANDLE_LIT("textures\\block", "red_candle_lit", "1.17"),
    TEXTURES_BLOCK_RED_CONCRETE("textures\\block", "red_concrete", "concrete_red", "1.12"),
    TEXTURES_BLOCK_RED_CONCRETE_POWDER("textures\\block", "red_concrete_powder", "concrete_powder_red", "1.12"),
    TEXTURES_BLOCK_RED_GLAZED_TERRACOTTA("textures\\block", "red_glazed_terracotta", "glazed_terracotta_red", "1.12"),
    TEXTURES_BLOCK_RED_MUSHROOM("textures\\block", "red_mushroom", "mushroom_red", "1.6"),
    TEXTURES_BLOCK_RED_MUSHROOM_BLOCK("textures\\block", "red_mushroom_block", "mushroom_block_skin_red", "1.6"),
    TEXTURES_BLOCK_RED_NETHER_BRICKS("textures\\block", "red_nether_bricks", "red_nether_brick", "1.10"),
    TEXTURES_BLOCK_RED_SAND("textures\\block", "red_sand", "1.7"),
    TEXTURES_BLOCK_RED_SANDSTONE("textures\\block", "red_sandstone", "red_sandstone_normal"),
    TEXTURES_BLOCK_RED_SANDSTONE_BOTTOM("textures\\block", "red_sandstone_bottom", "1.8"),
    TEXTURES_BLOCK_RED_SANDSTONE_TOP("textures\\block", "red_sandstone_top", "1.8"),
    TEXTURES_BLOCK_RED_SHULKER_BOX("textures\\block", "red_shulker_box", "shulker_top_red", "1.11"),
    TEXTURES_BLOCK_RED_STAINED_GLASS("textures\\block", "red_stained_glass", "glass_red", "1.7"),
    TEXTURES_BLOCK_RED_STAINED_GLASS_PANE_TOP("textures\\block", "red_stained_glass_pane_top", "glass_pane_top_red", "1.7"),
    TEXTURES_BLOCK_RED_TERRACOTTA("textures\\block", "red_terracotta", "hardened_clay_stained_red", "1.6"),
    TEXTURES_BLOCK_RED_TULIP("textures\\block", "red_tulip", "flower_tulip_red", "1.7"),
    TEXTURES_BLOCK_RED_WOOL("textures\\block", "red_wool", "wool_colored_red", "1.6"),
    TEXTURES_BLOCK_REDSTONE_BLOCK("textures\\block", "redstone_block", "1.6"),
    TEXTURES_BLOCK_REDSTONE_DUST_CROSS("textures\\block", "redstone_dust_cross", "1.6"),
    TEXTURES_BLOCK_REDSTONE_DUST_DOT("textures\\block", "redstone_dust_dot", "1.9"),
    TEXTURES_BLOCK_REDSTONE_DUST_LINE("textures\\block", "redstone_dust_line", "1.6"),
    TEXTURES_BLOCK_REDSTONE_DUST_LINE0("textures\\block", "redstone_dust_line0", "1.9"),
    TEXTURES_BLOCK_REDSTONE_DUST_LINE1("textures\\block", "redstone_dust_line1", "1.9"),
    TEXTURES_BLOCK_REDSTONE_LAMP("textures\\block", "redstone_lamp", "redstone_lamp_off", "1.6"),
    TEXTURES_BLOCK_REDSTONE_LAMP_ON("textures\\block", "redstone_lamp_on", "1.6"),
    TEXTURES_BLOCK_REDSTONE_ORE("textures\\block", "redstone_ore", "1.6"),
    TEXTURES_BLOCK_REDSTONE_TORCH("textures\\block", "redstone_torch", "redstone_torch_on", "1.6"),
    TEXTURES_BLOCK_REDSTONE_TORCH_OFF("textures\\block", "redstone_torch_off", "1.6"),
    TEXTURES_BLOCK_REINFORCED_DEEPSLATE_BOTTOM("textures\\block", "reinforced_deepslate_bottom", "1.19"),
    TEXTURES_BLOCK_REINFORCED_DEEPSLATE_SIDE("textures\\block", "reinforced_deepslate_side", "1.19"),
    TEXTURES_BLOCK_REINFORCED_DEEPSLATE_TOP("textures\\block", "reinforced_deepslate_top", "1.19"),
    TEXTURES_BLOCK_REPEATER("textures\\block", "repeater", "repeater_off", "1.6"),
    TEXTURES_BLOCK_REPEATER_ON("textures\\block", "repeater_on", "1.6"),
    TEXTURES_BLOCK_REPEATING_COMMAND_BLOCK_BACK("textures\\block", "repeating_command_block_back", "1.9"),
    TEXTURES_BLOCK_REPEATING_COMMAND_BLOCK_CONDITIONAL("textures\\block", "repeating_command_block_contitional", "1.9"),
    TEXTURES_BLOCK_REPEATING_COMMAND_BLOCK_FRONT("textures\\block", "repeating_command_block_front", "1.9"),
    TEXTURES_BLOCK_REPEATING_COMMAND_BLOCK_SIDE("textures\\block", "repeating_command_block_side", "1.9"),
    TEXTURES_BLOCK_RESPAWN_ANCHOR_BOTTOM("textures\\block", "respawn_anchor_bottom", "1.16"),
    TEXTURES_BLOCK_RESPAWN_ANCHOR_SIDE0("textures\\block", "respawn_anchor_side0", "1.16"),
    TEXTURES_BLOCK_RESPAWN_ANCHOR_SIDE1("textures\\block", "respawn_anchor_side1", "1.16"),
    TEXTURES_BLOCK_RESPAWN_ANCHOR_SIDE2("textures\\block", "respawn_anchor_side2", "1.16"),
    TEXTURES_BLOCK_RESPAWN_ANCHOR_SIDE3("textures\\block", "respawn_anchor_side3", "1.16"),
    TEXTURES_BLOCK_RESPAWN_ANCHOR_SIDE4("textures\\block", "respawn_anchor_side4", "1.16"),
    TEXTURES_BLOCK_RESPAWN_ANCHOR_TOP("textures\\block", "respawn_anchor_top", "1.16"),
    TEXTURES_BLOCK_RESPAWN_ANCHOR_TOP_OFF("textures\\block", "respawn_anchor_top_off", "1.16"),
    TEXTURES_BLOCK_ROOTED_DIRT("textures\\block", "rooted_dirt", "1.17"),
    TEXTURES_BLOCK_ROSE_BUSH_BOTTOM("textures\\block", "rose_bush_bottom", "double_plant_rose_bottom", "1.7"),
    TEXTURES_BLOCK_ROSE_BUSH_TOP("textures\\block", "rose_bush_top", "double_plant_rose_top", "1.7"),
    TEXTURES_BLOCK_SAND("textures\\block", "sand", "1.6"),
    TEXTURES_BLOCK_SANDSTONE("textures\\block", "sandstone", "sandstone_normal", "1.6"),
    TEXTURES_BLOCK_SANDSTONE_BOTTOM("textures\\block", "sandstone_bottom", "1.6"),
    TEXTURES_BLOCK_SANDSTONE_TOP("textures\\block", "sandstone_top", "1.6"),
    TEXTURES_BLOCK_SCAFFOLDING_BOTTOM("textures\\block", "scaffolding_bottom", "1.14"),
    TEXTURES_BLOCK_SCAFFOLDING_SIDE("textures\\block", "scaffolding_side", "1.14"),
    TEXTURES_BLOCK_SCAFFOLDING_TOP("textures\\block", "scaffolding_top", "1.14"),
    TEXTURES_BLOCK_SCULK("textures\\block", "sculk", "1.19"),
    TEXTURES_BLOCK_SCULK_CATALYST_BOTTOM("textures\\block", "sculk_catalyst_bottom", "1.19"),
    TEXTURES_BLOCK_SCULK_CATALYST_SIDE("textures\\block", "sculk_catalyst_side", "1.19"),
    TEXTURES_BLOCK_SCULK_CATALYST_SIDE_BLOOM("textures\\block", "sculk_catalyst_side_bloom", "1.19"),
    TEXTURES_BLOCK_SCULK_CATALYST_TOP("textures\\block", "sculk_catalyst_top", "1.19"),
    TEXTURES_BLOCK_SCULK_CATALYST_TOP_BLOOM("textures\\block", "sculk_catalyst_top_bloom", "1.19"),
    TEXTURES_BLOCK_SCULK_SENSOR_BOTTOM("textures\\block", "sculk_sensor_bottom", "1.19"),
    TEXTURES_BLOCK_SCULK_SENSOR_SIDE("textures\\block", "sculk_sensor_side", "1.19"),
    TEXTURES_BLOCK_SCULK_SENSOR_TENDRIL_ACTIVE("textures\\block", "sculk_sensor_tendril_active", "1.19"),
    TEXTURES_BLOCK_SCULK_SENSOR_TENDRIL_INACTIVE("textures\\block", "sculk_sensor_tendril_inactive", "1.19"),
    TEXTURES_BLOCK_SCULK_SENSOR_TOP("textures\\block", "sculk_sensor_top", "1.19"),
    TEXTURES_BLOCK_SCULK_SHRIEKER_BOTTOM("textures\\block", "sculk_shrieker_bottom", "1.19"),
    TEXTURES_BLOCK_SCULK_SHRIEKER_CAN_SUMMON_INNER_TOP("textures\\block", "sculk_shrieker_can_summon_inner_top", "1.19"),
    TEXTURES_BLOCK_SCULK_SHRIEKER_INNER_TOP("textures\\block", "sculk_shrieker_inner_top", "1.19"),
    TEXTURES_BLOCK_SCULK_SHRIEKER_SIDE("textures\\block", "sculk_shrieker_side", "1.19"),
    TEXTURES_BLOCK_SCULK_SHRIEKER_TOP("textures\\block", "sculk_shrieker_top", "1.19"),
    TEXTURES_BLOCK_SCULK_VEIN("textures\\block", "sculk_vein", "1.19"),
    TEXTURES_BLOCK_SEA_LANTERN("textures\\block", "sea_lantern", "1.8"),
    TEXTURES_BLOCK_SEA_PICKLE("textures\\block", "sea_pickle", "1.13"),
    TEXTURES_BLOCK_SEAGRASS("textures\\block", "seagrass", "1.13"),
    TEXTURES_BLOCK_SHROOMLIGHT("textures\\block", "shroomlight", "1.16"),
    TEXTURES_BLOCK_SHULKER_BOX("textures\\block", "shulker_box", "shulker_top_purple", "1.11"),
    TEXTURES_BLOCK_SLIME_BLOCK("textures\\block", "slime_block", "slime", "1.8"),
    TEXTURES_BLOCK_SMALL_AMETHYST_BUD("textures\\block", "small_amethyst_bud", "1.17"),
    TEXTURES_BLOCK_SMALL_DRIPLEAF_SIDE("textures\\block", "small_dripleaf_side", "1.17"),
    TEXTURES_BLOCK_SMALL_DRIPLEAF_STEM_BOTTOM("textures\\block", "small_dripleaf_stem_bottom", "1.17"),
    TEXTURES_BLOCK_SMALL_DRIPLEAF_STEM_TOP("textures\\block", "small_dripleaf_stem_top", "1.17"),
    TEXTURES_BLOCK_SMALL_DRIPLEAF_TOP("textures\\block", "small_dripleaf_top", "1.17"),
    TEXTURES_BLOCK_SMITHING_TABLE_BOTTOM("textures\\block", "smithing_table_bottom", "1.14"),
    TEXTURES_BLOCK_SMITHING_TABLE_FRONT("textures\\block", "smithing_table_front", "1.14"),
    TEXTURES_BLOCK_SMITHING_TABLE_SIDE("textures\\block", "smithing_table_side", "1.14"),
    TEXTURES_BLOCK_SMITHING_TABLE_TOP("textures\\block", "smithing_table_top", "1.14"),
    TEXTURES_BLOCK_SMOKER_BOTTOM("textures\\block", "smoker_bottom", "1.14"),
    TEXTURES_BLOCK_SMOKER_FRONT("textures\\block", "smoker_front", "1.14"),
    TEXTURES_BLOCK_SMOKER_FRONT_ON("textures\\block", "smoker_front_on", "1.14"),
    TEXTURES_BLOCK_SMOKER_SIDE("textures\\block", "smoker_side", "1.14"),
    TEXTURES_BLOCK_SMOKER_TOP("textures\\block", "smoker_top", "1.14"),
    TEXTURES_BLOCK_SMOOTH_BASALT("textures\\block", "smooth_basalt", "1.16"),
    TEXTURES_BLOCK_SMOOTH_STONE("textures\\block", "smooth_stone", "stone_slab_top", "1.6"),
    TEXTURES_BLOCK_SMOOTH_STONE_SLAB_SIDE("textures\\block", "smooth_stone_slab_side", "stone_slab_side", "1.6"),
    TEXTURES_BLOCK_SNOW("textures\\block", "snow", "1.6"),
    TEXTURES_BLOCK_SOUL_CAMPFIRE_FIRE("textures\\block", "soul_campfire_fire", "1.16"),
    TEXTURES_BLOCK_SOUL_CAMPFIRE_LOG_LIT("textures\\block", "soul_campfire_log_lit", "1.16"),
    TEXTURES_BLOCK_SOUL_FIRE_0("textures\\block", "soul_fire_0", "1.16"),
    TEXTURES_BLOCK_SOUL_FIRE_1("textures\\block", "soul_fire_1", "1.16"),
    TEXTURES_BLOCK_SOUL_LANTERN("textures\\block", "soul_lantern", "1.16"),
    TEXTURES_BLOCK_SOUL_SAND("textures\\block", "soul_sand", "1.6"),
    TEXTURES_BLOCK_SOUL_SOIL("textures\\block", "soul_soil", "1.16"),
    TEXTURES_BLOCK_SOUL_TORCH("textures\\block", "soul_torch", "1.16"),
    TEXTURES_BLOCK_SPAWNER("textures\\block", "spawner", "mob_spawner", "1.6"),
    TEXTURES_BLOCK_SPONGE("textures\\block", "sponge", "1.6"),
    TEXTURES_BLOCK_SPORE_BLOSSOM("textures\\block", "spore_blossom", "1.17"),
    TEXTURES_BLOCK_SPORE_BLOSSOM_BASE("textures\\block", "spore_blossom_base", "1.17"),
    TEXTURES_BLOCK_SPRUCE_DOOR_BOTTOM("textures\\block", "spruce_door_bottom", "door_spruce_lower", "1.8"),
    TEXTURES_BLOCK_SPRUCE_DOOR_TOP("textures\\block", "spruce_door_top", "door_spruce_upper", "1.8"),
    TEXTURES_BLOCK_SPRUCE_LEAVES("textures\\block", "spruce_leaves", "leaves_spruce", "1.6"),
    TEXTURES_BLOCK_SPRUCE_LOG("textures\\block", "spruce_log", "log_spruce", "1.6"),
    TEXTURES_BLOCK_SPRUCE_LOG_TOP("textures\\block", "spruce_log_top", "log_spruce_top", "1.6"),
    TEXTURES_BLOCK_SPRUCE_PLANKS("textures\\block", "spruce_planks", "planks_spruce", "1.6"),
    TEXTURES_BLOCK_SPRUCE_SAPLING("textures\\block", "spruce_sapling", "sapling_spruce", "1.6"),
    TEXTURES_BLOCK_SPRUCE_TRAPDOOR("textures\\block", "spruce_trapdoor", "1.13"),
    TEXTURES_BLOCK_STONE("textures\\block", "stone", "1.6"),
    TEXTURES_BLOCK_STONE_BRICKS("textures\\block","stone_bricks", "stonebrick", "1.6"),
    TEXTURES_BLOCK_STONECUTTER_BOTTOM("textures\\block", "stonecutter_bottom", "1.14"),
    TEXTURES_BLOCK_STONECUTTER_SAW("textures\\block", "stonecutter_saw", "1.14"),
    TEXTURES_BLOCK_STONECUTTER_SIDE("textures\\block", "stonecutter_side", "1.14"),
    TEXTURES_BLOCK_STONECUTTER_TOP("textures\\block", "stonecutter_top", "1.14"),
    TEXTURES_BLOCK_STRIPPED_ACACIA_LOG("textures\\block", "stripped_acacia_log", "1.13"),
    TEXTURES_BLOCK_STRIPPED_ACACIA_LOG_TOP("textures\\block", "stripped_acacis_log_top", "1.13"),
    TEXTURES_BLOCK_STRIPPED_BIRCH_LOG("textures\\block", "stripped_birch_log", "1.13"),
    TEXTURES_BLOCK_STRIPPED_BIRCH_LOG_TOP("textures\\block", "stripped_birch_log_top", "1.13"),
    TEXTURES_BLOCK_STRIPPED_CRIMSON_STEM("textures\\block", "stripped_crimson_stem", "1.16"),
    TEXTURES_BLOCK_STRIPPED_CRIMSON_STEM_TOP("textures\\block", "stripped_crimson_stem_top", "1.16"),
    TEXTURES_BLOCK_STRIPPED_DARK_OAK_LOG("textures\\block", "stripped_darK_oak_log", "1.13"),
    TEXTURES_BLOCK_STRIPPED_DARK_OAK_LOG_TOP("textures\\block", "stripped_dark_oak_log_top", "1.13"),
    TEXTURES_BLOCK_STRIPPED_JUNGLE_LOG("textures\\block", "stripped_jungle_log", "1.13"),
    TEXTURES_BLOCK_STRIPPED_JUNGLE_LOG_TOP("textures\\block", "stripped_jungle_log_top", "1.13"),
    TEXTURES_BLOCK_STRIPPED_MANGROVE_LOG("textures\\block", "stripped_mangrove_log", "1.19"),
    TEXTURES_BLOCK_STRIPPED_MANGROVE_LOG_TOP("textures\\block", "stripped_mangrove_log_top", "1.19"),
    TEXTURES_BLOCK_STRIPPED_OAK_LOG("textures\\block", "stripped_oak_log", "1.13"),
    TEXTURES_BLOCK_STRIPPED_OAK_LOG_TOP("textures\\block", "stripped_oak_log_top", "1.13"),
    TEXTURES_BLOCK_STRIPPED_SPRUCE_LOG("textures\\block", "stripped_spruce_log", "1.13"),
    TEXTURES_BLOCK_STRIPPED_SPRUCE_LOG_TOP("textures\\block", "stripped_spruce_log_top", "1.13"),
    TEXTURES_BLOCK_STRIPPED_WARPED_STEM("textures\\block", "stripped_warped_stem", "1.16"),
    TEXTURES_BLOCK_STRIPPED_WARPED_STEM_TOP("textures\\block", "stripped_warped_log_stem", "1.16"),
    TEXTURES_BLOCK_STRUCTURE_BLOCK("textures\\block", "structure_block", "1.9"),
    TEXTURES_BLOCK_STRUCTURE_BLOCK_CORNER("textures\\block", "structure_block_corner", "1.9"),
    TEXTURES_BLOCK_STRUCTURE_BLOCK_DATA("textures\\block", "structure_block_data", "1.9"),
    TEXTURES_BLOCK_STRUCTURE_BLOCK_LOAD("textures\\block", "structure_block_load", "1.9"),
    TEXTURES_BLOCK_STRUCTURE_BLOCK_SAVE("textures\\block", "structure_block_save", "1.9"),
    TEXTURES_BLOCK_SUGAR_CANE("textures\\block", "sugar_cane", "reeds", "1.6"),
    TEXTURES_BLOCK_SUNFLOWER_BACK("textures\\block", "sunflower_back", "double_plant_sunflower_back", "1.7"),
    TEXTURES_BLOCK_SUNFLOWER_BOTTOM("textures\\block", "sunflower_bottom", "double_plant_sunflower_bottom", "1.7"),
    TEXTURES_BLOCK_SUNFLOWER_FRONT("textures\\block", "sunflower_front", "double_plant_sunflower_front", "1.7"),
    TEXTURES_BLOCK_SUNFLOWER_TOP("textures\\block", "sunflower_top", "double_plant_sunflower_top", "1.7"),
    TEXTURES_BLOCK_SWEET_BERRY_BUSH_STAGE0("textures\\block", "sweet_berry_bush_stage0", "1.14"),
    TEXTURES_BLOCK_SWEET_BERRY_BUSH_STAGE1("textures\\block", "sweet_berry_bush_stage1", "1.14"),
    TEXTURES_BLOCK_SWEET_BERRY_BUSH_STAGE2("textures\\block", "sweet_berry_bush_stage2", "1.14"),
    TEXTURES_BLOCK_SWEET_BERRY_BUSH_STAGE3("textures\\block", "sweet_berry_bush_stage3", "1.14"),
    TEXTURES_BLOCK_TALL_GRASS_BOTTOM("textures\\block", "tall_grass_bottom", "double_plant_grass_bottom", "1.7"),
    TEXTURES_BLOCK_TALL_GRASS_TOP("textures\\block", "tall_grass_bottom", "double_plant_grass_bottom", "1.7"),
    TEXTURES_BLOCK_TALL_SEAGRASS_BOTTOM("textures\\block", "tall_seagrass_bottom", "1.13"),
    TEXTURES_BLOCK_TALL_SEAGRASS_TOP("textures\\block", "tall_seagrass_top", "1.13"),
    TEXTURES_BLOCK_TARGET_SIDE("textures\\block", "target_side", "1.16"),
    TEXTURES_BLOCK_TARGET_TOP("textures\\block", "target_top", "1.16"),
    TEXTURES_BLOCK_TERRACOTTA("textures\\block", "terracotta", "hardened_clay", "1.6"),
    TEXTURES_BLOCK_TINTED_GLASS("textures\\block", "tinted_glass", "1.17"),
    TEXTURES_BLOCK_TNT_BOTTOM("textures\\block", "tnt_bottom", "1.6"),
    TEXTURES_BLOCK_TNT_SIDE("textures\\block", "tnt_side", "1.6"),
    TEXTURES_BLOCK_TNT_TOP("textures\\block", "tnt_top", "1.6"),
    TEXTURES_BLOCK_TORCH("textures\\block", "torch", "torch_on", "1.6"),
    TEXTURES_BLOCK_TRIPWIRE("textures\\block", "tripwire", "trip_wire", "1.6"),
    TEXTURES_BLOCK_TRIPWIRE_HOOK("textures\\block", "tripwire_hook", "trip_wire_source", "1.6"),
    TEXTURES_BLOCK_TUBE_CORAL("textures\\block", "tube_coral", "1.13"),
    TEXTURES_BLOCK_TUBE_CORAL_BLOCK("textures\\block", "tube_coral_block", "1.13"),
    TEXTURES_BLOCK_TUBE_CORAL_FAN("textures\\block", "tube_coral_fan", "1.13"),
    TEXTURES_BLOCK_TUFF("textures\\block", "tuff", "1.17"),
    TEXTURES_BLOCK_TURTLE_EGG("textures\\block", "turtle_egg", "1.13"),
    TEXTURES_BLOCK_TURTLE_EGG_SLIGHTLY_CRACKED("textures\\block", "turtle_egg_slightly_cracked", "1.13"),
    TEXTURES_BLOCK_TURTLE_EGG_VERY_CRACKED("textures\\block", "turtle_egg_very_cracked", "1.13"),
    TEXTURES_BLOCK_TWISTING_VINES("textures\\block", "twisting_vines", "1.16"),
    TEXTURES_BLOCK_TWISTING_VINES_PLANT("textures\\block", "twisting_vines_plant", "1.16"),
    TEXTURES_BLOCK_VERDANT_FROGLIGHT_SIDE("textures\\block", "verdant_froglight_side", "1.19"),
    TEXTURES_BLOCK_VERDANT_FROGLIGHT_TOP("textures\\block", "verdant_froglight_top", "1.19"),
    TEXTURES_BLOCK_VINE("textures\\block", "vine", "1.6"),
    TEXTURES_BLOCK_WARPED_DOOR_BOTTOM("textures\\block", "warped_door_bottom", "1.16"),
    TEXTURES_BLOCK_WARPED_DOOR_TOP("textures\\block", "warped_door_top", "1.16"),
    TEXTURES_BLOCK_WARPED_FUNGUS("textures\\block", "warped_fungus", "1.16"),
    TEXTURES_BLOCK_WARPED_NYLIUM("textures\\block", "warped_nylium", "1.16"),
    TEXTURES_BLOCK_WARPED_NYLIUM_SIDE("textures\\block", "warped_nylium_side", "1.16"),
    TEXTURES_BLOCK_WARPED_PLANKS("textures\\block", "warped_planks", "1.16"),
    TEXTURES_BLOCK_WARPED_ROOTS("textures\\block", "warped_roots", "1.16"),
    TEXTURES_BLOCK_WARPED_ROOTS_POT("textures\\block", "warped_roots_pot", "1.16"),
    TEXTURES_BLOCK_WARPED_STEM("textures\\block", "warped_stem", "1.16"),
    TEXTURES_BLOCK_WARPED_STEM_TOP("textures\\block", "warped_stem_top", "1.16"),
    TEXTURES_BLOCK_WARPED_TRAPDOOR("textures\\block", "warped_trapdoor", "1.16"),
    TEXTURES_BLOCK_WATER_FLOW("textures\\block", "water_flow", "1.6"),
    TEXTURES_BLOCK_WATER_OVERLAY("textures\\block", "water_overlay", "1.9"),
    TEXTURES_BLOCK_WATER_STILL("textures\\block", "water_still", "1.6"),
    TEXTURES_BLOCK_WEATHERED_COPPER("textures\\block", "weathered_copper", "1.17"),
    TEXTURES_BLOCK_WEATHERED_CUT_COPPER("textures\\block", "weathered_cut_copper", "1.17"),
    TEXTURES_BLOCK_WEEPING_VINES("textures\\block", "weeping_vines", "1.16"),
    TEXTURES_BLOCK_WEEPING_VINES_PLANT("textures\\block", "weeping_vines_plant", "1.16"),
    TEXTURES_BLOCK_WET_SPONGE("textures\\block", "wet_sponge", "sponge_wet", "1.8"),
    TEXTURES_BLOCK_WHEAT_STAGE0("textures\\block", "wheat_stage0", "wheat_stage_0", "1.6"),
    TEXTURES_BLOCK_WHEAT_STAGE1("textures\\block", "wheat_stage1", "wheat_stage_1", "1.6"),
    TEXTURES_BLOCK_WHEAT_STAGE2("textures\\block", "wheat_stage2", "wheat_stage_2", "1.6"),
    TEXTURES_BLOCK_WHEAT_STAGE3("textures\\block", "wheat_stage3", "wheat_stage_3", "1.6"),
    TEXTURES_BLOCK_WHEAT_STAGE4("textures\\block", "wheat_stage4", "wheat_stage_4", "1.6"),
    TEXTURES_BLOCK_WHEAT_STAGE5("textures\\block", "wheat_stage5", "wheat_stage_5", "1.6"),
    TEXTURES_BLOCK_WHEAT_STAGE6("textures\\block", "wheat_stage6", "wheat_stage_6", "1.6"),
    TEXTURES_BLOCK_WHEAT_STAGE7("textures\\block", "wheat_stage7", "wheat_stage_7", "1.6"),
    TEXTURES_BLOCK_WHITE_CANDLE("textures\\block", "white_candle", "1.17"),
    TEXTURES_BLOCK_WHITE_CANDLE_LIT("textures\\block", "white_candle_lit", "1.17"),
    TEXTURES_BLOCK_WHITE_CONCRETE("textures\\block", "white_concrete", "concrete_white", "1.12"),
    TEXTURES_BLOCK_WHITE_CONCRETE_POWDER("textures\\block", "white_concrete_powder", "concrete_powder_white", "1.12"),
    TEXTURES_BLOCK_WHITE_GLAZED_TERRACOTTA("textures\\block", "white_glazed_terracotta", "glazed_terracotta_white", "1.12"),
    TEXTURES_BLOCK_WHITE_SHULKER_BOX("textures\\block", "white_shulker_box", "shulker_top_white", "1.11"),
    TEXTURES_BLOCK_WHITE_STAINED_GLASS("textures\\block", "white_stained_glass", "glass_white", "1.7"),
    TEXTURES_BLOCK_WHITE_STAINED_GLASS_PANE_TOP("textures\\block", "white_stained_glass_pane_top", "glass_pane_top_white", "1.7"),
    TEXTURES_BLOCK_WHITE_TERRACOTTA("textures\\block", "orage_terracotta", "hardened_clay_stained_white", "1.6"),
    TEXTURES_BLOCK_WHITE_TULIP("textures\\block", "white_tulip", "flower_tulip_white", "1.7"),
    TEXTURES_BLOCK_WHITE_WOOL("textures\\block", "white_wool", "wool_colored_white", "1.6"),
    TEXTURES_BLOCK_WITHER_ROSE("textures\\block", "wither_rose", "1.14"),
    TEXTURES_BLOCK_YELLOW_CANDLE("textures\\block", "yellow_candle", "1.17"),
    TEXTURES_BLOCK_YELLOW_CANDLE_LIT("textures\\block", "yellow_candle_lit", "1.17"),
    TEXTURES_BLOCK_YELLOW_CONCRETE("textures\\block", "yellow_concrete", "concrete_yellow", "1.12"),
    TEXTURES_BLOCK_YELLOW_CONCRETE_POWDER("textures\\block", "yellow_concrete_powder", "concrete_powder_yellow", "1.12"),
    TEXTURES_BLOCK_YELLOW_GLAZED_TERRACOTTA("textures\\block", "yellow_glazed_terracotta", "glazed_terracotta_yellow", "1.12"),
    TEXTURES_BLOCK_YELLOW_SHULKER_BOX("textures\\block", "yellow_shulker_box", "shulker_top_yellow", "1.11"),
    TEXTURES_BLOCK_YELLOW_STAINED_GLASS("textures\\block", "yellow_stained_glass", "glass_yellow", "1.7"),
    TEXTURES_BLOCK_YELLOW_STAINED_GLASS_PANE_TOP("textures\\block", "yellow_stained_glass_pane_top", "glass_pane_top_yellow", "1.7"),
    TEXTURES_BLOCK_YELLOW_TERRACOTTA("textures\\block", "orage_terracotta", "hardened_clay_stained_yellow", "1.6"),
    TEXTURES_BLOCK_YELLOW_WOOL("textures\\block", "yellow_wool", "wool_colored_yellow", "1.6");

    Block(String dir, String nameNew, String nameOld, String introducedVersion) {
        this.dir = dir;
        this.nameNew = nameNew;
        this.nameOld = nameOld;
        this.introducedVersion = introducedVersion;
    }

    Block(String dir, String nameNew, String introducedVersion) {
        this.dir = dir;
        this.nameNew = nameNew;
        this.nameOld = nameNew;
        this.introducedVersion = introducedVersion;
    }



    private final String dir;
    private final String nameNew;
    private final String nameOld;
    private final String introducedVersion;

    @Override
    public String getDirectory() {
        return dir;
    }

    @Override
    public String getNewerName() {
        return nameNew;
    }

    @Override
    public String getOlderNames() {
        return nameOld;
    }

    @Override
    public String getIntroducedVersion() {
        return introducedVersion;
    }


}
