package me.bruno.packbuilder.enums.texture;

import me.bruno.packbuilder.enums.Files;

public enum Entity implements Files {
    // textures/entity

    TEXTURES_ENTITY_ALLAY_DIR("textures\\entity", "allay", "1.19"),
    TEXTURES_ENTITY_ALLAY_ALLAY("textures\\entity\\allay", "allay", "1.19"),
    TEXTURES_ENTITY_ARMORSTAND_DIR("textures\\entity", "armorstand", "1.8"),
    TEXTURES_ENTITY_ARMORSTAND_WOOD("textures\\entity\\armorstand", "wood", "1.8"),
    TEXTURES_ENTITY_AXOLOTL_DIR("textures\\entity", "axolotl", "1.17"),
    TEXTURES_ENTITY_AXOLOTL_BLUE("textures\\entity\\axolotl", "axolotl_blue", "1.17"),
    TEXTURES_ENTITY_AXOLOTL_CYAN("textures\\entity\\axolotl", "axolotl_cyan", "1.17"),
    TEXTURES_ENTITY_AXOLOTL_GOLD("textures\\entity\\axolotl", "axolotl_gold", "1.17"),
    TEXTURES_ENTITY_AXOLOTL_LUCY("textures\\entity\\axolotl", "axolotl_lucy", "1.17"),
    TEXTURES_ENTITY_AXOLOTL_WILD("textures\\entity\\axolotl", "axolotl_wild", "1.17"),
    TEXTURES_ENTITY_BANNER_DIR("textures\\entity", "banner", "1.8"),
    TEXTURES_ENTITY_BANNER_BASE("textures\\entity\\banner", "base", "1.8"),
    TEXTURES_ENTITY_BANNER_BORDER("textures\\entity\\banner", "border", "1.8"),
    TEXTURES_ENTITY_BANNER_BRICKS("textures\\entity\\banner", "bricks", "1.8"),
    TEXTURES_ENTITY_BANNER_CIRCLE("textures\\entity\\banner", "circle", "1.8"),
    TEXTURES_ENTITY_BANNER_CREEPER("textures\\entity\\banner", "creeper", "1.8"),
    TEXTURES_ENTITY_BANNER_CROSS("textures\\entity\\banner", "cross", "1.8"),
    TEXTURES_ENTITY_BANNER_CURLY_BORDER("textures\\entity\\banner", "curly_border", "1.8"),
    TEXTURES_ENTITY_BANNER_DIAGONAL_LEFT("textures\\entity\\banner", "diagonal_left", "1.8"),
    TEXTURES_ENTITY_BANNER_DIAGONAL_RIGHT("textures\\entity\\banner", "diagonal_right", "1.8"),
    TEXTURES_ENTITY_BANNER_DIAGONAL_UP_LEFT("textures\\entity\\banner", "diagonal_up_left", "1.8"),
    TEXTURES_ENTITY_BANNER_DIAGONAL_UP_RIGHT("textures\\entity\\banner", "diagonal_up_right", "1.8"),
    TEXTURES_ENTITY_BANNER_FLOWER("textures\\entity\\banner", "flower", "1.8"),
    TEXTURES_ENTITY_BANNER_GLOBE("textures\\entity\\banner", "globe", "1.14"),
    TEXTURES_ENTITY_BANNER_GRADIENT("textures\\entity\\banner", "gradient", "1.8"),
    TEXTURES_ENTITY_BANNER_GRADIENT_UP("textures\\entity\\banner", "gradient_up", "1.8"),
    TEXTURES_ENTITY_BANNER_HALF_HORIZONTAL("textures\\entity\\banner", "half_horizontal", "1.8"),
    TEXTURES_ENTITY_BANNER_HALF_HORIZONTAL_BOTTOM("textures\\entity\\banner", "half_horizontal_bottom", "1.8"),
    TEXTURES_ENTITY_BANNER_HALF_VERTICAL("textures\\entity\\banner", "half_vertical", "1.8"),
    TEXTURES_ENTITY_BANNER_HALF_VERTICAL_RIGHT("textures\\entity\\banner", "half_vertical_right", "1.8"),
    TEXTURES_ENTITY_BANNER_MOJANG("textures\\entity\\banner", "mojang", "1.8"),
    TEXTURES_ENTITY_BANNER_PIGLIN("textures\\entity\\banner", "piglin", "1.16"),
    TEXTURES_ENTITY_BANNER_RHOMBUS("textures\\entity\\banner", "rhombus", "1.8"),
    TEXTURES_ENTITY_BANNER_SKULL("textures\\entity\\banner", "skull", "1.8"),
    TEXTURES_ENTITY_BANNER_SMALL_STRIPES("textures\\entity\\banner", "small_stripes", "1.8"),
    TEXTURES_ENTITY_BANNER_SQUARE_BOTTOM_LEFT("textures\\entity\\banner", "square_bottom_left", "1.8"),
    TEXTURES_ENTITY_BANNER_SQUARE_BOTTOM_RIGHT("textures\\entity\\banner", "square_bottom_right", "1.8"),
    TEXTURES_ENTITY_BANNER_SQUARE_TOP_LEFT("textures\\entity\\banner", "square_top_left", "1.8"),
    TEXTURES_ENTITY_BANNER_SQUARE_TOP_RIGHT("textures\\entity\\banner", "square_top_right", "1.8"),
    TEXTURES_ENTITY_BANNER_STRAIGHT_CROSS("textures\\entity\\banner", "straight_cross", "1.8"),
    TEXTURES_ENTITY_BANNER_STRIPE_BOTTOM("textures\\entity\\banner", "stripe_bottom", "1.8"),
    TEXTURES_ENTITY_BANNER_STRIPE_CENTER("textures\\entity\\banner", "stripe_center", "1.8"),
    TEXTURES_ENTITY_BANNER_STRIPE_DOWNLEFT("textures\\entity\\banner", "stripe_downleft", "1.8"),
    TEXTURES_ENTITY_BANNER_STRIPE_DOWNRIGHT("textures\\entity\\banner", "stripe_downright", "1.8"),
    TEXTURES_ENTITY_BANNER_STRIPE_LEFT("textures\\entity\\banner", "stripe_left", "1.8"),
    TEXTURES_ENTITY_BANNER_STRIPE_MIDDLE("textures\\entity\\banner", "stripe_middle", "1.8"),
    TEXTURES_ENTITY_BANNER_STRIPE_RIGHT("textures\\entity\\banner", "stripe_right", "1.8"),
    TEXTURES_ENTITY_BANNER_STRIPE_TOP("textures\\entity\\banner", "stripe_top", "1.8"),
    TEXTURES_ENTITY_BANNER_TRIANGLE_BOTTOM("textures\\entity\\banner", "triangle_bottom", "1.8"),
    TEXTURES_ENTITY_BANNER_TRIANGLE_TOP("textures\\entity\\banner", "triangle_top", "1.8"),
    TEXTURES_ENTITY_BANNER_TRIANGLES_BOTTOM("textures\\entity\\banner", "triangles_bottom", "1.8"),
    TEXTURES_ENTITY_BANNER_TRIANGLES_TOP("textures\\entity\\banner", "triangles_top", "1.8"),
    TEXTURES_ENTITY_BEAR_DIR("textures\\entity", "bear", "1.10"),
    TEXTURES_ENTITY_BEAR_POLARBEAR("textures\\entity\\bear", "polarbear", "1.10"),
    TEXTURES_ENTITY_BED_DIR("textures\\entity", "bed", "1.12"),
    TEXTURES_ENTITY_BED_BLACK("textures\\entity\\bed", "black", "1.12"),
    TEXTURES_ENTITY_BED_BLUE("textures\\entity\\bed", "blue", "1.12"),
    TEXTURES_ENTITY_BED_BROWN("textures\\entity\\bed", "brown", "1.12"),
    TEXTURES_ENTITY_BED_CYAN("textures\\entity\\bed", "cyan", "1.12"),
    TEXTURES_ENTITY_BED_GRAY("textures\\entity\\bed", "gray", "1.12"),
    TEXTURES_ENTITY_BED_GREEN("textures\\entity\\bed", "green", "1.12"),
    TEXTURES_ENTITY_BED_LIGHT_BLUE("textures\\entity\\bed", "light_blue", "1.12"),
    TEXTURES_ENTITY_BED_LIGHT_GRAY("textures\\entity\\bed", "light_gray", "silver", "1.12"),
    TEXTURES_ENTITY_BED_LIME("textures\\entity\\bed", "lime", "1.12"),
    TEXTURES_ENTITY_BED_MAGENTA("textures\\entity\\bed", "magenta", "1.12"),
    TEXTURES_ENTITY_BED_ORANGE("textures\\entity\\bed", "orange", "1.12"),
    TEXTURES_ENTITY_BED_PINK("textures\\entity\\bed", "pink", "1.12"),
    TEXTURES_ENTITY_BED_PURPLE("textures\\entity\\bed", "purple", "1.12"),
    TEXTURES_ENTITY_BED_RED("textures\\entity\\bed", "red", "1.12"),
    TEXTURES_ENTITY_BED_WHITE("textures\\entity\\bed", "white", "1.12"),
    TEXTURES_ENTITY_BED_YELLOW("textures\\entity\\bed", "yellow", "1.12"),
    TEXTURES_ENTITY_BEE_DIR("textures\\entity", "bee", "1.15"),
    TEXTURES_ENTITY_BEE("textures\\entity\\bee", "bee", "1.15"),
    TEXTURES_ENTITY_BEE_ANGRY("textures\\entity\\bee", "bee_angry", "1.15"),
    TEXTURES_ENTITY_BEE_ANGRY_NECTAR("textures\\entity\\bee", "bee_angry_nectar", "1.15"),
    TEXTURES_ENTITY_BEE_NECTAR("textures\\entity\\bee", "bee_nectar", "1.15"),
    TEXTURES_ENTITY_BEE_STINGER("textures\\entity\\bee", "bee_stinger", "1.15"),
    TEXTURES_ENTITY_BELL_DIR("textures\\entity", "bell", "1.14"),
    TEXTURES_ENTITY_BELL_BODY("textures\\entity\\bell", "bell_body", "1.14"),
    TEXTURES_ENTITY_BOAT("textures\\entity", "boat", "1.9"),
    TEXTURES_ENTITY_BOAT_ACACIA("textures\\entity\\boat", "acacia", "boat_acacia", "1.9"),
    TEXTURES_ENTITY_BOAT_BIRCH("textures\\entity\\boat", "birch", "boat_birch", "1.9"),
    TEXTURES_ENTITY_BOAT_DARK_OAK("textures\\entity\\boat", "dark_oak", "boat_darkoak", "1.9"),
    TEXTURES_ENTITY_BOAT_JUNGLE("textures\\entity\\boat", "jungle", "boat_jungle", "1.9"),
    TEXTURES_ENTITY_BOAT_MANGROVE("textures\\entity\\boat", "mangrove", "1.19"),
    TEXTURES_ENTITY_BOAT_OAK("textures\\entity\\boat", "oak", "boat_oak", "1.9"),
    TEXTURES_ENTITY_BOAT_SPRUCE("textures\\entity\\boat", "spruce", "boat_spruce", "1.9"),
    TEXTURES_ENTITY_CAT_DIR("textures\\entity", "cat", "1.6"),
    TEXTURES_ENTITY_CAT_ALL_BLACK("textures\\entity\\cat", "all_black", "1.14"),
    TEXTURES_ENTITY_CAT_BLACK("textures\\entity\\cat", "black", "1.6"),
    TEXTURES_ENTITY_CAT_BRITISH_SHORTHAIR("textures\\entity\\cat", "british_shorthair", "1.14"),
    TEXTURES_ENTITY_CAT_CALICO("textures\\entity\\cat", "calico", "1.14"),
    TEXTURES_ENTITY_CAT_COLLAR("textures\\entity\\cat", "cat_collar", "1.14"),
    TEXTURES_ENTITY_CAT_JELLIE("textures\\entity\\cat", "jellie", "1.14"),
    TEXTURES_ENTITY_CAT_OCELOT("textures\\entity\\cat", "ocelot", "1.6"),
    TEXTURES_ENTITY_CAT_PERSIAN("textures\\entity\\cat", "persian", "1.14"),
    TEXTURES_ENTITY_CAT_RAGDOLL("textures\\entity\\cat", "ragdoll", "1.14"),
    TEXTURES_ENTITY_CAT_RED("textures\\entity\\cat", "red", "1.6"),
    TEXTURES_ENTITY_CAT_SIAMESE("textures\\entity\\cat", "siamese", "1.6"),
    TEXTURES_ENTITY_CAT_TABBY("textures\\entity\\cat", "tabby", "1.14"),
    TEXTURES_ENTITY_CAT_WHITE("textures\\entity\\cat", "white", "1.14"),
    TEXTURES_ENTITY_CHEST_DIR("textures\\entity", "chest", "1.6"),
    TEXTURES_ENTITY_CHEST_CHRISTMAS("textures\\entity\\chest", "christmas", "1.6"),
    TEXTURES_ENTITY_CHEST_CHRISTMAS_DOUBLE("textures\\entity\\chest", "christmas_double", "1.6"),
    TEXTURES_ENTITY_CHEST_CHRISTMAS_LEFT("textures\\entity\\chest", "christmas_left", "1.15"),
    TEXTURES_ENTITY_CHEST_CHRISTMAS_RIGHT("textures\\entity\\chest", "christmas_right", "1.15"),
    TEXTURES_ENTITY_CHEST_ENDER("textures\\entity\\chest", "ender", "1.6"),
    TEXTURES_ENTITY_CHEST_NORMAL("textures\\entity\\chest", "normal", "1.6"),
    TEXTURES_ENTITY_CHEST_NORMAL_DOUBLE("textures\\entity\\chest", "normal_double", "1.6"),
    TEXTURES_ENTITY_CHEST_NORMAL_LEFT("textures\\entity\\chest", "normal_left", "1.15"),
    TEXTURES_ENTITY_CHEST_NORMAL_RIGHT("textures\\entity\\chest", "normal_right", "1.15"),
    TEXTURES_ENTITY_CHEST_TRAPPED("textures\\entity\\chest", "trapped", "1.6"),
    TEXTURES_ENTITY_CHEST_TRAPPED_DOUBLE("textures\\entity\\chest", "trapped_double", "1.6"),
    TEXTURES_ENTITY_CHEST_TRAPPED_LEFT("textures\\entity\\chest", "trapped_left", "1.15"),
    TEXTURES_ENTITY_CHEST_TRAPPED_RIGHT("textures\\entity\\chest", "trapped_right", "1.15"),
    TEXTURES_ENTITY_CHEST_BOAT_DIR("textures\\entity", "chest_boat", "1.19"),
    TEXTURES_ENTITY_CHEST_BOAT_ACACIA("textures\\entity\\chest_boat", "acacia", "1.19"),
    TEXTURES_ENTITY_CHEST_BOAT_BIRCH("textures\\entity\\chest_boat", "birch", "1.19"),
    TEXTURES_ENTITY_CHEST_BOAT_DARK_OAK("textures\\entity\\chest_boat", "dark_oak", "1.19"),
    TEXTURES_ENTITY_CHEST_BOAT_JUNGLE("textures\\entity\\chest_boat", "jungle", "1.19"),
    TEXTURES_ENTITY_CHEST_BOAT_MANGROVE("textures\\entity\\chest_boat", "mangrove", "1.19"),
    TEXTURES_ENTITY_CHEST_BOAT_OAK("textures\\entity\\chest_boat", "oak", "1.19"),
    TEXTURES_ENTITY_CHEST_BOAT_SPRUCE("textures\\entity\\chest_boat", "spruce", "1.19"),
    TEXTURES_ENTITY_CONDUIT_DIR("textures\\entity", "conduit", "1.13"),
    TEXTURES_ENTITY_CONDUIT_BASE("textures\\entity\\conduit", "base", "1.13"),
    TEXTURES_ENTITY_CONDUIT_BREAK_PARTICLE("textures\\entity\\conduit", "break_particle", "1.13"),
    TEXTURES_ENTITY_CONDUIT_CAGE("textures\\entity\\conduit", "cage", "1.13"),
    TEXTURES_ENTITY_CONDUIT_CLOSED_EYE("textures\\entity\\conduit", "closed_eye", "1.13"),
    TEXTURES_ENTITY_CONDUIT_OPEN_EYE("textures\\entity\\conduit", "open_eye", "1.13"),
    TEXTURES_ENTITY_CONDUIT_WIND("textures\\entity\\conduit", "wind", "1.13"),
    TEXTURES_ENTITY_CONDUIT_WIND_VERTICAL("textures\\entity\\conduit", "wind_vertical", "1.13"),
    TEXTURES_ENTITY_COW_DIR("textures\\entity", "cow", "1.6"),
    TEXTURES_ENTITY_COW_COW("textures\\entity\\cow", "cow", "1.6"),
    TEXTURES_ENTITY_COW_MOOSHROOM("textures\\entity\\cow", "mooshroom", "1.6"),
    TEXTURES_ENTITY_COW_RED_MOOSHROOM("textures\\entity\\cow", "red_mooshroom", "1.14"),
    TEXTURES_ENTITY_COW_BROWN_MOOSHROOM("textures\\entity\\cow", "brown_mooshroom", "1.14"),
    TEXTURES_ENTITY_CREEPER_DIR("textures\\entity", "creeper", "1.6"),
    TEXTURES_ENTITY_CREEPER_CREEPER("textures\\entity\\creeper", "creeper", "1.6"),
    TEXTURES_ENTITY_CREEPER_CREEPER_ARMOR("textures\\entity\\creeper", "creeper_armor", "1.6"),
    TEXTURES_ENTITY_END_CRYSTAL_DIR("textures\\entity", "end_crystal", "endercrystal", "1.6"),
    TEXTURES_ENTITY_END_CRYSTAL_END_CRYSTAL("textures\\entity\\end_crystal", "end_crystal", "1.6"),
    TEXTURES_ENTITY_END_CRYSTAL_END_CRYSTAL_BEAM("texture\\entity\\end_crystal", "end_crystal_beam", "1.6"),
    TEXTURES_ENTITY_ENDERDRAGON_DIR("textures\\entity", "enderdragon", "1.6"),
    TEXTURES_ENTITY_ENDERDRAGON_DRAGON("textures\\entity\\enderdragon", "dragon", "1.6"),
    TEXTURES_ENTITY_ENDERDRAGON_DRAGON_EXPLODING("textures\\entity\\enderdragon", "dragon_exploding", "1.6"),
    TEXTURES_ENTITY_ENDERDRAGON_DRAGON_EYES("textures\\entity\\enderdragon", "dragon_eyes", "1.6"),
    TEXTURES_ENTITY_ENDERDRAGON_DRAGON_FIREBALL("textures\\entity\\enderdragon", "dragon_fireball", "1.9"),
    TEXTURES_ENTITY_ENDERMAN_DIR("textures\\entity", "enderman", "1.6"),
    TEXTURES_ENTITY_ENDERMAN_ENDERMAN("textures\\entity\\enderman", "enderman", "1.6"),
    TEXTURES_ENTITY_ENDERMAN_ENDERMAN_EYES("textures\\entity\\enderman", "enderman_eyes", "1.6"),
    TEXTURES_ENTITY_FISH_DIR("textures\\entity", "fish", "1.13"),
    TEXTURES_ENTITY_FISH_COD("textures\\entity\\fish", "cod", "1.13"),
    TEXTURES_ENTITY_FISH_PUFFERFISH("textures\\entity\\fish", "pufferfish", "1.13"),
    TEXTURES_ENTITY_FISH_SALMON("textures\\entity\\fish", "salmon", "1.13"),
    TEXTURES_ENTITY_FISH_TROPICAL_A("textures\\entity\\fish", "tropical_a", "1.13"),
    TEXTURES_ENTITY_FISH_TROPICAL_A_1("textures\\entity\\fish", "tropical_a_1", "1.13"),
    TEXTURES_ENTITY_FISH_TROPICAL_A_2("textures\\entity\\fish", "tropical_a_2", "1.13"),
    TEXTURES_ENTITY_FISH_TROPICAL_A_3("textures\\entity\\fish", "tropical_a_3", "1.13"),
    TEXTURES_ENTITY_FISH_TROPICAL_A_4("textures\\entity\\fish", "tropical_a_4", "1.13"),
    TEXTURES_ENTITY_FISH_TROPICAL_A_5("textures\\entity\\fish", "tropical_a_5", "1.13"),
    TEXTURES_ENTITY_FISH_TROPICAL_A_6("textures\\entity\\fish", "tropical_a_6", "1.13"),
    TEXTURES_ENTITY_FISH_TROPICAL_B("textures\\entity\\fish", "tropical_b", "1.13"),
    TEXTURES_ENTITY_FISH_TROPICAL_B_1("textures\\entity\\fish", "tropical_b_1", "1.13"),
    TEXTURES_ENTITY_FISH_TROPICAL_B_2("textures\\entity\\fish", "tropical_b_2", "1.13"),
    TEXTURES_ENTITY_FISH_TROPICAL_B_3("textures\\entity\\fish", "tropical_b_3", "1.13"),
    TEXTURES_ENTITY_FISH_TROPICAL_B_4("textures\\entity\\fish", "tropical_b_4", "1.13"),
    TEXTURES_ENTITY_FISH_TROPICAL_B_5("textures\\entity\\fish", "tropical_b_5", "1.13"),
    TEXTURES_ENTITY_FISH_TROPICAL_B_6("textures\\entity\\fish", "tropical_b_6", "1.13"),
    TEXTURES_ENTITY_FOX_DIR("textures\\entity", "fox", "1.14"),
    TEXTURES_ENTITY_FOX_FOX("textures\\entity\\fox", "fox", "1.14"),
    TEXTURES_ENTITY_FOX_FOX_SLEEP("textures\\entity\\fox", "fox_sleep", "1.14"),
    TEXTURES_ENTITY_FOX_SNOW_FOX("textures\\entity\\fox", "snow_fox", "1.14"),
    TEXTURES_ENTITY_FOX_SNOW_FOX_SLEEP("textures\\entity\\fox", "snow_fox_sleep", "1.14"),
    TEXTURES_ENTITY_FROG_DIR("textures\\entity", "frog", "1.19"),
    TEXTURES_ENTITY_FROG_COLD_FROG("textures\\entity\\frog", "cold_frog", "1.19"),
    TEXTURES_ENTITY_FROG_TEMPERATE_FROG("textures\\entity\\frog", "temperate_frog", "1.19"),
    TEXTURES_ENTITY_FROG_WARM_FROG("textures\\entity\\frog", "warm_frog", "1.19"),
    TEXTURES_ENTITY_GHAST_DIR("textures\\entity", "ghast", "1.6"),
    TEXTURES_ENTITY_GHAST_GHAST("textures\\entity\\ghast", "ghast", "1.6"),
    TEXTURES_ENTITY_GHAST_GHAST_SHOOTING("textures\\entity\\ghast", "ghast_shooting", "1.6"),
    TEXTURES_ENTITY_GOAT_DIR("textures\\entity", "goat", "1.17"),
    TEXTURES_ENTITY_GOAT_GOAT("textures\\entity\\goat", "goat", "1.17"),
    TEXTURES_ENTITY_HOGLIN_DIR("textures\\entity", "hoglin", "1.16"),
    TEXTURES_ENTITY_HOGLIN_HOGLIN("textures\\entity\\hoglin", "hoglin", "1.16"),
    TEXTURES_ENTITY_HOGLIN_ZOGLIN("textures\\entity\\hoglin", "zoglin", "1.16"),
    TEXTURES_ENTITY_HORSE_DIR("textures\\entity", "horse", "1.6"),
    TEXTURES_ENTITY_HORSE_ARMOR_DIR("textures\\entity\\horse", "armor", "1.6"),
    TEXTURES_ENTITY_HORSE_ARMOR_HORSE_ARMOR_DIAMOND("textures\\entity\\horse\\armor", "horse_armor_diamond", "1.6"),
    TEXTURES_ENTITY_HORSE_ARMOR_HORSE_ARMOR_GOLD("textures\\entity\\horse\\armor", "horse_armor_gold", "1.6"),
    TEXTURES_ENTITY_HORSE_ARMOR_HORSE_ARMOR_IRON("textures\\entity\\horse\\armor", "horse_armor_iron", "1.6"),
    TEXTURES_ENTITY_HORSE_ARMOR_HORSE_ARMOR_LEATHER("textures\\entity\\horse\\armor", "horse_armor_leather", "1.6"),
    TEXTURES_ENTITY_HORSE_DONKEY("textures\\entity\\horse", "donkey", "1.6"),
    TEXTURES_ENTITY_HORSE_HORSE_BLACK("textures\\entity\\horse", "horse_black", "1.6"),
    TEXTURES_ENTITY_HORSE_HORSE_BROWN("textures\\entity\\horse", "horse_brown", "1.6"),
    TEXTURES_ENTITY_HORSE_HORSE_CHESTNUT("textures\\entity\\horse", "horse_chestnut", "1.6"),
    TEXTURES_ENTITY_HORSE_HORSE_CREAMY("textures\\entity\\horse", "horse_creamy", "1.6"),
    TEXTURES_ENTITY_HORSE_HORSE_DARKBROWN("textures\\entity\\horse", "horse_darkbrown", "1.6"),
    TEXTURES_ENTITY_HORSE_HORSE_GRAY("textures\\entity\\horse", "horse_gray", "1.6"),
    TEXTURES_ENTITY_HORSE_HORSE_MARKINGS_BLACKDOTS("textures\\entity\\horse", "horse_markings_blackdots", "1.6"),
    TEXTURES_ENTITY_HORSE_HORSE_MARKINGS_WHITE("textures\\entity\\horse", "horse_markings_white", "1.6"),
    TEXTURES_ENTITY_HORSE_HORSE_MARKINGS_WHITEDOTS("textures\\entity\\horse", "horse_markings_whitedots", "1.6"),
    TEXTURES_ENTITY_HORSE_HORSE_MARKINGS_WHITEFILLED("textures\\entity\\horse", "horse_markings_whitefilled", "1.6"),
    TEXTURES_ENTITY_HORSE_HORSE_SKELETON("textures\\entity\\horse", "horse_skeleton", "1.6"),
    TEXTURES_ENTITY_HORSE_HORSE_WHITE("textures\\entity\\horse", "horse_white", "1.6"),
    TEXTURES_ENTITY_HORSE_HORSE_ZOMBIE("textures\\entity\\horse", "horse_zombie", "1.6"),
    TEXTURES_ENTITY_HORSE_MULE("textures\\entity\\horse", "mule", "1.6"),
    TEXTURES_ENTITY_ILLAGER_DIR("textures\\entity", "illager", "1.14"),
    TEXTURES_ENTITY_ILLAGER_EVOKER("textures\\entity\\illager", "evoker", "1.14"),
    TEXTURES_ENTITY_ILLAGER_EVOKER_FANGS("textures\\entity\\illager", "evoker_fangs", "1.14"),
    TEXTURES_ENTITY_ILLAGER_ILLUSIONER("textures\\entity\\illager", "illusioner", "1.14"),
    TEXTURES_ENTITY_ILLAGER_PILLAGER("textures\\entity\\illager", "pillager", "1.14"),
    TEXTURES_ENTITY_ILLAGER_RAVAGER("textures\\entity\\illager", "ravager", "1.14"),
    TEXTURES_ENTITY_ILLAGER_VEX("textures\\entity\\illager", "vex", "1.14"),
    TEXTURES_ENTITY_ILLAGER_VEX_CHARGING("textures\\entity\\illager", "vex_charging", "1.14"),
    TEXTURES_ENTITY_ILLAGER_VINDICATOR("textures\\entity\\illager", "vindicator", "1.14"),
    TEXTURES_ENTITY_IRON_GOLEM_DIR("textures\\entity", "iron_golem", "1.15"),
    TEXTURES_ENTITY_IRON_GOLEM_IRON_GOLEM("textures\\entity", "iron_golem\\iron_golem", "iron_golem", "1.6"),
    TEXTURES_ENTITY_IRON_GOLEM_IRON_GOLEM_CRACKINESS_HIGH("textures\\entity\\iron_golem", "iron_golem_crackiness_high", "1.15"),
    TEXTURES_ENTITY_IRON_GOLEM_IRON_GOLEM_CRACKINESS_LOW("textures\\entity\\iron_golem", "iron_golem_crackiness_low", "1.15"),
    TEXTURES_ENTITY_IRON_GOLEM_IRON_GOLEM_CRACKINESS_MEDIUM("textures\\entity\\iron_golem", "iron_golem_crackiness_medium", "1.15"),
    TEXTURES_ENTITY_LLAMA_DIR("textures\\entity", "llama", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR("textures\\entity\\llama", "decor", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_BLACK("textures\\entity\\llama\\decor", "black", "decor_black", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_BLUE("textures\\entity\\llama\\decor", "blue", "decor_blue", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_BROWN("textures\\entity\\llama\\decor", "brown", "decor_brown", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_CYAN("textures\\entity\\llama\\decor", "cyan", "decor_cyan", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_GRAY("textures\\entity\\llama\\decor", "gray", "decor_gray", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_GREEN("textures\\entity\\llama\\decor", "green", "decor_green", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_LIGHT_BLUE("textures\\entity\\llama\\decor", "light_blue", "decor_light_blue", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_LIGHT_GRAY("textures\\entity\\llama\\decor", "light_gray", "decor_silver", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_LIME("textures\\entity\\llama\\decor", "lime", "decor_lime", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_MAGENTA("textures\\entity\\llama\\decor", "magenta", "decor_magenta", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_ORANGE("textures\\entity\\llama\\decor", "orange", "decor_orange", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_PINK("textures\\entity\\llama\\decor", "pink", "decor_pink", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_PURPLE("textures\\entity\\llama\\decor", "purple", "decor_purple", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_RED("textures\\entity\\llama\\decor", "red", "decor_red", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_TRADER_LLAMA("textures\\entity\\llama\\decor", "trader_llama", "1.14"),
    TEXTURES_ENTITY_LLAMA_DECOR_WHITE("textures\\entity\\llama\\decor", "white", "decor_white", "1.11"),
    TEXTURES_ENTITY_LLAMA_DECOR_YELLOW("textures\\entity\\llama\\decor", "yellow", "decor_yellow", "1.11"),
    TEXTURES_ENTITY_LLAMA_LLAMA("textures\\entity\\llama", "creamy", "llama", "1.11"),
    TEXTURES_ENTITY_LLAMA_BROWN("textures\\entity\\llama", "brown", "llama_brown", "1.11"),
    TEXTURES_ENTITY_LLAMA_CREAMY("textures\\entity\\llama", "creamy", "1.13"),
    TEXTURES_ENTITY_LLAMA_GRAY("textures\\entity\\llama", "gray", "llama_gray", "1.11"),
    TEXTURES_ENTITY_LLAMA_SPIT("textures\\entity\\llama", "spit", "1.11"),
    TEXTURES_ENTITY_LLAMA_WHITE("textures\\entity\\llama", "white", "llama_white", "1.11"),
    TEXTURES_ENTITY_PANDA_DIR("textures\\entity", "panda", "1.14"),
    TEXTURES_ENTITY_PANDA_AGGRESSIVE_PANDA("textures\\entity\\panda", "aggressive_panda", "1.14"),
    TEXTURES_ENTITY_PANDA_BROWN_PANDA("textures\\entity\\panda", "brown_panda", "1.14"),
    TEXTURES_ENTITY_PANDA_LAZY_PANDA("textures\\entity\\panda", "lazy_panda", "1.14"),
    TEXTURES_ENTITY_PANDA_PANDA("textures\\entity\\panda", "panda", "1.14"),
    TEXTURES_ENTITY_PANDA_PLAYFUL_PANDA("textures\\entity\\panda", "playful_panda", "1.14"),
    TEXTURES_ENTITY_PANDA_WEAK_PANDA("textures\\entity\\panda", "weak_panda", "1.14"),
    TEXTURES_ENTITY_PANDA_WORRIED_PANDA("textures\\entity\\panda", "worried_panda", "1.14"),
    TEXTURES_ENTITY_PARROT_DIR("textures\\entity", "parrot", "1.12"),
    TEXTURES_ENTITY_PARROT_PARROT_BLUE("textures\\entity\\parrot", "parrot_blue", "1.13"),
    TEXTURES_ENTITY_PARROT_PARROT_GREEN("textures\\entity\\parrot", "parrot_green", "1.13"),
    TEXTURES_ENTITY_PARROT_PARROT_GREY("textures\\entity\\parrot", "parrot_grey", "1.13"),
    TEXTURES_ENTITY_PARROT_PARROT_RED_BLUE("textures\\entity\\parrot", "parrot_red_blue", "1.13"),
    TEXTURES_ENTITY_PARROT_PARROT_YELLOW_BLUE("textures\\entity\\parrot", "parrot_yellow_blue", "1.13"),
    TEXTURES_ENTITY_PIG_DIR("textures\\entity", "pig", "1.6"),
    TEXTURES_ENTITY_PIG_PIG("textures\\entity\\pig", "pig", "1.6"),
    TEXTURES_ENTITY_PIG_PIG_SADDLE("textures\\entity\\pig", "pig_saddle", "1.6"),
    TEXTURES_ENTITY_PIGLIN_DIR("textures\\entity", "piglin", "1.16"),
    TEXTURES_ENTITY_PIGLIN_PIGLIN("textures\\entity\\piglin", "piglin", "1.16"),
    TEXTURES_ENTITY_PIGLIN_PIGLIN_BRUTE("textures\\entity\\piglin", "piglin_brute", "1.16"),
    TEXTURES_ENTITY_PIGLIN_ZOMBIFIED_PIGLIN("textures\\entity\\piglin", "zombified_piglin", "1.16"),
    TEXTURES_ENTITY_PROJECTILE_DIR("textures\\entity", "projectile", "1.9"),
    TEXTURES_ENTITY_PROJECTILE_ARROW("textures\\entity", "projectile\\arrow", "arrow", "1.6"),
    TEXTURES_ENTITY_PROJECTILE_SPECTRAL_ARROW("textures\\entity\\projectile", "spectral_arrow", "1.9"),
    TEXTURES_ENTITY_PROJECTILE_TIPPED_ARROW("textures\\entity\\projectile", "tipped_arrow", "1.9"),
    TEXTURES_ENTITY_RABBIT_DIR("textures\\entity", "rabbit", "1.8"),
    TEXTURES_ENTITY_RABBIT_BLACK("textures\\entity\\rabbit", "black", "1.8"),
    TEXTURES_ENTITY_RABBIT_BROWN("textures\\entity\\rabbit", "brown", "1.8"),
    TEXTURES_ENTITY_RABBIT_CAERBANNOG("textures\\entity\\rabbit", "caerbannot", "1.8"),
    TEXTURES_ENTITY_RABBIT_GOLD("textures\\entity\\rabbit", "gold", "1.8"),
    TEXTURES_ENTITY_RABBIT_SALT("textures\\entity\\rabbit", "salt", "1.8"),
    TEXTURES_ENTITY_RABBIT_TOAST("textures\\entity\\rabbit", "toast", "1.8"),
    TEXTURES_ENTITY_RABBIT_WHITE("textures\\entity\\rabbit", "white", "1.8"),
    TEXTURES_ENTITY_RABBIT_WHITE_SPLOTCHED("textures\\entity\\rabbit", "white_splotched", "1.8"),
    TEXTURES_ENTITY_SHEEP_DIR("textures\\entity", "sheep", "1.6"),
    TEXTURES_ENTITY_SHEEP_SHEEP("textures\\entity\\sheep", "sheep", "1.6"),
    TEXTURES_ENTITY_SHEEP_SHEEP_FUR("textures\\entity\\sheep", "sheep_fur", "1.6"),
    TEXTURES_ENTITY_SHIELD_DIR("textures\\entity", "shield", "1.9"),
    TEXTURES_ENTITY_SHIELD_BASE("textures\\entity\\shield", "base", "1.9"),
    TEXTURES_ENTITY_SHIELD_BORDER("textures\\entity\\shield", "border", "1.9"),
    TEXTURES_ENTITY_SHIELD_BRICKS("textures\\entity\\shield", "bricks", "1.9"),
    TEXTURES_ENTITY_SHIELD_CIRCLE("textures\\entity\\shield", "circle", "1.9"),
    TEXTURES_ENTITY_SHIELD_CREEPER("textures\\entity\\shield", "creeper", "1.9"),
    TEXTURES_ENTITY_SHIELD_CROSS("textures\\entity\\shield", "cross", "1.9"),
    TEXTURES_ENTITY_SHIELD_CURLY_BORDER("textures\\entity\\shield", "curly_border", "1.9"),
    TEXTURES_ENTITY_SHIELD_DIAGONAL_LEFT("textures\\entity\\shield", "diagonal_left", "1.9"),
    TEXTURES_ENTITY_SHIELD_DIAGONAL_RIGHT("textures\\entity\\shield", "diagonal_right", "1.9"),
    TEXTURES_ENTITY_SHIELD_DIAGONAL_UP_LEFT("textures\\entity\\shield", "diagonal_up_left", "1.9"),
    TEXTURES_ENTITY_SHIELD_DIAGONAL_UP_RIGHT("textures\\entity\\shield", "diagonal_up_right", "1.9"),
    TEXTURES_ENTITY_SHIELD_FLOWER("textures\\entity\\shield", "flower", "1.9"),
    TEXTURES_ENTITY_SHIELD_GLOBE("textures\\entity\\shield", "globe", "1.14"),
    TEXTURES_ENTITY_SHIELD_GRADIENT("textures\\entity\\shield", "gradient", "1.9"),
    TEXTURES_ENTITY_SHIELD_GRADIENT_UP("textures\\entity\\shield", "gradient_up", "1.9"),
    TEXTURES_ENTITY_SHIELD_HALF_HORIZONTAL("textures\\entity\\shield", "half_horizontal", "1.9"),
    TEXTURES_ENTITY_SHIELD_HALF_HORIZONTAL_BOTTOM("textures\\entity\\shield", "half_horizontal_bottom", "1.9"),
    TEXTURES_ENTITY_SHIELD_HALF_VERTICAL("textures\\entity\\shield", "half_vertical", "1.9"),
    TEXTURES_ENTITY_SHIELD_HALF_VERTICAL_RIGHT("textures\\entity\\shield", "half_vertical_right", "1.9"),
    TEXTURES_ENTITY_SHIELD_MOJANG("textures\\entity\\shield", "mojang", "1.9"),
    TEXTURES_ENTITY_SHIELD_PIGLIN("textures\\entity\\shield", "piglin", "1.16"),
    TEXTURES_ENTITY_SHIELD_RHOMBUS("textures\\entity\\shield", "rhombus", "1.9"),
    TEXTURES_ENTITY_SHIELD_SKULL("textures\\entity\\shield", "skull", "1.9"),
    TEXTURES_ENTITY_SHIELD_SMALL_STRIPES("textures\\entity\\shield", "small_stripes", "1.9"),
    TEXTURES_ENTITY_SHIELD_SQUARE_BOTTOM_LEFT("textures\\entity\\shield", "square_bottom_left", "1.9"),
    TEXTURES_ENTITY_SHIELD_SQUARE_BOTTOM_RIGHT("textures\\entity\\shield", "square_bottom_right", "1.9"),
    TEXTURES_ENTITY_SHIELD_SQUARE_TOP_LEFT("textures\\entity\\shield", "square_top_left", "1.9"),
    TEXTURES_ENTITY_SHIELD_SQUARE_TOP_RIGHT("textures\\entity\\shield", "square_top_right", "1.9"),
    TEXTURES_ENTITY_SHIELD_STRAIGHT_CROSS("textures\\entity\\shield", "straight_cross", "1.9"),
    TEXTURES_ENTITY_SHIELD_STRIPE_BOTTOM("textures\\entity\\shield", "stripe_bottom", "1.9"),
    TEXTURES_ENTITY_SHIELD_STRIPE_CENTER("textures\\entity\\shield", "stripe_center", "1.9"),
    TEXTURES_ENTITY_SHIELD_STRIPE_DOWNLEFT("textures\\entity\\shield", "stripe_downleft", "1.9"),
    TEXTURES_ENTITY_SHIELD_STRIPE_DOWNRIGHT("textures\\entity\\shield", "stripe_downright", "1.9"),
    TEXTURES_ENTITY_SHIELD_STRIPE_LEFT("textures\\entity\\shield", "stripe_left", "1.9"),
    TEXTURES_ENTITY_SHIELD_STRIPE_MIDDLE("textures\\entity\\shield", "stripe_middle", "1.9"),
    TEXTURES_ENTITY_SHIELD_STRIPE_RIGHT("textures\\entity\\shield", "stripe_right", "1.9"),
    TEXTURES_ENTITY_SHIELD_STRIPE_TOP("textures\\entity\\shield", "stripe_top", "1.9"),
    TEXTURES_ENTITY_SHIELD_TRIANGLE_BOTTOM("textures\\entity\\shield", "triangle_bottom", "1.9"),
    TEXTURES_ENTITY_SHIELD_TRIANGLE_TOP("textures\\entity\\shield", "triangle_top", "1.9"),
    TEXTURES_ENTITY_SHIELD_TRIANGLES_BOTTOM("textures\\entity\\shield", "triangles_bottom", "1.9"),
    TEXTURES_ENTITY_SHIELD_TRIANGLES_TOP("textures\\entity\\shield", "triangles_top", "1.9"),
    TEXTURES_ENTITY_SHULKER_DIR("textures\\entity", "shulker", "1.9"),
    TEXTURES_ENTITY_SHULKER_SHULKER("textures\\entity\\shulker", "endergolem", "shulker", "1.9"),
    TEXTURES_ENTITY_SHULKER_SHULKER_BLACK("textures\\entity\\shulker", "shulker_black", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_BLUE("textures\\entity\\shulker", "shulker_blue", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_BROWN("textures\\entity\\shulker", "shulker_brown", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_CYAN("textures\\entity\\shulker", "shulker_cyan", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_GRAY("textures\\entity\\shulker", "shulker_gray", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_GREEN("textures\\entity\\shulker", "shulker_green", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_LIGHT_BLUE("textures\\entity\\shulker", "shulker_light_blue", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_LIGHT_GRAY("textures\\entity\\shulker", "shulker_light_gray", "shulker_silver", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_LIME("textures\\entity\\shulker", "shulker_lime", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_MAGENTA("textures\\entity\\shulker", "shulker_magenta", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_ORANGE("textures\\entity\\shulker", "shulker_orange", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_PINK("textures\\entity\\shulker", "shulker_pink", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_PURPLE("textures\\entity\\shulker", "shulker_purple", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_RED("textures\\entity\\shulker", "shulker_red", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_WHITE("textures\\entity\\shulker", "shulker_white", "1.11"),
    TEXTURES_ENTITY_SHULKER_SHULKER_YELLOW("textures\\entity\\shulker", "shulker_yellow", "1.11"),
    TEXTURES_ENTITY_SHULKER_SPARK("textures\\entity\\shulker", "spark", "1.9"),
    TEXTURES_ENTITY_SIGNS_DIR("textures\\entity", "signs", "1.14"),
    TEXTURES_ENTITY_SIGNS_ACACIA("textures\\entity\\signs", "acacia", "1.14"),
    TEXTURES_ENTITY_SIGNS_BIRCH("textures\\entity\\signs", "birch", "1.14"),
    TEXTURES_ENTITY_SIGNS_CRIMSON("textures\\entity\\signs", "crimson", "1.16"),
    TEXTURES_ENTITY_SIGNS_DARK_OAK("textures\\entity\\signs", "dark_oak", "1.14"),
    TEXTURES_ENTITY_SIGNS_JUNGLE("textures\\entity\\signs", "jungle", "1.14"),
    TEXTURES_ENTITY_SIGNS_MANGROVE("textures\\entity\\signs", "mangrove", "1.19"),
    TEXTURES_ENTITY_SIGNS_OAK("textures\\entity", "signs\\oak", "sign", "1.6"),
    TEXTURES_ENTITY_SIGNS_SPRUCE("textures\\entity\\signs", "acacia", "1.14"),
    TEXTURES_ENTITY_SIGNS_WARPED("textures\\entity\\signs", "acacia", "1.16"),
    TEXTURES_ENTITY_SKELETON_DIR("textures\\entity", "skeleton", "1.6"),
    TEXTURES_ENTITY_SKELETON_SKELETON("textures\\entity\\skeleton", "skeleton", "1.6"),
    TEXTURES_ENTITY_SKELETON_STRAY("textures\\entity\\skeleton", "stray", "1.10"),
    TEXTURES_ENTITY_SKELETON_STRAY_OVERLAY("textures\\entity\\skeleton", "stray_overlay", "1.10"),
    TEXTURES_ENTITY_SKELETON_WITHER_SKELETON("textures\\entity\\skeleton", "wither_skeleton", "1.6"),
    TEXTURES_ENTITY_SLIME_DIR("textures\\entity", "slime", "1.6"),
    TEXTURES_ENTITY_SLIME_MAGMACUBE("textures\\entity\\slime", "magmacube", "1.6"),
    TEXTURES_ENTITY_SLIME_SLIME("textures\\entity\\slime", "slime", "1.6"),
    TEXTURES_ENTITY_SPIDER_DIR("textures\\entity", "spider", "1.6"),
    TEXTURES_ENTITY_SPIDER_CAVE_SPIDER("textures\\entity\\spider", "cave_spider", "1.6"),
    TEXTURES_ENTITY_SPIDER_SPIDER("textures\\entity\\spider", "spider", "1.6"),
    TEXTURES_ENTITY_SQUID_DIR("textures\\entity", "squid", "1.17"),
    TEXTURES_ENTITY_SQUID_GLOW_SQUID("textures\\entity\\squid", "glow_squid", "1.17"),
    TEXTURES_ENTITY_SQUID_SQUID("textures\\entity", "squid\\squid", "squid", "1.6"),
    TEXTURES_ENTITY_STRIDER_DIR("textures\\entity", "strider", "1.16"),
    TEXTURES_ENTITY_STRIDER_STRIDER("textures\\entity\\strider", "strider", "1.16"),
    TEXTURES_ENTITY_STRIDER_STRIDER_COLD("textures\\entity\\strider", "strider_cold", "1.16"),
    TEXTURES_ENTITY_STRIDER_STRIDER_SADDLE("textures\\entity\\strider", "strider_saddle", "1.16"),
    TEXTURES_ENTITY_TADPOLE_DIR("textures\\entity", "tadpole", "1.19"),
    TEXTURES_ENTITY_TADPOLE_TADPOLE("textures\\entity\\tadpole", "tadpole", "1.19"),
    TEXTURES_ENTITY_TURTLE_DIR("textures\\entity", "turtle", "1.13"),
    TEXTURES_ENTITY_TURTLE_BIG_SEA_TURTLE("textures\\entity\\turtle", "big_sea_turtle", "1.13"),
    TEXTURES_ENTITY_VILLAGER_DIR("textures\\entity", "villager", "1.6"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION("textures\\entity\\villager", "profession", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_ARMORER("textures\\entity\\villager\\profession", "armorer", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_BUTCHER("textures\\entity\\villager\\profession", "butcher", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_CARTOGRAPHER("textures\\entity\\villager\\profession", "cartographer", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_CLERIC("textures\\entity\\villager\\profession", "cleric", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_FARMER("textures\\entity\\villager\\profession", "farmer", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_FISHERMAN("textures\\entity\\villager\\profession", "fisherman", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_FLETCHER("textures\\entity\\villager\\profession", "fletcher", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_LEATHERWORKER("textures\\entity\\villager\\profession", "leatherworker", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_LIBRARIAN("textures\\entity\\villager\\profession", "librarian", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_MASON("textures\\entity\\villager\\profession", "mason", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_NITWIT("textures\\entity\\villager\\profession", "nitwit", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_SHEPHERD("textures\\entity\\villager\\profession", "shepherd", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_TOOLSMITH("textures\\entity\\villager\\profession", "toolsmith", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_WEAPONSMITH("textures\\entity\\villager\\profession", "weaponsmith", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_LEVEL("textures\\entity\\villager", "profession_level", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_LEVEL_DIAMOND("textures\\entity\\villager\\profession_level", "diamond", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_LEVEL_EMERALD("textures\\entity\\villager\\profession_level", "emerald", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_LEVEL_GOLD("textures\\entity\\villager\\profession_level", "gold", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_LEVEL_IRON("textures\\entity\\villager\\profession_level", "iron", "1.14"),
    TEXTURES_ENTITY_VILLAGER_PROFESSION_LEVEL_STONE("textures\\entity\\villager\\profession_level", "stone", "1.14"),
    TEXTURES_ENTITY_VILLAGER_TYPE("textures\\entity\\villager", "type", "1.14"),
    TEXTURES_ENTITY_VILLAGER_TYPE_DESERT("textures\\entity\\villager\\type", "desert", "1.14"),
    TEXTURES_ENTITY_VILLAGER_TYPE_JUNGLE("textures\\entity\\villager\\type", "jungle", "1.14"),
    TEXTURES_ENTITY_VILLAGER_TYPE_PLAINS("textures\\entity\\villager\\type", "plains", "1.14"),
    TEXTURES_ENTITY_VILLAGER_TYPE_SAVANNA("textures\\entity\\villager\\type", "savanna", "1.14"),
    TEXTURES_ENTITY_VILLAGER_TYPE_SNOW("textures\\entity\\villager\\type", "snow", "1.14"),
    TEXTURES_ENTITY_VILLAGER_TYPE_SWAMP("textures\\entity\\villager\\type", "swamp", "1.14"),
    TEXTURES_ENTITY_VILLAGER_TYPE_TAIGA("textures\\entity\\villager\\type", "taiga", "1.14"),
    TEXTURES_ENTITY_VILLAGER_VILLAGER("textures\\entity\\villager", "villager", "1.14"),
    TEXTURES_ENTITY_VILLAGEROLD_DIR("textures\\entity\\villager", "old", "1.14"),
    TEXTURES_ENTITY_VILLAGEROLD_BUTCHER("textures\\entity\\villager", "butcher", "old\\butcher", "1.6"),
    TEXTURES_ENTITY_VILLAGEROLD_FARMER("textures\\entity\\villager", "farmer", "old\\farmer", "1.6"),
    TEXTURES_ENTITY_VILLAGEROLD_LIBRARIAN("textures\\entity\\villager", "librarian", "old\\librarian", "1.6"),
    TEXTURES_ENTITY_VILLAGEROLD_PRIEST("textures\\entity\\villager", "priest", "old\\priest", "1.6"),
    TEXTURES_ENTITY_VILLAGEROLD_SMITH("textures\\entity\\villager", "smith", "old\\smith", "1.6"),
    TEXTURES_ENTITY_VILLAGEROLD_VILLAGER("textures\\entity\\villager", "villager", "old\\villager", "1.6"),
    TEXTURES_ENTITY_WARDEN_DIR("textures\\entity", "warden", "1.19"),
    TEXTURES_ENTITY_WARDEN_WARDEN_BIOLUMINESCENT_LAYER("textures\\entity\\warden", "warden_bioluminiscent_layer", "1.19"),
    TEXTURES_ENTITY_WARDEN_WARDEN_HEART("textures\\entity\\warden", "warden_heart", "1.19"),
    TEXTURES_ENTITY_WARDEN_WARDEN_PULSATING_SPOTS_1("textures\\entity\\warden", "warden_pulsating_spots_1", "1.19"),
    TEXTURES_ENTITY_WARDEN_WARDEN_PULSATING_SPOTS_2("textures\\entity\\warden", "warden_pulsating_spots_2", "1.19"),
    TEXTURES_ENTITY_WITHER_DIR("textures\\entity", "wither", "1.6"),
    TEXTURES_ENTITY_WITHER_WITHER("textures\\entity\\wither", "wither", "1.6"),
    TEXTURES_ENTITY_WITHER_WITHER_ARMOR("textures\\entity\\wither", "wither_armor", "1.6"),
    TEXTURES_ENTITY_WITHER_WITHER_INVULNERABLE("textures\\entity\\wither", "wither_invulnerable", "1.6"),
    TEXTURES_ENTITY_WOLF_DIR("textures\\entity", "wolf", "1.6"),
    TEXTURES_ENTITY_WOLF_WOLF("textures\\entity\\wolf", "wolf", "1.6"),
    TEXTURES_ENTITY_WOLF_WOLF_ANGRY("textures\\entity\\wolf", "wolf_angry", "1.6"),
    TEXTURES_ENTITY_WOLF_WOLF_COLLAR("textures\\entity\\wolf", "wolf_collar", "1.6"),
    TEXTURES_ENTITY_WOLF_WOLF_TAME("textures\\entity\\wolf", "wolf_tame", "1.6"),
    TEXTURES_ENTITY_ZOMBIE_DIR("textures\\entity", "zombie", "1.6"),
    TEXTURES_ENTITY_ZOMBIE_DROWNED("textures\\entity\\zombie", "drowned", "1.13"),
    TEXTURES_ENTITY_ZOMBIE_DROWNED_OUTER_LAYER("textures\\entity\\zombie", "drowned_outer_layer", "1.13"),
    TEXTURES_ENTITY_ZOMBIE_HUSK("textures\\entity\\zombie", "husk", "1.10"),
    TEXTURES_ENTITY_ZOMBIE_ZOMBIE("textures\\entity\\zombie", "zombie", "1.6"),
    TEXTURES_ENTITY_ZOMBIE_ZOMBIE_VILLAGER("textures\\entity\\zombie_villager", "zombie_villager", "1.6"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_DIR("textures\\entity", "villager", "1.9"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION("textures\\entity\\zombie_villager", "profession", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_ARMORER("textures\\entity\\zombie_villager\\profession", "armorer", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_BUTCHER("textures\\entity\\zombie_villager\\profession", "butcher", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_CARTOGRAPHER("textures\\entity\\zombie_villager\\profession", "cartographer", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_CLERIC("textures\\entity\\zombie_villager\\profession", "cleric", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_FARMER("textures\\entity\\zombie_villager\\profession", "farmer", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_FISHERMAN("textures\\entity\\zombie_villager\\profession", "fisherman", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_FLETCHER("textures\\entity\\zombie_villager\\profession", "fletcher", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_LEATHERWORKER("textures\\entity\\zombie_villager\\profession", "leatherworker", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_LIBRARIAN("textures\\entity\\zombie_villager\\profession", "librarian", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_MASON("textures\\entity\\zombie_villager\\profession", "mason", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_NITWIT("textures\\entity\\zombie_villager\\profession", "nitwit", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_SHEPHERD("textures\\entity\\zombie_villager\\profession", "shepherd", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_TOOLSMITH("textures\\entity\\zombie_villager\\profession", "toolsmith", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_WEAPONSMITH("textures\\entity\\zombie_villager\\profession", "weaponsmith", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_LEVEL("textures\\entity\\zombie_villager", "profession_level", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_LEVEL_DIAMOND("textures\\entity\\zombie_villager\\profession_level", "diamond", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_LEVEL_EMERALD("textures\\entity\\zombie_villager\\profession_level", "emerald", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_LEVEL_GOLD("textures\\entity\\zombie_villager\\profession_level", "gold", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_LEVEL_IRON("textures\\entity\\zombie_villager\\profession_level", "iron", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_PROFESSION_LEVEL_STONE("textures\\entity\\zombie_villager\\profession_level", "stone", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_TYPE("textures\\entity\\zombie_villager", "type", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_TYPE_DESERT("textures\\entity\\zombie_villager\\type", "desert", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_TYPE_JUNGLE("textures\\entity\\zombie_villager\\type", "jungle", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_TYPE_PLAINS("textures\\entity\\zombie_villager\\type", "plains", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_TYPE_SAVANNA("textures\\entity\\zombie_villager\\type", "savanna", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_TYPE_SNOW("textures\\entity\\zombie_villager\\type", "snow", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_TYPE_SWAMP("textures\\entity\\zombie_villager\\type", "swamp", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGER_TYPE_TAIGA("textures\\entity\\zombie_villager\\type", "taiga", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGEROLD_DIR("textures\\entity\\zombie_villager", "old", "1.14"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGEROLD_BUTCHER("textures\\entity\\zombie_illager", "zombie_butcher", "old\\zombie_butcher", "1.9"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGEROLD_FARMER("textures\\entity\\zombie_villager", "zombie_farmer", "old\\zombie_farmer", "1.9"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGEROLD_LIBRARIAN("textures\\entity\\zombie_villager", "zombie_librarian", "old\\zombie_librarian", "1.9"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGEROLD_PRIEST("textures\\entity\\zombie_villager", "zombie_priest", "old\\zombie_priest", "1.9"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGEROLD_SMITH("textures\\entity\\zombie_villager", "zombie_smith", "old\\zombie_smith", "1.9"),
    TEXTURES_ENTITY_ZOMBIE_VILLAGEROLD_VILLAGER("textures\\entity\\zombie_villager", "zombie_villager", "old\\zombie_villager", "1.9"),
    TEXTURES_ENTITYPNG_ALEX("textures\\entity", "alex", "1.8"),
    TEXTURES_ENTITYPNG_BANNER_BASE("textures\\entity", "banner_base", "1.8"),
    TEXTURES_ENTITYPNG_BAT("textures\\entity", "bat", "1.6"),
    TEXTURES_ENTITYPNG_BEACON_BEAM("textures\\entity", "beacon_beam", "1.6"),
    TEXTURES_ENTITYPNG_BLAZE("textures\\entity", "blaze", "1.6"),
    TEXTURES_ENTITYPNG_BOAT("textures\\entity", "boat", "1.6"),
    TEXTURES_ENTITYPNG_CHICKEN("textures\\entity", "chicken", "1.6"),
    TEXTURES_ENTITYPNG_DOLPHIN("textures\\entity", "dolphin", "1.13"),
    TEXTURES_ENTITYPNG_ELYTRA("textures\\entity", "elytra", "1.9"),
    TEXTURES_ENTITYPNG_ENCHANTING_TABLE_BOOK("textures\\entity", "enchanting_table_book", "1.6"),
    TEXTURES_ENTITYPNG_END_GATEWAY_BEAM("textures\\entity", "end_gateway_beam", "1.9"),
    TEXTURES_ENTITYPNG_END_PORTAL("textures\\entity", "end_portal", "1.6"),
    TEXTURES_ENTITYPNG_ENDERMITE("textures\\entity", "endermite", "1.8"),
    TEXTURES_ENTITYPNG_EXPERIENCE_ORB("textures\\entity", "experience_orb", "1.6"),
    TEXTURES_ENTITYPNG_EXPLOSION("textures\\entity", "explosion", "1.6"),
    TEXTURES_ENTITYPNG_FISHING_HOOK("textures\\entity", "fishing_hook", "1.14"),
    TEXTURES_ENTITYPNG_GUARDIAN("textures\\entity", "guardian", "1.8"),
    TEXTURES_ENTITYPNG_GUARDIAN_BEAM("textures\\entity", "guardian_beam", "1.8"),
    TEXTURES_ENTITYPNG_GUARDIAN_ELDER("textures\\entity", "guardian_elder", "1.8"),
    TEXTURES_ENTITYPNG_LEAD_KNOT("textures\\entity", "lead_knot", "1.6"),
    TEXTURES_ENTITYPNG_MINECART("textures\\entity", "minecart", "1.6"),
    TEXTURES_ENTITYPNG_PHANTOM("textures\\entity","phantom", "1.13"),
    TEXTURES_ENTITYPNG_PHANTOM_EYES("textures\\entity", "phantom_eyes", "1.13"),
    TEXTURES_ENTITYPNG_SHIELD_BASE("textures\\entity", "shield_base", "1.9"),
    TEXTURES_ENTITYPNG_SHIELD_BASE_NOPATTERN("textures\\entity", "shield_base_nopattern", "1.9"),
    TEXTURES_ENTITYPNG_SILVERFISH("textures\\entity", "silverfish", "1.6"),
    TEXTURES_ENTITYPNG_SNOW_GOLEM("textures\\entity", "snow_golem", "snowman", "1.6"),
    TEXTURES_ENTITYPNG_SPIDER_EYES("textures\\entity", "spider_eyes", "1.6"),
    TEXTURES_ENTITYPNG_STEVE("textures\\entity", "steve", "1.6"),
    TEXTURES_ENTITYPNG_TRIDENT("textures\\entity", "trident", "1.13"),
    TEXTURES_ENTITYPNG_TRIDENT_RIPTIDE("textures\\entity", "trident_riptide", "1.13"),
    TEXTURES_ENTITYPNG_WANDERING_TRADER("textures\\entity", "wandering_trader", "1.14"),
    TEXTURES_ENTITYPNG_WITCH("textures\\entity", "witch", "1.6");

    Entity(String dir, String nameNew, String nameOld, String introducedVersion) {
        this.dir = dir;
        this.nameNew = nameNew;
        this.nameOld = nameOld;
        this.introducedVersion = introducedVersion;
    }

    Entity(String dir, String nameNew, String introducedVersion) {
        this.dir = dir;
        this.nameNew = nameNew;
        this.nameOld = nameNew;
        this.introducedVersion = introducedVersion;
    }



    private final String dir;
    private final String nameNew;
    private final String nameOld;
    private final String introducedVersion;

    @Override
    public String getDirectory() {
        return dir;
    }

    @Override
    public String getNewerName() {
        return nameNew;
    }

    @Override
    public String getOlderNames() {
        return nameOld;
    }

    @Override
    public String getIntroducedVersion() {
        return introducedVersion;
    }
}
