package me.bruno.packbuilder.enums.texture;

import me.bruno.packbuilder.enums.Files;

public enum Font implements Files {
    // textures/font

    TEXTURES_FONT_ACCENTED("textures\\font", "accented", "1.13"),
    TEXTURES_FONT_ASCII("textures\\font", "ascii", "1.6"),
    TEXTURES_FONT_ASCII_SGA("textures\\font", "ascii_sga", "1.6"),
    TEXTURES_FONT_ASCIILLAGER("textures\\font", "asciillager", "1.18"),
    TEXTURES_FONT_NONLATIN_EUROPEAN("textures\\font", "nonlatin_european", "1.13"),
    TEXTURES_FONT_UNICODE_PAGE_00("textures\\font", "unicode_page_00", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_0A("textures\\font", "unicode_page_0a", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_0B("textures\\font", "unicode_page_0b", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_0C("textures\\font", "unicode_page_0c", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_0D("textures\\font", "unicode_page_0d", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_0E("textures\\font", "unicode_page_0e", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_0F("textures\\font", "unicode_page_0f", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_01("textures\\font", "unicode_page_01", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_1A("textures\\font", "unicode_page_1a", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_1B("textures\\font", "unicode_page_1b", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_1C("textures\\font", "unicode_page_1c", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_1D("textures\\font", "unicode_page_1d", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_1E("textures\\font", "unicode_page_1e", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_1F("textures\\font", "unicode_page_1f", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_02("textures\\font", "unicode_page_02", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_2A("textures\\font", "unicode_page_2a", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_2B("textures\\font", "unicode_page_2b", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_2C("textures\\font", "unicode_page_2c", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_2D("textures\\font", "unicode_page_2d", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_2E("textures\\font", "unicode_page_2e", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_2F("textures\\font", "unicode_page_2f", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_03("textures\\font", "unicode_page_03", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_3A("textures\\font", "unicode_page_3a", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_3B("textures\\font", "unicode_page_3b", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_3C("textures\\font", "unicode_page_3c", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_3D("textures\\font", "unicode_page_3d", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_3E("textures\\font", "unicode_page_3e", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_3F("textures\\font", "unicode_page_3f", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_04("textures\\font", "unicode_page_04", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_4A("textures\\font", "unicode_page_4a", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_4B("textures\\font", "unicode_page_4b", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_4C("textures\\font", "unicode_page_4c", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_4D("textures\\font", "unicode_page_4d", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_4E("textures\\font", "unicode_page_4e", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_4F("textures\\font", "unicode_page_4f", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_05("textures\\font", "unicode_page_05", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_5A("textures\\font", "unicode_page_5a", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_5B("textures\\font", "unicode_page_5b", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_5C("textures\\font", "unicode_page_5c", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_5D("textures\\font", "unicode_page_5d", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_5E("textures\\font", "unicode_page_5e", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_5F("textures\\font", "unicode_page_5f", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_06("textures\\font", "unicode_page_06", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_6A("textures\\font", "unicode_page_6a", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_6B("textures\\font", "unicode_page_6b", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_6C("textures\\font", "unicode_page_6c", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_6D("textures\\font", "unicode_page_6d", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_6E("textures\\font", "unicode_page_6e", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_6F("textures\\font", "unicode_page_6f", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_07("textures\\font", "unicode_page_07", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_7A("textures\\font", "unicode_page_7a", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_7B("textures\\font", "unicode_page_7b", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_7C("textures\\font", "unicode_page_7c", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_7D("textures\\font", "unicode_page_7d", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_7E("textures\\font", "unicode_page_7e", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_7F("textures\\font", "unicode_page_7f", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_08("textures\\font", "unicode_page_08", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_8A("textures\\font", "unicode_page_8a", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_8B("textures\\font", "unicode_page_8b", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_8C("textures\\font", "unicode_page_8c", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_8D("textures\\font", "unicode_page_8d", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_8E("textures\\font", "unicode_page_8e", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_8F("textures\\font", "unicode_page_8f", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_09("textures\\font", "unicode_page_09", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_9A("textures\\font", "unicode_page_9a", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_9B("textures\\font", "unicode_page_9b", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_9C("textures\\font", "unicode_page_9c", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_9D("textures\\font", "unicode_page_9d", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_9E("textures\\font", "unicode_page_9e", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_9F("textures\\font", "unicode_page_9f", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_10("textures\\font", "unicode_page_10", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_11("textures\\font", "unicode_page_11", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_12("textures\\font", "unicode_page_12", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_13("textures\\font", "unicode_page_13", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_14("textures\\font", "unicode_page_14", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_15("textures\\font", "unicode_page_15", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_16("textures\\font", "unicode_page_16", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_17("textures\\font", "unicode_page_17", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_18("textures\\font", "unicode_page_18", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_19("textures\\font", "unicode_page_19", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_20("textures\\font", "unicode_page_20", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_21("textures\\font", "unicode_page_21", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_22("textures\\font", "unicode_page_22", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_23("textures\\font", "unicode_page_23", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_24("textures\\font", "unicode_page_24", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_25("textures\\font", "unicode_page_25", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_26("textures\\font", "unicode_page_26", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_27("textures\\font", "unicode_page_27", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_28("textures\\font", "unicode_page_28", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_29("textures\\font", "unicode_page_29", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_30("textures\\font", "unicode_page_30", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_31("textures\\font", "unicode_page_31", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_32("textures\\font", "unicode_page_32", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_33("textures\\font", "unicode_page_33", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_34("textures\\font", "unicode_page_34", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_35("textures\\font", "unicode_page_35", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_36("textures\\font", "unicode_page_36", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_37("textures\\font", "unicode_page_37", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_38("textures\\font", "unicode_page_38", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_39("textures\\font", "unicode_page_39", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_40("textures\\font", "unicode_page_40", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_41("textures\\font", "unicode_page_41", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_42("textures\\font", "unicode_page_42", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_43("textures\\font", "unicode_page_43", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_44("textures\\font", "unicode_page_44", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_45("textures\\font", "unicode_page_45", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_46("textures\\font", "unicode_page_46", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_47("textures\\font", "unicode_page_47", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_48("textures\\font", "unicode_page_48", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_49("textures\\font", "unicode_page_49", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_50("textures\\font", "unicode_page_50", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_51("textures\\font", "unicode_page_51", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_52("textures\\font", "unicode_page_52", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_53("textures\\font", "unicode_page_53", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_54("textures\\font", "unicode_page_54", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_55("textures\\font", "unicode_page_55", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_56("textures\\font", "unicode_page_56", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_57("textures\\font", "unicode_page_57", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_58("textures\\font", "unicode_page_58", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_59("textures\\font", "unicode_page_59", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_60("textures\\font", "unicode_page_60", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_61("textures\\font", "unicode_page_61", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_62("textures\\font", "unicode_page_62", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_63("textures\\font", "unicode_page_63", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_64("textures\\font", "unicode_page_64", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_65("textures\\font", "unicode_page_65", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_66("textures\\font", "unicode_page_66", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_67("textures\\font", "unicode_page_67", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_68("textures\\font", "unicode_page_68", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_69("textures\\font", "unicode_page_69", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_70("textures\\font", "unicode_page_70", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_71("textures\\font", "unicode_page_71", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_72("textures\\font", "unicode_page_72", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_73("textures\\font", "unicode_page_73", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_74("textures\\font", "unicode_page_74", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_75("textures\\font", "unicode_page_75", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_76("textures\\font", "unicode_page_76", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_77("textures\\font", "unicode_page_77", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_78("textures\\font", "unicode_page_78", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_79("textures\\font", "unicode_page_79", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_80("textures\\font", "unicode_page_80", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_81("textures\\font", "unicode_page_81", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_82("textures\\font", "unicode_page_82", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_83("textures\\font", "unicode_page_83", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_84("textures\\font", "unicode_page_84", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_85("textures\\font", "unicode_page_85", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_86("textures\\font", "unicode_page_86", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_87("textures\\font", "unicode_page_87", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_88("textures\\font", "unicode_page_88", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_89("textures\\font", "unicode_page_89", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_90("textures\\font", "unicode_page_90", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_91("textures\\font", "unicode_page_91", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_92("textures\\font", "unicode_page_92", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_93("textures\\font", "unicode_page_93", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_94("textures\\font", "unicode_page_94", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_95("textures\\font", "unicode_page_95", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_96("textures\\font", "unicode_page_96", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_97("textures\\font", "unicode_page_97", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_98("textures\\font", "unicode_page_98", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_99("textures\\font", "unicode_page_99", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_A0("textures\\font", "unicode_page_a0", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_A1("textures\\font", "unicode_page_a1", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_A2("textures\\font", "unicode_page_a2", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_A3("textures\\font", "unicode_page_a3", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_A4("textures\\font", "unicode_page_a4", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_A5("textures\\font", "unicode_page_a5", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_A6("textures\\font", "unicode_page_a6", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_A7("textures\\font", "unicode_page_a7", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_A8("textures\\font", "unicode_page_a8", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_A9("textures\\font", "unicode_page_a9", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_AA("textures\\font", "unicode_page_aa", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_AB("textures\\font", "unicode_page_ab", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_AC("textures\\font", "unicode_page_ac", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_AD("textures\\font", "unicode_page_ad", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_AE("textures\\font", "unicode_page_ae", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_AF("textures\\font", "unicode_page_af", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_B0("textures\\font", "unicode_page_b0", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_B1("textures\\font", "unicode_page_b1", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_B2("textures\\font", "unicode_page_b2", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_B3("textures\\font", "unicode_page_b3", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_B4("textures\\font", "unicode_page_b4", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_B5("textures\\font", "unicode_page_b5", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_B6("textures\\font", "unicode_page_b6", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_B7("textures\\font", "unicode_page_b7", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_B8("textures\\font", "unicode_page_b8", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_B9("textures\\font", "unicode_page_b9", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_BA("textures\\font", "unicode_page_ba", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_BB("textures\\font", "unicode_page_bb", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_BC("textures\\font", "unicode_page_bc", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_BD("textures\\font", "unicode_page_bd", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_BE("textures\\font", "unicode_page_be", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_BF("textures\\font", "unicode_page_bf", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_C0("textures\\font", "unicode_page_c0", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_C1("textures\\font", "unicode_page_c1", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_C2("textures\\font", "unicode_page_c2", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_C3("textures\\font", "unicode_page_c3", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_C4("textures\\font", "unicode_page_c4", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_C5("textures\\font", "unicode_page_c5", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_C6("textures\\font", "unicode_page_c6", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_C7("textures\\font", "unicode_page_c7", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_C8("textures\\font", "unicode_page_c8", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_C9("textures\\font", "unicode_page_c9", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_CA("textures\\font", "unicode_page_ca", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_CB("textures\\font", "unicode_page_cb", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_CC("textures\\font", "unicode_page_cc", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_CD("textures\\font", "unicode_page_cd", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_CE("textures\\font", "unicode_page_ce", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_CF("textures\\font", "unicode_page_cf", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_D0("textures\\font", "unicode_page_d0", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_D1("textures\\font", "unicode_page_d1", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_D2("textures\\font", "unicode_page_d2", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_D3("textures\\font", "unicode_page_d3", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_D4("textures\\font", "unicode_page_d4", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_D5("textures\\font", "unicode_page_d5", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_D6("textures\\font", "unicode_page_d6", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_D7("textures\\font", "unicode_page_d7", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_F9("textures\\font", "unicode_page_f9", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_FA("textures\\font", "unicode_page_fa", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_FB("textures\\font", "unicode_page_fb", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_FC("textures\\font", "unicode_page_fc", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_FD("textures\\font", "unicode_page_fd", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_FE("textures\\font", "unicode_page_fe", "1.6"),
    TEXTURES_FONT_UNICODE_PAGE_FF("textures\\font", "unicode_page_ff", "1.6");



    Font(String dir, String nameNew, String nameOld, String introducedVersion) {
        this.dir = dir;
        this.nameNew = nameNew;
        this.nameOld = nameOld;
        this.introducedVersion = introducedVersion;
    }

    Font(String dir, String nameNew, String introducedVersion) {
        this.dir = dir;
        this.nameNew = nameNew;
        this.nameOld = nameNew;
        this.introducedVersion = introducedVersion;
    }



    private final String dir;
    private final String nameNew;
    private final String nameOld;
    private final String introducedVersion;

    @Override
    public String getDirectory() {
        return dir;
    }

    @Override
    public String getNewerName() {
        return nameNew;
    }

    @Override
    public String getOlderNames() {
        return nameOld;
    }

    @Override
    public String getIntroducedVersion() {
        return introducedVersion;
    }
}
