package me.bruno.packbuilder.enums.texture;

import me.bruno.packbuilder.enums.Files;

public enum Item implements Files {

    // textures/item

    TEXTURES_ITEM_ACACIA_BOAT("textures\\item", "acacia_boat", "1.9"),
    TEXTURES_ITEM_ACACIA_CHEST_BOAT("textures\\item", "acacia_chest_boat", "1.19"),
    TEXTURES_ITEM_ACACIA_DOOR("textures\\item", "acacia_door", "door_acacia", "1.8"),
    TEXTURES_ITEM_ACACIA_SIGN("textures\\item", "acacia_sign", "1.14"),
    TEXTURES_ITEM_AMETHYST_SHARD("textures\\item", "amethyst_shard", "1.17"),
    TEXTURES_ITEM_APPLE("textures\\item", "apple", "1.6"),
    TEXTURES_ITEM_ARMOR_STAND("textures\\item", "armor_stand", "wooden_armorstand", "1.8"),
    TEXTURES_ITEM_ARROW("textures\\item", "arrow", "1.6"),
    TEXTURES_ITEM_AXOLOTL_BUCKET("textures\\item", "axolotl_bucket", "1.17"),
    TEXTURES_ITEM_BAKED_POTATO("textures\\item", "baked_potato", "potato_baked", "1.6"),
    TEXTURES_ITEM_BAMBOO("textures\\item", "bamboo", "1.14"),
    TEXTURES_ITEM_BARRIER("textures\\item", "barrier", "1.8"),
    TEXTURES_ITEM_BEEF("textures\\item", "beef", "beef_raw", "1.6"),
    TEXTURES_ITEM_BEETROOT("textures\\item", "beetroot", "1.9"),
    TEXTURES_ITEM_BEETROOT_SEEDS("textures\\item", "beetroot_seeds", "1.9"),
    TEXTURES_ITEM_BEETROOT_SOUP("textures\\item", "beetroot_soup", "1.9"),
    TEXTURES_ITEM_BELL("textures\\item", "bell", "1.14"),
    TEXTURES_ITEM_BIRCH_BOAT("textures\\item", "birch_boat", "1.9"),
    TEXTURES_ITEM_BIRCH_CHEST_BOAT("textures\\item", "birch_chest_boat", "1.19"),
    TEXTURES_ITEM_BIRCH_DOOR("textures\\item", "birch_door", "door_birch", "1.8"),
    TEXTURES_ITEM_BIRCH_SIGN("textures\\item", "birch_sign", "1.14"),
    TEXTURES_ITEM_BLACK_CANDLE("textures\\item", "black_candle", "1.17"),
    TEXTURES_ITEM_BLACK_DYE("textures\\item", "black_dye", "1.14"),
    TEXTURES_ITEM_BLAZE_POWDER("textures\\item", "blaze_powder", "1.6"),
    TEXTURES_ITEM_BLAZE_ROD("textures\\item", "blaze_rod", "1.6"),
    TEXTURES_ITEM_BLUE_CANDLE("textures\\item", "blue_candle", "1.17"),
    TEXTURES_ITEM_BLUE_DYE("textures\\item", "blue_dye", "1.14"),
    TEXTURES_ITEM_BONE("textures\\item", "bone", "1.6"),
    TEXTURES_ITEM_BONE_MEAL("textures\\item", "bone_meal", "dye_powder_white", "1.6"),
    TEXTURES_ITEM_BOOK("textures\\item", "book", "book_normal", "1.6"),
    TEXTURES_ITEM_BOW("textures\\item", "bow", "bow_standby", "1.6"),
    TEXTURES_ITEM_BOW_PULLING_0("textures\\item", "bow_pulling_0", "1.6"),
    TEXTURES_ITEM_BOW_PULLING_1("textures\\item", "bow_pulling_1", "1.6"),
    TEXTURES_ITEM_BOW_PULLING_2("textures\\item", "bow_pulling_2", "1.6"),
    TEXTURES_ITEM_BOWL("textures\\item", "bowl", "1.6"),
    TEXTURES_ITEM_BREAD("textures\\item", "bread", "1.6"),
    TEXTURES_ITEM_BREWING_STAND("textures\\item", "brewing_stand", "1.6"),
    TEXTURES_ITEM_BRICK("textures\\item", "brick", "1.6"),
    TEXTURES_ITEM_BROKEN_ELYTRA("textures\\item", "broken_elytra", "1.9"),
    TEXTURES_ITEM_BROWN_CANDLE("textures\\item", "brown_candle", "1.17"),
    TEXTURES_ITEM_BROWN_DYE("textures\\item", "brown_dye", "1.14"),
    TEXTURES_ITEM_BUCKET("textures\\item", "bucket", "bucket_empty", "1.6"),
    TEXTURES_ITEM_BUNDLE("textures\\item", "bundle", "1.17"),
    TEXTURES_ITEM_BUNDLE_FILLED("textures\\item", "bundle_filled", "1.17"),
    TEXTURES_ITEM_CAKE("textures\\item", "cake", "1.6"),
    TEXTURES_ITEM_CAMPFIRE("textures\\item", "campfire", "1.14"),
    TEXTURES_ITEM_CANDLE("textures\\item", "candle", "1.17"),
    TEXTURES_ITEM_CARROT("textures\\item", "carrot", "1.6"),
    TEXTURES_ITEM_CARROT_ON_A_STICK("textures\\item", "carrot_on_a_sick", "1.6"),
    TEXTURES_ITEM_CAULDRON("textures\\item", "cauldron", "1.6"),
    TEXTURES_ITEM_CHAIN("textures\\item", "chain", "1.16"),
    TEXTURES_ITEM_CHAINMAIN_BOOTS("textures\\item", "chainmail_boots", "1.6"),
    TEXTURES_ITEM_CHAINMAIN_CHESTPLATE("textures\\item", "chainmail_chestplate", "1.6"),
    TEXTURES_ITEM_CHAINMAIN_HELMET("textures\\item", "chainmail_helmet", "1.6"),
    TEXTURES_ITEM_CHAINMAIN_LEGGINGS("textures\\item", "chainmail_leggings", "1.6"),
    TEXTURES_ITEM_CHARCOAL("textures\\item", "charcoal", "1.6"),
    TEXTURES_ITEM_CHEST_MINECART("textures\\item", "chest_minecart", "minecart_chest","1.6"),
    TEXTURES_ITEM_CHICKEN("textures\\item", "chicken", "chicken_raw", "1.6"),
    TEXTURES_ITEM_CHORUS_FRUIT("textures\\item", "chorus_fruit", "1.9"),
    TEXTURES_ITEM_CLAY_BALL("textures\\item", "clay_ball", "1.6"),
    TEXTURES_ITEM_CLOCK("textures\\item", "clock", "1.6"),
    TEXTURES_ITEM_CLOCK_00("textures\\item", "clock_00", "1.9"),
    TEXTURES_ITEM_CLOCK_01("textures\\item", "clock_01", "1.9"),
    TEXTURES_ITEM_CLOCK_02("textures\\item", "clock_02", "1.9"),
    TEXTURES_ITEM_CLOCK_03("textures\\item", "clock_03", "1.9"),
    TEXTURES_ITEM_CLOCK_04("textures\\item", "clock_04", "1.9"),
    TEXTURES_ITEM_CLOCK_05("textures\\item", "clock_05", "1.9"),
    TEXTURES_ITEM_CLOCK_06("textures\\item", "clock_06", "1.9"),
    TEXTURES_ITEM_CLOCK_07("textures\\item", "clock_07", "1.9"),
    TEXTURES_ITEM_CLOCK_08("textures\\item", "clock_08", "1.9"),
    TEXTURES_ITEM_CLOCK_09("textures\\item", "clock_09", "1.9"),
    TEXTURES_ITEM_CLOCK_10("textures\\item", "clock_10", "1.9"),
    TEXTURES_ITEM_CLOCK_11("textures\\item", "clock_11", "1.9"),
    TEXTURES_ITEM_CLOCK_12("textures\\item", "clock_12", "1.9"),
    TEXTURES_ITEM_CLOCK_13("textures\\item", "clock_13", "1.9"),
    TEXTURES_ITEM_CLOCK_14("textures\\item", "clock_14", "1.9"),
    TEXTURES_ITEM_CLOCK_15("textures\\item", "clock_15", "1.9"),
    TEXTURES_ITEM_CLOCK_16("textures\\item", "clock_16", "1.9"),
    TEXTURES_ITEM_CLOCK_17("textures\\item", "clock_17", "1.9"),
    TEXTURES_ITEM_CLOCK_18("textures\\item", "clock_18", "1.9"),
    TEXTURES_ITEM_CLOCK_19("textures\\item", "clock_19", "1.9"),
    TEXTURES_ITEM_CLOCK_20("textures\\item", "clock_20", "1.9"),
    TEXTURES_ITEM_CLOCK_21("textures\\item", "clock_21", "1.9"),
    TEXTURES_ITEM_CLOCK_22("textures\\item", "clock_22", "1.9"),
    TEXTURES_ITEM_CLOCK_23("textures\\item", "clock_23", "1.9"),
    TEXTURES_ITEM_CLOCK_24("textures\\item", "clock_24", "1.9"),
    TEXTURES_ITEM_CLOCK_25("textures\\item", "clock_25", "1.9"),
    TEXTURES_ITEM_CLOCK_26("textures\\item", "clock_26", "1.9"),
    TEXTURES_ITEM_CLOCK_27("textures\\item", "clock_27", "1.9"),
    TEXTURES_ITEM_CLOCK_28("textures\\item", "clock_28", "1.9"),
    TEXTURES_ITEM_CLOCK_29("textures\\item", "clock_29", "1.9"),
    TEXTURES_ITEM_CLOCK_30("textures\\item", "clock_30", "1.9"),
    TEXTURES_ITEM_CLOCK_31("textures\\item", "clock_31", "1.9"),
    TEXTURES_ITEM_CLOCK_32("textures\\item", "clock_32", "1.9"),
    TEXTURES_ITEM_CLOCK_33("textures\\item", "clock_33", "1.9"),
    TEXTURES_ITEM_CLOCK_34("textures\\item", "clock_34", "1.9"),
    TEXTURES_ITEM_CLOCK_35("textures\\item", "clock_35", "1.9"),
    TEXTURES_ITEM_CLOCK_36("textures\\item", "clock_36", "1.9"),
    TEXTURES_ITEM_CLOCK_37("textures\\item", "clock_37", "1.9"),
    TEXTURES_ITEM_CLOCK_38("textures\\item", "clock_38", "1.9"),
    TEXTURES_ITEM_CLOCK_39("textures\\item", "clock_39", "1.9"),
    TEXTURES_ITEM_CLOCK_40("textures\\item", "clock_40", "1.9"),
    TEXTURES_ITEM_CLOCK_41("textures\\item", "clock_41", "1.9"),
    TEXTURES_ITEM_CLOCK_42("textures\\item", "clock_42", "1.9"),
    TEXTURES_ITEM_CLOCK_43("textures\\item", "clock_43", "1.9"),
    TEXTURES_ITEM_CLOCK_44("textures\\item", "clock_44", "1.9"),
    TEXTURES_ITEM_CLOCK_45("textures\\item", "clock_45", "1.9"),
    TEXTURES_ITEM_CLOCK_46("textures\\item", "clock_46", "1.9"),
    TEXTURES_ITEM_CLOCK_47("textures\\item", "clock_47", "1.9"),
    TEXTURES_ITEM_CLOCK_48("textures\\item", "clock_48", "1.9"),
    TEXTURES_ITEM_CLOCK_49("textures\\item", "clock_49", "1.9"),
    TEXTURES_ITEM_CLOCK_50("textures\\item", "clock_50", "1.9"),
    TEXTURES_ITEM_CLOCK_51("textures\\item", "clock_51", "1.9"),
    TEXTURES_ITEM_CLOCK_52("textures\\item", "clock_52", "1.9"),
    TEXTURES_ITEM_CLOCK_53("textures\\item", "clock_53", "1.9"),
    TEXTURES_ITEM_CLOCK_54("textures\\item", "clock_54", "1.9"),
    TEXTURES_ITEM_CLOCK_55("textures\\item", "clock_55", "1.9"),
    TEXTURES_ITEM_CLOCK_56("textures\\item", "clock_56", "1.9"),
    TEXTURES_ITEM_CLOCK_57("textures\\item", "clock_57", "1.9"),
    TEXTURES_ITEM_CLOCK_58("textures\\item", "clock_58", "1.9"),
    TEXTURES_ITEM_CLOCK_59("textures\\item", "clock_59", "1.9"),
    TEXTURES_ITEM_CLOCK_60("textures\\item", "clock_60", "1.9"),
    TEXTURES_ITEM_CLOCK_61("textures\\item", "clock_61", "1.9"),
    TEXTURES_ITEM_CLOCK_62("textures\\item", "clock_62", "1.9"),
    TEXTURES_ITEM_CLOCK_63("textures\\item", "clock_63", "1.9"),
    TEXTURES_ITEM_COAL("textures\\item", "coal", "1.6"),
    TEXTURES_ITEM_COCOA_BEANS("textures\\item", "cocoa_beans", "dye_powder_brown", "1.6"),
    TEXTURES_ITEM_COD("textures\\item", "cod", "1.13"),
    TEXTURES_ITEM_COD_BUCKET("textures\\item", "cod_bucket", "1.13"),
    TEXTURES_ITEM_COMMAND_BLOCK_MINECART("textures\\item", "command_block_minecart", "minecart_command_block", "1.7"),
    TEXTURES_ITEM_COMPARATOR("textures\\item", "comparator", "1.6"),
    TEXTURES_ITEM_COMPASS("textures\\item", "compass", "1.6"),
    TEXTURES_ITEM_COMPASS_00("textures\\item", "compass_00", "1.9"),
    TEXTURES_ITEM_COMPASS_01("textures\\item", "compass_01", "1.9"),
    TEXTURES_ITEM_COMPASS_02("textures\\item", "compass_02", "1.9"),
    TEXTURES_ITEM_COMPASS_03("textures\\item", "compass_03", "1.9"),
    TEXTURES_ITEM_COMPASS_04("textures\\item", "compass_04", "1.9"),
    TEXTURES_ITEM_COMPASS_05("textures\\item", "compass_05", "1.9"),
    TEXTURES_ITEM_COMPASS_06("textures\\item", "compass_06", "1.9"),
    TEXTURES_ITEM_COMPASS_07("textures\\item", "compass_07", "1.9"),
    TEXTURES_ITEM_COMPASS_08("textures\\item", "compass_08", "1.9"),
    TEXTURES_ITEM_COMPASS_09("textures\\item", "compass_09", "1.9"),
    TEXTURES_ITEM_COMPASS_10("textures\\item", "compass_10", "1.9"),
    TEXTURES_ITEM_COMPASS_11("textures\\item", "compass_11", "1.9"),
    TEXTURES_ITEM_COMPASS_12("textures\\item", "compass_12", "1.9"),
    TEXTURES_ITEM_COMPASS_13("textures\\item", "compass_13", "1.9"),
    TEXTURES_ITEM_COMPASS_14("textures\\item", "compass_14", "1.9"),
    TEXTURES_ITEM_COMPASS_15("textures\\item", "compass_15", "1.9"),
    TEXTURES_ITEM_COMPASS_16("textures\\item", "compass_16", "1.9"),
    TEXTURES_ITEM_COMPASS_17("textures\\item", "compass_17", "1.9"),
    TEXTURES_ITEM_COMPASS_18("textures\\item", "compass_18", "1.9"),
    TEXTURES_ITEM_COMPASS_19("textures\\item", "compass_19", "1.9"),
    TEXTURES_ITEM_COMPASS_20("textures\\item", "compass_20", "1.9"),
    TEXTURES_ITEM_COMPASS_21("textures\\item", "compass_21", "1.9"),
    TEXTURES_ITEM_COMPASS_22("textures\\item", "compass_22", "1.9"),
    TEXTURES_ITEM_COMPASS_23("textures\\item", "compass_23", "1.9"),
    TEXTURES_ITEM_COMPASS_24("textures\\item", "compass_24", "1.9"),
    TEXTURES_ITEM_COMPASS_25("textures\\item", "compass_25", "1.9"),
    TEXTURES_ITEM_COMPASS_26("textures\\item", "compass_26", "1.9"),
    TEXTURES_ITEM_COMPASS_27("textures\\item", "compass_27", "1.9"),
    TEXTURES_ITEM_COMPASS_28("textures\\item", "compass_28", "1.9"),
    TEXTURES_ITEM_COMPASS_29("textures\\item", "compass_29", "1.9"),
    TEXTURES_ITEM_COMPASS_30("textures\\item", "compass_30", "1.9"),
    TEXTURES_ITEM_COMPASS_31("textures\\item", "compass_31", "1.9"),
    TEXTURES_ITEM_COOKED_BEEF("textures\\item", "cooked_beef", "beef_cooked", "1.6"),
    TEXTURES_ITEM_COOKED_CHICKEN("textures\\item", "cooked_chicken", "chicken_cooked", "1.6"),
    TEXTURES_ITEM_COOKED_COD("textures\\item", "cooked_cod", "1.13"),
    TEXTURES_ITEM_COOKED_MUTTON("textures\\item", "cooked_mutton", "mutton_cooked", "1.8"),
    TEXTURES_ITEM_COOKED_PORKCHOP("textures\\item", "cooked_porkchop", "porkchop_cooked", "1.6"),
    TEXTURES_ITEM_COOKED_RABBIT("textures\\item", "cooked_rabbit", "rabbit_cooked", "1.8"),
    TEXTURES_ITEM_COOKED_SALMON("textures\\item", "cooked_salmon", "fish_salmon_cooked", "1.7"),
    TEXTURES_ITEM_COOKIE("textures\\item", "cookie", "1.6"),
    TEXTURES_ITEM_COPPER_INGOT("textures\\item", "copper_ingot", "1.17"),
    TEXTURES_ITEM_CREEPER_BANNER_PATTERN("textures\\item", "creeper_banner_pattern", "1.14"),
    TEXTURES_ITEM_CRIMSON_DOOR("textures\\item", "crimson_door", "1.16"),
    TEXTURES_ITEM_CRIMSON_SIGN("textures\\item", "crimson_sign", "1.16"),
    TEXTURES_ITEM_CROSSBOW_ARROW("textures\\item", "crossbow_arrow", "1.14"),
    TEXTURES_ITEM_CROSSBOW_FIREWORK("textures\\item", "crossbow_firework", "1.14"),
    TEXTURES_ITEM_CROSSBOW_PULLING_0("textures\\item", "crossbow_pulling_0", "1.14"),
    TEXTURES_ITEM_CROSSBOW_PULLING_1("textures\\item", "crossbow_pulling_1", "1.14"),
    TEXTURES_ITEM_CROSSBOW_PULLING_2("textures\\item", "crossbow_pulling_2", "1.14"),
    TEXTURES_ITEM_CROSSBOW_STANDBY("textures\\item", "crossbow_standby", "1.14"),
    TEXTURES_ITEM_CYAN_CANDLE("textures\\item", "cyan_candle", "1.17"),
    TEXTURES_ITEM_CYAN_DYE("textures\\item", "cyan_dye", "dye_powder_cyan"),
    TEXTURES_ITEM_DARK_OAK_BOAT("textures\\item", "dark_oak_boat", "1.9"),
    TEXTURES_ITEM_DARK_OAK_CHEST_BOAT("textures\\item", "dark_oak_chest_boat", "1.19"),
    TEXTURES_ITEM_DARK_OAK_DOOR("textures\\item", "dark_oak_door", "door_dark_oak", "1.8"),
    TEXTURES_ITEM_DARK_OAK_SIGN("textures\\item", "darK_oak_sign", "1.14"),
    TEXTURES_ITEM_DIAMOND("textures\\item", "diamond", "1.6"),
    TEXTURES_ITEM_DIAMOND_AXE("textures\\item", "diamond_axe", "1.6"),
    TEXTURES_ITEM_DIAMOND_BOOTS("textures\\item", "diamond_boots", "1.6"),
    TEXTURES_ITEM_DIAMOND_CHESTPLATE("textures\\item", "diamond_chestplate", "1.6"),
    TEXTURES_ITEM_DIAMOND_HELMET("textures\\item", "diamond_helmet", "1.6"),
    TEXTURES_ITEM_DIAMOND_HOE("textures\\item", "diamond_hoe", "1.6"),
    TEXTURES_ITEM_DIAMOND_HORSE_ARMOR("textures\\item", "diamond_horse_armor", "1.6"),
    TEXTURES_ITEM_DIAMOND_LEGGINGS("textures\\item", "diamond_leggings", "1.6"),
    TEXTURES_ITEM_DIAMOND_PICKAXE("textures\\item", "diamond_pickaxe", "1.6"),
    TEXTURES_ITEM_DIAMOND_SHOVEL("textures\\item", "diamond_shovel", "1.6"),
    TEXTURES_ITEM_DIAMOND_SWORD("textures\\item", "diamond_sword", "1.6"),
    TEXTURES_ITEM_DISC_FRAGMENT_5("textures\\item", "disc_fragment_5", "1.19"),
    TEXTURES_ITEM_DRAGON_BREATH("textures\\item", "dragon_breath", "1.9"),
    TEXTURES_ITEM_DRIED_KELP("textures\\item", "dried_kelp", "1.13"),
    TEXTURES_ITEM_ECHO_SHARD("textures\\item", "echo_shard", "1.19"),
    TEXTURES_ITEM_EGG("textures\\item", "egg", "1.6"),
    TEXTURES_ITEM_ELYTRA("textures\\item", "elytra", "1.9"),
    TEXTURES_ITEM_EMERALD("textures\\item", "emerald", "1.6"),
    TEXTURES_ITEM_EMPTY_ARMOR_SLOT_BOOTS("textures\\item", "empty_armor_slot_boots", "1.6"),
    TEXTURES_ITEM_EMPTY_ARMOR_SLOT_CHESTPLATE("textures\\item", "empty_armor_slot_chestplate", "1.6"),
    TEXTURES_ITEM_EMPTY_ARMOR_SLOT_HELMET("textures\\item", "empty_armor_slot_helmet", "1.6"),
    TEXTURES_ITEM_EMPTY_ARMOR_SLOT_LEGGINGS("textures\\item", "empty_armor_slot_leggings", "1.6"),
    TEXTURES_ITEM_ENCHANTED_BOOK("textures\\item", "enchanted_book", "book_enchanted", "1.6"),
    TEXTURES_ITEM_END_CRYSTAL("textures\\item", "end_crystal", "1.9"),
    TEXTURES_ITEM_ENDER_EYE("textures\\item", "ender_eye", "1.6"),
    TEXTURES_ITEM_ENDER_PEARL("textures\\item", "ender_pearl", "1.6"),
    TEXTURES_ITEM_EXPERIENCE_BOTTLE("textures\\item", "experience_bottle", "1.6"),
    TEXTURES_ITEM_FEATHER("textures\\item", "feather", "1.6"),
    TEXTURES_ITEM_FERMENTED_SPIDER_EYE("textures\\item", "spider_eye_fermented", "1.6"),
    TEXTURES_ITEM_FILLED_MAP("textures\\item", "filled_map", "map_filled", "1.6"),
    TEXTURES_ITEM_FILLED_MAP_MARKINGS("textures\\item", "filled_map_markins", "map_filled_markings", "1.11"),
    TEXTURES_ITEM_FIRE_CHARGE("textures\\item", "fire_charge", "fireball", "1.6"),
    TEXTURES_ITEM_FIREWORK_ROCKET("textures\\item", "firework_rocket", "fireworks", "1.6"),
    TEXTURES_ITEM_FIREWORK_STAR("textures\\item", "firework_star", "fireworks_charge", "1.6"),
    TEXTURES_ITEM_FIREWORK_STAR_OVERLAY("textures\\item", "firework_star_overlay", "fireworks_charge_overlay", "1.6"),
    TEXTURES_ITEM_FISHING_ROD("textures\\item", "fishing_rod", "fishing_rod_uncast", "1.6"),
    TEXTURES_ITEM_FISHING_ROD_CAST("textures\\item", "fishing_rod_cast", "1.6"),
    TEXTURES_ITEM_FLINT("textures\\item", "flint", "1.6"),
    TEXTURES_ITEM_FLINT_AND_STEEL("textures\\item", "flint_and_steel", "1.6"),
    TEXTURES_ITEM_FLOWER_BANNER_PATTERN("textures\\item", "flower_banner_pattern", "1.14"),
    TEXTURES_ITEM_FLOWER_POT("textures\\item", "flower_pot", "1.6"),
    TEXTURES_ITEM_FURNACE_MINECART("textures\\item", "furnace_minecart", "minecart_furnace", "1.6"),
    TEXTURES_ITEM_GHAST_TEAR("textures\\item", "ghast_tear", "1.6"),
    TEXTURES_ITEM_GLASS_BOTTLE("textures\\item", "glass_bottle", "potion_bottle_empty", "1.6"),
    TEXTURES_ITEM_GLISTERING_MELON_SLICE("textures\\item", "glistering_melon_slice", "melon_speckled", "1.6"),
    TEXTURES_ITEM_GLOBE_BANNER_PATTERN("textures\\item", "globe_banner", "pattern", "1.14"),
    TEXTURES_ITEM_GLOW_BERRIES("textures\\item", "glow_berries", "1.17"),
    TEXTURES_ITEM_GLOW_INK_SAC("textures\\item", "glow_ink_sac", "1.17"),
    TEXTURES_ITEM_GLOW_ITEM_FRAME("textures\\item", "glow_item_frame", "1.17"),
    TEXTURES_ITEM_GLOWSTONE_DUST("textures\\item", "glowstone_dust", "1.6"),
    TEXTURES_ITEM_GOAT_HORN("textures\\item", "goat_horn", "1.17"),
    TEXTURES_ITEM_GOLD_INGOT("textures\\item", "gold_ingot", "1.6"),
    TEXTURES_ITEM_GOLD_NUGGET("textures\\item", "gold_nugget", "1.6"),
    TEXTURES_ITEM_GOLDEN_APPLE("textures\\item", "golden_apple", "apple_golden", "1.6"),
    TEXTURES_ITEM_GOLDEN_AXE("textures\\item", "golden_axe", "gold_axe", "1.6"),
    TEXTURES_ITEM_GOLDEN_BOOTS("textures\\item", "golden_boots", "gold_axe", "1.6"),
    TEXTURES_ITEM_GOLDEN_CARROT("textures\\item", "golden_carrot", "carrot_golden", "1.6"),
    TEXTURES_ITEM_GOLDEN_CHESTPLATE("textures\\item", "golden_chestplate", "gold_chestplate", "1.6"),
    TEXTURES_ITEM_GOLDEN_HELMET("textures\\item", "golden_helmet", "gold_helmet", "1.6"),
    TEXTURES_ITEM_GOLDEN_HOE("textures\\item", "golden_hoe", "gold_hoe", "1.6"),
    TEXTURES_ITEM_GOLDEN_HORSE_ARMOR("textures\\item", "golden_horse_armor", "gold_horse_armor", "1.6"),
    TEXTURES_ITEM_GOLDEN_LEGGINGS("textures\\item", "golden_leggings", "gold_leggings", "1.6"),
    TEXTURES_ITEM_GOLDEN_PICKAXE("textures\\item", "golden_pickaxe", "gold_pickaxe", "1.6"),
    TEXTURES_ITEM_GOLDEN_SHOVEL("textures\\item", "golden_shovel", "gold_shovel", "1.6"),
    TEXTURES_ITEM_GOLDEN_SWORD("textures\\item", "golden_sword", "gold_sword", "1.6"),
    TEXTURES_ITEM_GRAY_CANDLE("textures\\item", "gray_candle", "1.17"),
    TEXTURES_ITEM_GRAY_DYE("textures\\item", "gray_dye", "dye_powder_gray", "1.6"),
    TEXTURES_ITEM_GREEN_CANDLE("textures\\item", "green_candle", "1.17"),
    TEXTURES_ITEM_GREEN_DYE("textures\\item", "green_dye", "dye_powder_green", "1.6"),
    TEXTURES_ITEM_GUNPOWDER("textures\\item", "gunpowder", "1.6"),
    TEXTURES_ITEM_HEART_OF_THE_SEA("textures\\item", "heart_of_the_sea", "1.13"),
    TEXTURES_ITEM_HONEY_BOTTLE("textures\\item", "honey_bottle", "1.15"),
    TEXTURES_ITEM_HONEYCOMB("textures\\item", "honeycomb", "1.15"),
    TEXTURES_ITEM_HOPPER("textures\\item", "hopper", "1.6"),
    TEXTURES_ITEM_HOPPER_MINECART("textures\\item", "hopper_minecart", "minecart_hopper", "1.6"),
    TEXTURES_ITEM_INK_SAC("textures\\item", "ink_sac", "dye_powder_black", "1.6"),
    TEXTURES_ITEM_IRON_AXE("textures\\item", "iron_axe", "1.6"),
    TEXTURES_ITEM_IRON_BOOTS("textures\\item", "iron_boots", "1.6"),
    TEXTURES_ITEM_IRON_CHESTPLATE("textures\\item", "iron_chestplate", "1.6"),
    TEXTURES_ITEM_IRON_DOOR("textures\\item", "iron_door", "door_iron", "1.6"),
    TEXTURES_ITEM_IRON_HELMET("textures\\item", "iron_helmet", "1.6"),
    TEXTURES_ITEM_IRON_HOE("textures\\item", "iron_hoe", "1.6"),
    TEXTURES_ITEM_IRON_HORSE_ARMOR("textures\\item", "iron_horse_armor", "1.6"),
    TEXTURES_ITEM_IRON_INGOT("textures\\item", "iron_ingot", "1.6"),
    TEXTURES_ITEM_IRON_LEGGINGS("textures\\item", "iron_leggings", "1.6"),
    TEXTURES_ITEM_IRON_NUGGET("textures\\item", "iron_nugget", "1.12"),
    TEXTURES_ITEM_IRON_PICKAXE("textures\\item", "iron_pickaxe", "1.6"),
    TEXTURES_ITEM_IRON_SHOVEL("textures\\item", "iron_shovel", "1.6"),
    TEXTURES_ITEM_IRON_SWORD("textures\\item", "iron_sword", "1.6"),
    TEXTURES_ITEM_ITEM_FRAME("textures\\item", "item_frame", "1.6"),
    TEXTURES_ITEM_JUNGLE_BOAT("textures\\item", "jungle_boat", "1.9"),
    TEXTURES_ITEM_JUNGLE_CHEST_BOAT("textures\\item", "jugnle_chest_boat", "1.19"),
    TEXTURES_ITEM_JUNGLE_DOOR("textures\\item", "jungle_door", "door_jungle", "1.8"),
    TEXTURES_ITEM_JUNGLE_SIGN("textures\\item", "jungle_sign", "1.14"),
    TEXTURES_ITEM_KELP("textures\\item", "kelp", "1.13"),
    TEXTURES_ITEM_KNOWLEDGE_BOOK("textures\\item", "knowledge_book", "1.12"),
    TEXTURES_ITEM_LANTERN("textures\\item", "lantern", "1.14"),
    TEXTURES_ITEM_LAPIS_LAZULI("textures\\item", "lapis_lazuli", "dye_powder_blue", "1.6"),
    TEXTURES_ITEM_LAVA_BUCKET("textures\\item", "lava_bucket", "bucket_lava", "1.6"),
    TEXTURES_ITEM_LEAD("textures\\item", "lead", "1.6"),
    TEXTURES_ITEM_LEATHER("textures\\item", "leather", "1.6"),
    TEXTURES_ITEM_LEATHER_BOOTS("textures\\item", "leather_boots", "1.6"),
    TEXTURES_ITEM_LEATHER_BOOTS_OVERLAY("textures\\item", "leather_boots_overlay", "1.6"),
    TEXTURES_ITEM_LEATHER_CHESTPLATE("textures\\item", "leather_chestplate", "1.6"),
    TEXTURES_ITEM_LEATHER_CHESTPLATE_OVERLAY("textures\\item", "leather_chestplate_overlay", "1.6"),
    TEXTURES_ITEM_LEATHER_HELMET("textures\\item", "leather_helmet", "1.6"),
    TEXTURES_ITEM_LEATHER_HELMET_OVERLAY("textures\\item", "leather_helmet_overlay", "1.6"),
    TEXTURES_ITEM_LEATHER_LEGGINGS("textures\\item", "leather_leggings", "1.6"),
    TEXTURES_ITEM_LEATHER_LEGGINGS_OVERLAY("textures\\item", "leather_leggings_overlay", "1.6"),
    TEXTURES_ITEM_LIGHT("textures\\item", "light", "1.17"),
    TEXTURES_ITEM_LIGHT_00("textures\\item", "light_00", "1.17"),
    TEXTURES_ITEM_LIGHT_01("textures\\item", "light_01", "1.17"),
    TEXTURES_ITEM_LIGHT_02("textures\\item", "light_02", "1.17"),
    TEXTURES_ITEM_LIGHT_03("textures\\item", "light_03", "1.17"),
    TEXTURES_ITEM_LIGHT_04("textures\\item", "light_04", "1.17"),
    TEXTURES_ITEM_LIGHT_05("textures\\item", "light_05", "1.17"),
    TEXTURES_ITEM_LIGHT_06("textures\\item", "light_06", "1.17"),
    TEXTURES_ITEM_LIGHT_07("textures\\item", "light_07", "1.17"),
    TEXTURES_ITEM_LIGHT_08("textures\\item", "light_08", "1.17"),
    TEXTURES_ITEM_LIGHT_09("textures\\item", "light_09", "1.17"),
    TEXTURES_ITEM_LIGHT_10("textures\\item", "light_10", "1.17"),
    TEXTURES_ITEM_LIGHT_11("textures\\item", "light_11", "1.17"),
    TEXTURES_ITEM_LIGHT_12("textures\\item", "light_12", "1.17"),
    TEXTURES_ITEM_LIGHT_13("textures\\item", "light_13", "1.17"),
    TEXTURES_ITEM_LIGHT_14("textures\\item", "light_14", "1.17"),
    TEXTURES_ITEM_LIGHT_15("textures\\item", "light_15", "1.17"),
    TEXTURES_ITEM_LIGHT_BLUE_CANDLE("textures\\item", "light_blue_candle", "1.17"),
    TEXTURES_ITEM_LIGHT_BLUE_DYE("textures\\item", "light_blue_dye", "dye_powder_light_blue", "1.6"),
    TEXTURES_ITEM_LIGHT_GRAY_CANDLE("textures\\item", "light_gray_candle", "1.17"),
    TEXTURES_ITEM_LIGHT_GRAY_DYE("textures\\item", "light_gray_dye", "dye_powder_silver", "1.6"),
    TEXTURES_ITEM_LIME_CANDLE("textures\\item", "lime_candle", "1.17"),
    TEXTURES_ITEM_LIME_DYE("textures\\item", "lime_dye", "dye_powder_lime", "1.6"),
    TEXTURES_ITEM_LINGERING_POTION("textures\\item", "lingering_potion", "potion_bottle_lingering", "1.9"),
    TEXTURES_ITEM_MAGENTA_CANDLE("textures\\item", "magenta_candle", "1.17"),
    TEXTURES_ITEM_MAGENTA_DYE("textures\\item", "magenta_dye", "dye_powder_magenta", "1.6"),
    TEXTURES_ITEM_MAGMA_CREAM("textures\\item", "magma_cream", "1.6"),
    TEXTURES_ITEM_MANGROVE_BOAT("textures\\item", "mangrove_boat", "1.19"),
    TEXTURES_ITEM_MANGROVE_CHEST_BOAT("textures\\item", "mangrove_chest_boat", "1.19"),
    TEXTURES_ITEM_MANGROVE_DOOR("textures\\item", "mangrove_door", "1.19"),
    TEXTURES_ITEM_MANGROVE_PROPAGULE("textures\\item", "mangrove_propagule", "1.19"),
    TEXTURES_ITEM_MANGROVE_SIGN("textures\\item", "mangrove_sign", "1.19"),
    TEXTURES_ITEM_MAP("textures\\item", "map", "map_empty", "1.6"),
    TEXTURES_ITEM_MELON_SEEDS("textures\\item", "melon_seeds", "seeds_melon", "1.6"),
    TEXTURES_ITEM_MELON_SLICE("textures\\item", "melon_slice", "melon", "1.6"),
    TEXTURES_ITEM_MILK_BUCKET("textures\\item", "milk_bucket", "bucket_milk", "1.6"),
    TEXTURES_ITEM_MINECART("textures\\item", "minecart", "minecart_normal", "1.6"),
    TEXTURES_ITEM_MOJANG_BANNER_PATTERN("textures\\item", "mojang_banner_pattern", "1.14"),
    TEXTURES_ITEM_MUSHROOM_STEW("textures\\item", "mushroom_stew", "1.6"),
    TEXTURES_ITEM_MUSIC_DISC_5("textures\\item", "music_disc_5", "1.19"),
    TEXTURES_ITEM_MUSIC_DISC_11("textures\\item", "music_disc_11", "record_11", "1.6"),
    TEXTURES_ITEM_MUSIC_DISC_13("textures\\item", "music_disc_13", "record_13", "1.6"),
    TEXTURES_ITEM_MUSIC_DISC_BLOCKS("textures\\item", "music_disc_blocks", "record_blocks", "1.6"),
    TEXTURES_ITEM_MUSIC_DISC_CAT("textures\\item", "music_disc_cat", "record_cat", "1.6"),
    TEXTURES_ITEM_MUSIC_DISC_CHIRP("textures\\item", "music_disc_chirp", "record_chirp", "1.6"),
    TEXTURES_ITEM_MUSIC_DISC_FAR("textures\\item", "music_disc_far", "record_far", "1.6"),
    TEXTURES_ITEM_MUSIC_DISC_MALL("textures\\item", "music_disc_mall", "record_mall", "1.6"),
    TEXTURES_ITEM_MUSIC_DISC_MELLOHI("textures\\item", "music_disc_mellohi", "record_mellohi", "1.6"),
    TEXTURES_ITEM_MUSIC_DISC_OTHERSIDE("textures\\item", "music_disc_otherside", "1.18"),
    TEXTURES_ITEM_MUSIC_DISC_PIGSTEP("textures\\item", "music_disc_pigstep", "1.16"),
    TEXTURES_ITEM_MUSIC_DISC_STAL("textures\\item", "music_disc_stal", "record_stal", "1.6"),
    TEXTURES_ITEM_MUSIC_DISC_STRAD("textures\\item", "music_disc_strad", "record_strad", "1.6"),
    TEXTURES_ITEM_MUSIC_DISC_WAIT("textures\\item", "music_disc_wait", "record_wait", "1.6"),
    TEXTURES_ITEM_MUSIC_DISC_WARD("textures\\item", "music_disc_ward", "record_ward", "1.6"),
    TEXTURES_ITEM_MUTTON("textures\\item", "mutton", "mutton_raw", "1.8"),
    TEXTURES_ITEM_NAME_TAG("textures\\item", "name_tag", "1.6"),
    TEXTURES_ITEM_NAUTILUS_SHELL("textures\\item", "nautilus_shell", "1.13"),
    TEXTURES_ITEM_NETHER_BRICK("textures\\item", "nether_brick", "netherbrick", "1.6"),
    TEXTURES_ITEM_NETHER_SPROUTS("textures\\item", "nether_sprouts", "1.16"),
    TEXTURES_ITEM_NETHER_STAR("textures\\item", "nether_star", "1.6"),
    TEXTURES_ITEM_NETHER_WART("textures\\item", "nether_wart", "1.6"),
    TEXTURES_ITEM_NETHERITE_AXE("textures\\item", "netherite_axe", "1.16"),
    TEXTURES_ITEM_NETHERITE_BOOTS("textures\\item", "netherite_boots", "1.16"),
    TEXTURES_ITEM_NETHERITE_CHESTPLATE("textures\\item", "netherite_chestplate", "1.16"),
    TEXTURES_ITEM_NETHERITE_HELMET("textures\\item", "netherite_helmet", "1.16"),
    TEXTURES_ITEM_NETHERITE_HOE("textures\\item", "netherite_hoe", "1.16"),
    TEXTURES_ITEM_NETHERITE_INGOT("textures\\item", "netherite_ingot", "1.16"),
    TEXTURES_ITEM_NETHERITE_LEGGINGS("textures\\item", "netherite_leggings", "1.16"),
    TEXTURES_ITEM_NETHERITE_PICKAXE("textures\\item", "netherite_pickaxe", "1.16"),
    TEXTURES_ITEM_NETHERITE_SCRAP("textures\\item", "netherite_scrap", "1.16"),
    TEXTURES_ITEM_NETHERITE_SHOVEL("textures\\item", "netherite_shovel", "1.16"),
    TEXTURES_ITEM_NETHERITE_SWORD("textures\\item", "netherite_sword", "1.16"),
    TEXTURES_ITEM_OAK_BOAT("textures\\item", "oak_boat", "boat", "1.6"),
    TEXTURES_ITEM_OAK_CHEST_BOAT("textures\\item", "oak_chest_boat", "1.19"),
    TEXTURES_ITEM_OAK_DOOR("textures\\item", "oak_door", "door_wood", "1.6"),
    TEXTURES_ITEM_OAK_SIGN("textures\\item", "oak_sign", "sign", "1.6"),
    TEXTURES_ITEM_ORANGE_CANDLE("textures\\item", "orange_candle", "1.17"),
    TEXTURES_ITEM_ORANGE_DYE("textures\\item", "orange_dye", "dye_powder_orange", "1.6"),
    TEXTURES_ITEM_PAINTING("textures\\item", "painting", "1.6"),
    TEXTURES_ITEM_PAPER("textures\\item", "paper", "1.6"),
    TEXTURES_ITEM_PHANTOM_MEMBRANE("textures\\item", "phantom_membrane", "1.13"),
    TEXTURES_ITEM_PIGLIN_BANNER_PATTERN("textures\\item", "piglin_banner_pattern", "1.16"),
    TEXTURES_ITEM_PINK_CANDLE("textures\\item", "pink_candle", "1.17"),
    TEXTURES_ITEM_PINK_DYE("textures\\item", "pink_dye", "dye_powder_pink", "1.6"),
    TEXTURES_ITEM_POINTED_DRIPSTONE("textures\\item", "pointed_dripstone", "1.17"),
    TEXTURES_ITEM_POISONOUS_POTATO("textures\\item", "poisonous_potato", "potato_poisonous", "1.6"),
    TEXTURES_ITEM_POPPED_CHORUS_FRUIT("textures\\item", "popped_chorus_fruit", "chorus_fruit_popped", "1.9"),
    TEXTURES_ITEM_PORKCHOP("textures\\item", "porkchop", "porkchop_raw", "1.6"),
    TEXTURES_ITEM_POTATO("textures\\item", "potato", "1.6"),
    TEXTURES_ITEM_POTION("textures\\item", "potion", "potion_bottle_drinkable", "1.6"),
    TEXTURES_ITEM_POTION_OVERLAY("textures\\item", "potion_overlay", "1.6"),
    TEXTURES_ITEM_POWDER_SNOW_BUCKET("textures\\item", "powder_snow_bucket", "1.17"),
    TEXTURES_ITEM_PRISMARINE_CRYSTALS("textures\\item", "prismarine_crystals", "1.8"),
    TEXTURES_ITEM_PRISMARINE_SHARD("textures\\item", "prismarine_shard", "1.6"),
    TEXTURES_ITEM_PUFFERFISH("textures\\item", "pufferfish", "fish_pufferfish_raw", "1.7"),
    TEXTURES_ITEM_PUFFERFISH_BUCKET("textures\\item", "pufferfish_bucket", "1.13"),
    TEXTURES_ITEM_PUMPKIN_PIE("textures\\item", "pumpkin_pie", "1.6"),
    TEXTURES_ITEM_PUMPKIN_SEEDS("textures\\item", "pumpkin_seeds", "1.6"),
    TEXTURES_ITEM_PURPLE_CANDLE("textures\\item", "purple_candle", "1.17"),
    TEXTURES_ITEM_PURPLE_DYE("textures\\item", "purple_dye", "dye_powder_purple", "1.6"),
    TEXTURES_ITEM_QUARTZ("textures\\item", "quartz", "1.6"),
    TEXTURES_ITEM_RABBIT("textures\\item", "rabbit", "rabbit_raw", "1.8"),
    TEXTURES_ITEM_RABBIT_FOOT("textures\\item", "rabbit_foot", "1.8"),
    TEXTURES_ITEM_RABBIT_HIDE("textures\\item", "rabbit_hide", "1.8"),
    TEXTURES_ITEM_RABBIT_STEW("textures\\item", "rabbit_stew", "1.8"),
    TEXTURES_ITEM_RAW_COPPER("textures\\item", "raw_copper", "1.17"),
    TEXTURES_ITEM_RAW_GOLD("textures\\item", "raw_gold", "1.17"),
    TEXTURES_ITEM_RAW_IRON("textures\\item", "raw_iron", "1.17"),
    TEXTURES_ITEM_RECOVERY_COMPASS_00("textures\\item", "recovery_compass_00", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_01("textures\\item", "recovery_compass_01", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_02("textures\\item", "recovery_compass_02", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_03("textures\\item", "recovery_compass_03", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_04("textures\\item", "recovery_compass_04", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_05("textures\\item", "recovery_compass_05", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_06("textures\\item", "recovery_compass_06", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_07("textures\\item", "recovery_compass_07", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_08("textures\\item", "recovery_compass_08", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_09("textures\\item", "recovery_compass_09", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_10("textures\\item", "recovery_compass_10", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_11("textures\\item", "recovery_compass_11", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_12("textures\\item", "recovery_compass_12", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_13("textures\\item", "recovery_compass_13", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_14("textures\\item", "recovery_compass_14", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_15("textures\\item", "recovery_compass_15", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_16("textures\\item", "recovery_compass_16", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_17("textures\\item", "recovery_compass_17", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_18("textures\\item", "recovery_compass_18", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_19("textures\\item", "recovery_compass_19", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_20("textures\\item", "recovery_compass_10", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_21("textures\\item", "recovery_compass_21", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_22("textures\\item", "recovery_compass_22", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_23("textures\\item", "recovery_compass_23", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_24("textures\\item", "recovery_compass_24", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_25("textures\\item", "recovery_compass_25", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_26("textures\\item", "recovery_compass_26", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_27("textures\\item", "recovery_compass_27", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_28("textures\\item", "recovery_compass_28", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_29("textures\\item", "recovery_compass_29", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_30("textures\\item", "recovery_compass_30", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_31("textures\\item", "recovery_compass_31", "1.19"),
    TEXTURES_ITEM_RECOVERY_COMPASS_32("textures\\item", "recovery_compass_32", "1.19"),
    TEXTURES_ITEM_RED_CANDLE("textures\\item", "red_candle", "1.17"),
    TEXTURES_ITEM_RED_DYE("textures\\item", "red_dye", "dye_powder_red", "1.6"),
    TEXTURES_ITEM_REDSTONE("textures\\item", "redstone", "redstone_dust", "1.6"),
    TEXTURES_ITEM_REPEATER("textures\\item", "repeater", "1.6"),
    TEXTURES_ITEM_ROTTEN_FLESH("textures\\item", "rotten_flesh", "1.6"),
    TEXTURES_ITEM_SADDLE("textures\\item", "saddle", "1.6"),
    TEXTURES_ITEM_SALMON("textures\\item", "salmon", "fish_salmon_raw", "1.7"),
    TEXTURES_ITEM_SALMON_BUCKET("textures\\item", "salmon_bucket", "1.13"),
    TEXTURES_ITEM_SCUTE("textures\\item", "scute", "1.13"),
    TEXTURES_ITEM_SEA_PICKLE("textures\\item", "pickle", "1.13"),
    TEXTURES_ITEM_SEAGRASS("textures\\item", "seagrass", "1.13"),
    TEXTURES_ITEM_SHEARS("textures\\item", "shears", "1.6"),
    TEXTURES_ITEM_SHULKER_SHELL("textures\\item", "shulker_shell", "1.11"),
    TEXTURES_ITEM_SKULL_BANNER_PATTERN("textures\\item", "skull_banner_pattern", "1.14"),
    TEXTURES_ITEM_SLIME_BALL("textures\\item", "slime_ball", "slimeball", "1.6"),
    TEXTURES_ITEM_SNOWBALL("textures\\item", "snowball", "1.6"),
    TEXTURES_ITEM_SOUL_CAMPFIRE("textures\\item", "soul_campfire", "1.16"),
    TEXTURES_ITEM_SOUL_LANTERN("textures\\item", "soul_lantern", "1.16"),
    TEXTURES_ITEM_SPAWN_EGG("textures\\item", "spawn_egg", "1.6"),
    TEXTURES_ITEM_SPAWN_EGG_OVERLAY("textures\\item", "spawn_egg_overlay", "1.6"),
    TEXTURES_ITEM_SPECTRAL_ARROW("textures\\item", "spectral_arrow", "1.9"),
    TEXTURES_ITEM_SPIDER_EYE("textures\\item", "spider_eye", "1.6"),
    TEXTURES_ITEM_SPLASH_POTION("textures\\item", "splash_potion", "potion_bottle_splash", "1.6"),
    TEXTURES_ITEM_SPRUCE_BOAT("textures\\item", "spruce_boat", "1.9"),
    TEXTURES_ITEM_SPRUCE_CHEST_BOAT("textures\\item", "spruce_chest_boat", "1.19"),
    TEXTURES_ITEM_SPRUCE_DOOR("textures\\item", "spruce_door", "door_spruce", "1.8"),
    TEXTURES_ITEM_SPRUCE_SIGN("textures\\item", "spruce_sign", "1.14"),
    TEXTURES_ITEM_SPYGLASS("textures\\item", "spyglass", "1.17"),
    TEXTURES_ITEM_SPYGLASS_MODEL("textures\\item", "spyglass_model", "1.17"),
    TEXTURES_ITEM_STICK("textures\\item", "stick", "1.6"),
    TEXTURES_ITEM_STONE_AXE("textures\\item", "stone_axe", "1.6"),
    TEXTURES_ITEM_STONE_HOE("textures\\item", "stone_hoe", "1.6"),
    TEXTURES_ITEM_STONE_PICKAXE("textures\\item", "stone_pickaxe", "1.6"),
    TEXTURES_ITEM_STONE_SHOVEL("textures\\item", "stone_shovel", "1.6"),
    TEXTURES_ITEM_STONE_SWORD("textures\\item", "stone_sword", "1.6"),
    TEXTURES_ITEM_STRING("textures\\item", "string", "1.6"),
    TEXTURES_ITEM_STRUCTURE_VOID("textures\\item", "structure_void", "1.10"),
    TEXTURES_ITEM_SUGAR("textures\\item", "sugar", "1.6"),
    TEXTURES_ITEM_SUGAR_CANE("textures\\item", "sugar_cane", "reeds", "1.6"),
    TEXTURES_ITEM_SUSPICIOUS_STEW("textures\\item", "suspicious_stew", "1.14"),
    TEXTURES_ITEM_SWEET_BERRIES("textures\\item", "sweet_berries", "1.14"),
    TEXTURES_ITEM_TADPOLE_BUCKET("textures\\item", "tadpole_bucket", "1.19"),
    TEXTURES_ITEM_TIPPED_ARROW_BASE("textures\\item", "tipped_arrow_base", "1.9"),
    TEXTURES_ITEM_TIPPED_ARROW_HEAD("textures\\item", "tipped_arrow_head", "1.9"),
    TEXTURES_ITEM_TNT_MINECART("textures\\item", "tnt_minecart", "minecart_tnt", "1.6"),
    TEXTURES_ITEM_TOTEM_OF_UNDYING("textures\\item", "totem_of_undying", "totem", "1.11"),
    TEXTURES_ITEM_TRIDENT("textures\\item", "trident", "1.13"),
    TEXTURES_ITEM_TROPICAL_FISH("textures\\item", "tropical_fish", "fish_clownfish_raw", "1.6"),
    TEXTURES_ITEM_TROPICAL_FISH_BUCKET("textures\\item", "tropical_fish_bucket", "1.13"),
    TEXTURES_ITEM_TURTLE_EGG("textures\\item", "turtle_egg", "1.13"),
    TEXTURES_ITEM_TURTLE_HELMET("textures\\item", "turtle_helmet", "1.13"),
    TEXTURES_ITEM_WARPED_DOOR("textures\\item", "warped_door", "1.16"),
    TEXTURES_ITEM_WARPED_FUNGUS_ON_A_STICK("textures\\item", "warped_fungus_on_a_stick", "1.16"),
    TEXTURES_ITEM_WARPED_SIGN("textures\\item", "warped_sign", "1.16"),
    TEXTURES_ITEM_WATER_BUCKET("textures\\item", "water_bucket", "bucket_water", "1.6"),
    TEXTURES_ITEM_WHEAT("textures\\item", "wheat", "1.6"),
    TEXTURES_ITEM_WHEAT_SEEDS("textures\\item", "wheat_seeds", "seeds_wheat", "1.6"),
    TEXTURES_ITEM_WHITE_CANDLE("textures\\item", "white_candle", "1.17"),
    TEXTURES_ITEM_WHITE_DYE("textures\\item", "white_dye", "1.14"),
    TEXTURES_ITEM_WOODEN_AXE("textures\\item", "wooden_axe", "wood_axe", "1.6"),
    TEXTURES_ITEM_WOODEN_HOE("textures\\item", "wooden_hoe", "wood_hoe","1.6"),
    TEXTURES_ITEM_WOODEN_PICKAXE("textures\\item", "wooden_pickaxe", "wood_pickaxe","1.6"),
    TEXTURES_ITEM_WOODEN_SHOVEL("textures\\item", "wooden_shovel", "wood_shovel","1.6"),
    TEXTURES_ITEM_WOODEN_SWORD("textures\\item", "wooden_sword", "wood_sword","1.6"),
    TEXTURES_ITEM_WRITABLE_BOOK("textures\\item", "writable_book", "book_writable", "1.6"),
    TEXTURES_ITEM_WRITTEN_BOOK("textures\\item", "written_book", "book_written", "1.6"),
    TEXTURES_ITEM_YELLOW_CANDLE("textures\\item", "yellow_candle", "1.17"),
    TEXTURES_ITEM_YELLOW_DYE("textures\\item", "yellow_dye", "dye_powder_yellow", "1.6"),


    foo("foo", "foo²", "foo³");


    Item(String dir, String nameNew, String nameOld, String introducedVersion) {
        this.dir = dir;
        this.nameNew = nameNew;
        this.nameOld = nameOld;
        this.introducedVersion = introducedVersion;
    }

    Item(String dir, String nameNew, String introducedVersion) {
        this.dir = dir;
        this.nameNew = nameNew;
        this.nameOld = nameNew;
        this.introducedVersion = introducedVersion;
    }



    private final String dir;
    private final String nameNew;
    private final String nameOld;
    private final String introducedVersion;

    @Override
    public String getDirectory() {
        return dir;
    }

    @Override
    public String getNewerName() {
        return nameNew;
    }

    @Override
    public String getOlderNames() {
        return nameOld;
    }

    @Override
    public String getIntroducedVersion() {
        return introducedVersion;
    }


}
